package com.model;
// Generated Nov 18, 2017 10:10:38 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client")
public class Client implements java.io.Serializable {

	private ClientId id;
	private String firstname;
	private String password;
	private String profession;
	private Date birthdate;
	private String lastname;
	private String socialstatus;

	public Client() {
	}

	public Client(ClientId id, String firstname, String password, String profession, Date birthdate, String lastname,
			String socialstatus) {
		this.id = id;
		this.firstname = firstname;
		this.password = password;
		this.profession = profession;
		this.birthdate = birthdate;
		this.lastname = lastname;
		this.socialstatus = socialstatus;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCard", column = @Column(name = "id_card", nullable = false, length = 64)),
			@AttributeOverride(name = "login", column = @Column(name = "login", nullable = false, length = 64)) })
	public ClientId getId() {
		return this.id;
	}

	public void setId(ClientId id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false, length = 64)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "profession", nullable = false, length = 64)
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birthdate", nullable = false, length = 8)
	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "lastname", nullable = false, length = 64)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "socialstatus", nullable = false, length = 64)
	public String getSocialstatus() {
		return this.socialstatus;
	}

	public void setSocialstatus(String socialstatus) {
		this.socialstatus = socialstatus;
	}

}
