package com.model;
// Generated Nov 4, 2017 10:45:47 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client")
public class Client implements java.io.Serializable {

	private ClientId id;

	public Client() {
	}

	public Client(ClientId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCard", column = @Column(name = "ID_card", nullable = false, length = 64)),
			@AttributeOverride(name = "firstname", column = @Column(name = "Firstname", length = 64)),
			@AttributeOverride(name = "lastName", column = @Column(name = "LastName", length = 64)),
			@AttributeOverride(name = "profession", column = @Column(name = "Profession", length = 64)),
			@AttributeOverride(name = "login", column = @Column(name = "Login", nullable = false, length = 64)),
			@AttributeOverride(name = "password", column = @Column(name = "Password", length = 64)),
			@AttributeOverride(name = "socialStatus", column = @Column(name = "SocialStatus", length = 64)),
			@AttributeOverride(name = "birthDate", column = @Column(name = "BirthDate", length = 4)) })
	public ClientId getId() {
		return this.id;
	}

	public void setId(ClientId id) {
		this.id = id;
	}

}
