package com.model;
// Generated Nov 18, 2017 10:10:38 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdersId generated by hbm2java
 */
@Embeddable
public class OrdersId implements java.io.Serializable {

	private double cost;
	private Date date;
	private String idCard;
	private int idProduct;
	private int quantity;
	private Date time;

	public OrdersId() {
	}

	public OrdersId(double cost, Date date, String idCard, int idProduct, int quantity, Date time) {
		this.cost = cost;
		this.date = date;
		this.idCard = idCard;
		this.idProduct = idProduct;
		this.quantity = quantity;
		this.time = time;
	}

	@Column(name = "cost", nullable = false, precision = 8, scale = 0)
	public double getCost() {
		return this.cost;
	}

	public void setCost(double cost) {
		this.cost = cost;
	}

	@Column(name = "date", nullable = false, length = 8)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "id_card", nullable = false, length = 64)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "time", nullable = false, length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdersId))
			return false;
		OrdersId castOther = (OrdersId) other;

		return (this.getCost() == castOther.getCost())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getIdCard() == castOther.getIdCard()) || (this.getIdCard() != null
						&& castOther.getIdCard() != null && this.getIdCard().equals(castOther.getIdCard())))
				&& (this.getIdProduct() == castOther.getIdProduct()) && (this.getQuantity() == castOther.getQuantity())
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null
						&& this.getTime().equals(castOther.getTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCost();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getIdCard() == null ? 0 : this.getIdCard().hashCode());
		result = 37 * result + this.getIdProduct();
		result = 37 * result + this.getQuantity();
		result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
		return result;
	}

}
