package com.model;
// Generated Nov 18, 2017 10:10:38 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders")
public class Orders implements java.io.Serializable {

	private OrdersId id;

	public Orders() {
	}

	public Orders(OrdersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cost", column = @Column(name = "cost", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 8)),
			@AttributeOverride(name = "idCard", column = @Column(name = "id_card", nullable = false, length = 64)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "quantity", column = @Column(name = "quantity", nullable = false)),
			@AttributeOverride(name = "time", column = @Column(name = "time", nullable = false, length = 8)) })
	public OrdersId getId() {
		return this.id;
	}

	public void setId(OrdersId id) {
		this.id = id;
	}

}
