package com.model;
// Generated Nov 18, 2017 10:10:38 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProviderId generated by hbm2java
 */
@Embeddable
public class ProviderId implements java.io.Serializable {

	private String idCard;
	private String login;

	public ProviderId() {
	}

	public ProviderId(String idCard, String login) {
		this.idCard = idCard;
		this.login = login;
	}

	@Column(name = "id_card", nullable = false, length = 64)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "login", nullable = false, length = 64)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProviderId))
			return false;
		ProviderId castOther = (ProviderId) other;

		return ((this.getIdCard() == castOther.getIdCard()) || (this.getIdCard() != null
				&& castOther.getIdCard() != null && this.getIdCard().equals(castOther.getIdCard())))
				&& ((this.getLogin() == castOther.getLogin()) || (this.getLogin() != null
						&& castOther.getLogin() != null && this.getLogin().equals(castOther.getLogin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdCard() == null ? 0 : this.getIdCard().hashCode());
		result = 37 * result + (getLogin() == null ? 0 : this.getLogin().hashCode());
		return result;
	}

}
