package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", schema = "public")
public class Orders implements java.io.Serializable {

	private OrdersId id;

	public Orders() {
	}

	public Orders(OrdersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "date", column = @Column(name = "Date", length = 4)),
			@AttributeOverride(name = "time", column = @Column(name = "Time", length = 8)),
			@AttributeOverride(name = "quantity", column = @Column(name = "Quantity")),
			@AttributeOverride(name = "cost", column = @Column(name = "Cost", precision = 8, scale = 0)),
			@AttributeOverride(name = "idCard", column = @Column(name = "ID_Card", length = 64)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "ID_Product")) })
	public OrdersId getId() {
		return this.id;
	}

	public void setId(OrdersId id) {
		this.id = id;
	}

}
