package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", schema = "public")
public class Person implements java.io.Serializable {

	private PersonId id;
	private String firstname;
	private String lastName;
	private String profession;
	private String password;
	private String socialStatus;
	private Date birthDate;

	public Person() {
	}

	public Person(PersonId id) {
		this.id = id;
	}

	public Person(PersonId id, String firstname, String lastName, String profession, String password,
			String socialStatus, Date birthDate) {
		this.id = id;
		this.firstname = firstname;
		this.lastName = lastName;
		this.profession = profession;
		this.password = password;
		this.socialStatus = socialStatus;
		this.birthDate = birthDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCard", column = @Column(name = "ID_card", nullable = false, length = 64)),
			@AttributeOverride(name = "login", column = @Column(name = "Login", nullable = false, length = 64)) })
	public PersonId getId() {
		return this.id;
	}

	public void setId(PersonId id) {
		this.id = id;
	}

	@Column(name = "Firstname", length = 64)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LastName", length = 64)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Profession", length = 64)
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Column(name = "Password", length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "SocialStatus", length = 64)
	public String getSocialStatus() {
		return this.socialStatus;
	}

	public void setSocialStatus(String socialStatus) {
		this.socialStatus = socialStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BirthDate", length = 4)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

}
