package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgAggregate generated by hbm2java
 */
@Entity
@Table(name = "pg_aggregate", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = "aggfnoid"))
public class PgAggregate implements java.io.Serializable {

	private PgAggregateId id;

	public PgAggregate() {
	}

	public PgAggregate(PgAggregateId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "aggfnoid", column = @Column(name = "aggfnoid", unique = true, nullable = false)),
			@AttributeOverride(name = "aggkind", column = @Column(name = "aggkind", nullable = false)),
			@AttributeOverride(name = "aggnumdirectargs", column = @Column(name = "aggnumdirectargs", nullable = false)),
			@AttributeOverride(name = "aggtransfn", column = @Column(name = "aggtransfn", nullable = false)),
			@AttributeOverride(name = "aggfinalfn", column = @Column(name = "aggfinalfn", nullable = false)),
			@AttributeOverride(name = "aggcombinefn", column = @Column(name = "aggcombinefn", nullable = false)),
			@AttributeOverride(name = "aggserialfn", column = @Column(name = "aggserialfn", nullable = false)),
			@AttributeOverride(name = "aggdeserialfn", column = @Column(name = "aggdeserialfn", nullable = false)),
			@AttributeOverride(name = "aggmtransfn", column = @Column(name = "aggmtransfn", nullable = false)),
			@AttributeOverride(name = "aggminvtransfn", column = @Column(name = "aggminvtransfn", nullable = false)),
			@AttributeOverride(name = "aggmfinalfn", column = @Column(name = "aggmfinalfn", nullable = false)),
			@AttributeOverride(name = "aggfinalextra", column = @Column(name = "aggfinalextra", nullable = false)),
			@AttributeOverride(name = "aggmfinalextra", column = @Column(name = "aggmfinalextra", nullable = false)),
			@AttributeOverride(name = "aggsortop", column = @Column(name = "aggsortop", nullable = false)),
			@AttributeOverride(name = "aggtranstype", column = @Column(name = "aggtranstype", nullable = false)),
			@AttributeOverride(name = "aggtransspace", column = @Column(name = "aggtransspace", nullable = false)),
			@AttributeOverride(name = "aggmtranstype", column = @Column(name = "aggmtranstype", nullable = false)),
			@AttributeOverride(name = "aggmtransspace", column = @Column(name = "aggmtransspace", nullable = false)),
			@AttributeOverride(name = "agginitval", column = @Column(name = "agginitval")),
			@AttributeOverride(name = "aggminitval", column = @Column(name = "aggminitval")) })
	public PgAggregateId getId() {
		return this.id;
	}

	public void setId(PgAggregateId id) {
		this.id = id;
	}

}
