package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgAmproc generated by hbm2java
 */
@Entity
@Table(name = "pg_amproc", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "amprocfamily", "amproclefttype", "amprocrighttype", "amprocnum" }),
		@UniqueConstraint(columnNames = "oid") })
public class PgAmproc implements java.io.Serializable {

	private PgAmprocId id;

	public PgAmproc() {
	}

	public PgAmproc(PgAmprocId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "amprocfamily", column = @Column(name = "amprocfamily", nullable = false)),
			@AttributeOverride(name = "amproclefttype", column = @Column(name = "amproclefttype", nullable = false)),
			@AttributeOverride(name = "amprocrighttype", column = @Column(name = "amprocrighttype", nullable = false)),
			@AttributeOverride(name = "amprocnum", column = @Column(name = "amprocnum", nullable = false)),
			@AttributeOverride(name = "amproc", column = @Column(name = "amproc", nullable = false)) })
	public PgAmprocId getId() {
		return this.id;
	}

	public void setId(PgAmprocId id) {
		this.id = id;
	}

}
