package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgAmId generated by hbm2java
 */
@Embeddable
public class PgAmId implements java.io.Serializable {

	private String amname;
	private Serializable amhandler;
	private Serializable amtype;

	public PgAmId() {
	}

	public PgAmId(String amname, Serializable amhandler, Serializable amtype) {
		this.amname = amname;
		this.amhandler = amhandler;
		this.amtype = amtype;
	}

	@Column(name = "amname", unique = true, nullable = false, length = 64)
	public String getAmname() {
		return this.amname;
	}

	public void setAmname(String amname) {
		this.amname = amname;
	}

	@Column(name = "amhandler", nullable = false)
	public Serializable getAmhandler() {
		return this.amhandler;
	}

	public void setAmhandler(Serializable amhandler) {
		this.amhandler = amhandler;
	}

	@Column(name = "amtype", nullable = false)
	public Serializable getAmtype() {
		return this.amtype;
	}

	public void setAmtype(Serializable amtype) {
		this.amtype = amtype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgAmId))
			return false;
		PgAmId castOther = (PgAmId) other;

		return ((this.getAmname() == castOther.getAmname()) || (this.getAmname() != null
				&& castOther.getAmname() != null && this.getAmname().equals(castOther.getAmname())))
				&& ((this.getAmhandler() == castOther.getAmhandler()) || (this.getAmhandler() != null
						&& castOther.getAmhandler() != null && this.getAmhandler().equals(castOther.getAmhandler())))
				&& ((this.getAmtype() == castOther.getAmtype()) || (this.getAmtype() != null
						&& castOther.getAmtype() != null && this.getAmtype().equals(castOther.getAmtype())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAmname() == null ? 0 : this.getAmname().hashCode());
		result = 37 * result + (getAmhandler() == null ? 0 : this.getAmhandler().hashCode());
		result = 37 * result + (getAmtype() == null ? 0 : this.getAmtype().hashCode());
		return result;
	}

}
