package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgAmprocId generated by hbm2java
 */
@Embeddable
public class PgAmprocId implements java.io.Serializable {

	private int amprocfamily;
	private int amproclefttype;
	private int amprocrighttype;
	private short amprocnum;
	private Serializable amproc;

	public PgAmprocId() {
	}

	public PgAmprocId(int amprocfamily, int amproclefttype, int amprocrighttype, short amprocnum, Serializable amproc) {
		this.amprocfamily = amprocfamily;
		this.amproclefttype = amproclefttype;
		this.amprocrighttype = amprocrighttype;
		this.amprocnum = amprocnum;
		this.amproc = amproc;
	}

	@Column(name = "amprocfamily", nullable = false)
	public int getAmprocfamily() {
		return this.amprocfamily;
	}

	public void setAmprocfamily(int amprocfamily) {
		this.amprocfamily = amprocfamily;
	}

	@Column(name = "amproclefttype", nullable = false)
	public int getAmproclefttype() {
		return this.amproclefttype;
	}

	public void setAmproclefttype(int amproclefttype) {
		this.amproclefttype = amproclefttype;
	}

	@Column(name = "amprocrighttype", nullable = false)
	public int getAmprocrighttype() {
		return this.amprocrighttype;
	}

	public void setAmprocrighttype(int amprocrighttype) {
		this.amprocrighttype = amprocrighttype;
	}

	@Column(name = "amprocnum", nullable = false)
	public short getAmprocnum() {
		return this.amprocnum;
	}

	public void setAmprocnum(short amprocnum) {
		this.amprocnum = amprocnum;
	}

	@Column(name = "amproc", nullable = false)
	public Serializable getAmproc() {
		return this.amproc;
	}

	public void setAmproc(Serializable amproc) {
		this.amproc = amproc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgAmprocId))
			return false;
		PgAmprocId castOther = (PgAmprocId) other;

		return (this.getAmprocfamily() == castOther.getAmprocfamily())
				&& (this.getAmproclefttype() == castOther.getAmproclefttype())
				&& (this.getAmprocrighttype() == castOther.getAmprocrighttype())
				&& (this.getAmprocnum() == castOther.getAmprocnum())
				&& ((this.getAmproc() == castOther.getAmproc()) || (this.getAmproc() != null
						&& castOther.getAmproc() != null && this.getAmproc().equals(castOther.getAmproc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAmprocfamily();
		result = 37 * result + this.getAmproclefttype();
		result = 37 * result + this.getAmprocrighttype();
		result = 37 * result + this.getAmprocnum();
		result = 37 * result + (getAmproc() == null ? 0 : this.getAmproc().hashCode());
		return result;
	}

}
