package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgAttrdef generated by hbm2java
 */
@Entity
@Table(name = "pg_attrdef", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "adrelid", "adnum" }), @UniqueConstraint(columnNames = "oid") })
public class PgAttrdef implements java.io.Serializable {

	private PgAttrdefId id;

	public PgAttrdef() {
	}

	public PgAttrdef(PgAttrdefId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "adrelid", column = @Column(name = "adrelid", nullable = false)),
			@AttributeOverride(name = "adnum", column = @Column(name = "adnum", nullable = false)),
			@AttributeOverride(name = "adbin", column = @Column(name = "adbin")),
			@AttributeOverride(name = "adsrc", column = @Column(name = "adsrc")) })
	public PgAttrdefId getId() {
		return this.id;
	}

	public void setId(PgAttrdefId id) {
		this.id = id;
	}

}
