package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgAttributeId generated by hbm2java
 */
@Embeddable
public class PgAttributeId implements java.io.Serializable {

	private int attrelid;
	private String attname;
	private int atttypid;
	private int attstattarget;
	private short attlen;
	private short attnum;
	private int attndims;
	private int attcacheoff;
	private int atttypmod;
	private boolean attbyval;
	private Serializable attstorage;
	private Serializable attalign;
	private boolean attnotnull;
	private boolean atthasdef;
	private boolean attisdropped;
	private boolean attislocal;
	private int attinhcount;
	private int attcollation;
	private Serializable attacl;
	private Serializable attoptions;
	private Serializable attfdwoptions;

	public PgAttributeId() {
	}

	public PgAttributeId(int attrelid, String attname, int atttypid, int attstattarget, short attlen, short attnum,
			int attndims, int attcacheoff, int atttypmod, boolean attbyval, Serializable attstorage,
			Serializable attalign, boolean attnotnull, boolean atthasdef, boolean attisdropped, boolean attislocal,
			int attinhcount, int attcollation) {
		this.attrelid = attrelid;
		this.attname = attname;
		this.atttypid = atttypid;
		this.attstattarget = attstattarget;
		this.attlen = attlen;
		this.attnum = attnum;
		this.attndims = attndims;
		this.attcacheoff = attcacheoff;
		this.atttypmod = atttypmod;
		this.attbyval = attbyval;
		this.attstorage = attstorage;
		this.attalign = attalign;
		this.attnotnull = attnotnull;
		this.atthasdef = atthasdef;
		this.attisdropped = attisdropped;
		this.attislocal = attislocal;
		this.attinhcount = attinhcount;
		this.attcollation = attcollation;
	}

	public PgAttributeId(int attrelid, String attname, int atttypid, int attstattarget, short attlen, short attnum,
			int attndims, int attcacheoff, int atttypmod, boolean attbyval, Serializable attstorage,
			Serializable attalign, boolean attnotnull, boolean atthasdef, boolean attisdropped, boolean attislocal,
			int attinhcount, int attcollation, Serializable attacl, Serializable attoptions,
			Serializable attfdwoptions) {
		this.attrelid = attrelid;
		this.attname = attname;
		this.atttypid = atttypid;
		this.attstattarget = attstattarget;
		this.attlen = attlen;
		this.attnum = attnum;
		this.attndims = attndims;
		this.attcacheoff = attcacheoff;
		this.atttypmod = atttypmod;
		this.attbyval = attbyval;
		this.attstorage = attstorage;
		this.attalign = attalign;
		this.attnotnull = attnotnull;
		this.atthasdef = atthasdef;
		this.attisdropped = attisdropped;
		this.attislocal = attislocal;
		this.attinhcount = attinhcount;
		this.attcollation = attcollation;
		this.attacl = attacl;
		this.attoptions = attoptions;
		this.attfdwoptions = attfdwoptions;
	}

	@Column(name = "attrelid", nullable = false)
	public int getAttrelid() {
		return this.attrelid;
	}

	public void setAttrelid(int attrelid) {
		this.attrelid = attrelid;
	}

	@Column(name = "attname", nullable = false, length = 64)
	public String getAttname() {
		return this.attname;
	}

	public void setAttname(String attname) {
		this.attname = attname;
	}

	@Column(name = "atttypid", nullable = false)
	public int getAtttypid() {
		return this.atttypid;
	}

	public void setAtttypid(int atttypid) {
		this.atttypid = atttypid;
	}

	@Column(name = "attstattarget", nullable = false)
	public int getAttstattarget() {
		return this.attstattarget;
	}

	public void setAttstattarget(int attstattarget) {
		this.attstattarget = attstattarget;
	}

	@Column(name = "attlen", nullable = false)
	public short getAttlen() {
		return this.attlen;
	}

	public void setAttlen(short attlen) {
		this.attlen = attlen;
	}

	@Column(name = "attnum", nullable = false)
	public short getAttnum() {
		return this.attnum;
	}

	public void setAttnum(short attnum) {
		this.attnum = attnum;
	}

	@Column(name = "attndims", nullable = false)
	public int getAttndims() {
		return this.attndims;
	}

	public void setAttndims(int attndims) {
		this.attndims = attndims;
	}

	@Column(name = "attcacheoff", nullable = false)
	public int getAttcacheoff() {
		return this.attcacheoff;
	}

	public void setAttcacheoff(int attcacheoff) {
		this.attcacheoff = attcacheoff;
	}

	@Column(name = "atttypmod", nullable = false)
	public int getAtttypmod() {
		return this.atttypmod;
	}

	public void setAtttypmod(int atttypmod) {
		this.atttypmod = atttypmod;
	}

	@Column(name = "attbyval", nullable = false)
	public boolean isAttbyval() {
		return this.attbyval;
	}

	public void setAttbyval(boolean attbyval) {
		this.attbyval = attbyval;
	}

	@Column(name = "attstorage", nullable = false)
	public Serializable getAttstorage() {
		return this.attstorage;
	}

	public void setAttstorage(Serializable attstorage) {
		this.attstorage = attstorage;
	}

	@Column(name = "attalign", nullable = false)
	public Serializable getAttalign() {
		return this.attalign;
	}

	public void setAttalign(Serializable attalign) {
		this.attalign = attalign;
	}

	@Column(name = "attnotnull", nullable = false)
	public boolean isAttnotnull() {
		return this.attnotnull;
	}

	public void setAttnotnull(boolean attnotnull) {
		this.attnotnull = attnotnull;
	}

	@Column(name = "atthasdef", nullable = false)
	public boolean isAtthasdef() {
		return this.atthasdef;
	}

	public void setAtthasdef(boolean atthasdef) {
		this.atthasdef = atthasdef;
	}

	@Column(name = "attisdropped", nullable = false)
	public boolean isAttisdropped() {
		return this.attisdropped;
	}

	public void setAttisdropped(boolean attisdropped) {
		this.attisdropped = attisdropped;
	}

	@Column(name = "attislocal", nullable = false)
	public boolean isAttislocal() {
		return this.attislocal;
	}

	public void setAttislocal(boolean attislocal) {
		this.attislocal = attislocal;
	}

	@Column(name = "attinhcount", nullable = false)
	public int getAttinhcount() {
		return this.attinhcount;
	}

	public void setAttinhcount(int attinhcount) {
		this.attinhcount = attinhcount;
	}

	@Column(name = "attcollation", nullable = false)
	public int getAttcollation() {
		return this.attcollation;
	}

	public void setAttcollation(int attcollation) {
		this.attcollation = attcollation;
	}

	@Column(name = "attacl")
	public Serializable getAttacl() {
		return this.attacl;
	}

	public void setAttacl(Serializable attacl) {
		this.attacl = attacl;
	}

	@Column(name = "attoptions")
	public Serializable getAttoptions() {
		return this.attoptions;
	}

	public void setAttoptions(Serializable attoptions) {
		this.attoptions = attoptions;
	}

	@Column(name = "attfdwoptions")
	public Serializable getAttfdwoptions() {
		return this.attfdwoptions;
	}

	public void setAttfdwoptions(Serializable attfdwoptions) {
		this.attfdwoptions = attfdwoptions;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgAttributeId))
			return false;
		PgAttributeId castOther = (PgAttributeId) other;

		return (this.getAttrelid() == castOther.getAttrelid())
				&& ((this.getAttname() == castOther.getAttname()) || (this.getAttname() != null
						&& castOther.getAttname() != null && this.getAttname().equals(castOther.getAttname())))
				&& (this.getAtttypid() == castOther.getAtttypid())
				&& (this.getAttstattarget() == castOther.getAttstattarget())
				&& (this.getAttlen() == castOther.getAttlen()) && (this.getAttnum() == castOther.getAttnum())
				&& (this.getAttndims() == castOther.getAttndims())
				&& (this.getAttcacheoff() == castOther.getAttcacheoff())
				&& (this.getAtttypmod() == castOther.getAtttypmod()) && (this.isAttbyval() == castOther.isAttbyval())
				&& ((this.getAttstorage() == castOther.getAttstorage()) || (this.getAttstorage() != null
						&& castOther.getAttstorage() != null && this.getAttstorage().equals(castOther.getAttstorage())))
				&& ((this.getAttalign() == castOther.getAttalign()) || (this.getAttalign() != null
						&& castOther.getAttalign() != null && this.getAttalign().equals(castOther.getAttalign())))
				&& (this.isAttnotnull() == castOther.isAttnotnull()) && (this.isAtthasdef() == castOther.isAtthasdef())
				&& (this.isAttisdropped() == castOther.isAttisdropped())
				&& (this.isAttislocal() == castOther.isAttislocal())
				&& (this.getAttinhcount() == castOther.getAttinhcount())
				&& (this.getAttcollation() == castOther.getAttcollation())
				&& ((this.getAttacl() == castOther.getAttacl()) || (this.getAttacl() != null
						&& castOther.getAttacl() != null && this.getAttacl().equals(castOther.getAttacl())))
				&& ((this.getAttoptions() == castOther.getAttoptions()) || (this.getAttoptions() != null
						&& castOther.getAttoptions() != null && this.getAttoptions().equals(castOther.getAttoptions())))
				&& ((this.getAttfdwoptions() == castOther.getAttfdwoptions())
						|| (this.getAttfdwoptions() != null && castOther.getAttfdwoptions() != null
								&& this.getAttfdwoptions().equals(castOther.getAttfdwoptions())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAttrelid();
		result = 37 * result + (getAttname() == null ? 0 : this.getAttname().hashCode());
		result = 37 * result + this.getAtttypid();
		result = 37 * result + this.getAttstattarget();
		result = 37 * result + this.getAttlen();
		result = 37 * result + this.getAttnum();
		result = 37 * result + this.getAttndims();
		result = 37 * result + this.getAttcacheoff();
		result = 37 * result + this.getAtttypmod();
		result = 37 * result + (this.isAttbyval() ? 1 : 0);
		result = 37 * result + (getAttstorage() == null ? 0 : this.getAttstorage().hashCode());
		result = 37 * result + (getAttalign() == null ? 0 : this.getAttalign().hashCode());
		result = 37 * result + (this.isAttnotnull() ? 1 : 0);
		result = 37 * result + (this.isAtthasdef() ? 1 : 0);
		result = 37 * result + (this.isAttisdropped() ? 1 : 0);
		result = 37 * result + (this.isAttislocal() ? 1 : 0);
		result = 37 * result + this.getAttinhcount();
		result = 37 * result + this.getAttcollation();
		result = 37 * result + (getAttacl() == null ? 0 : this.getAttacl().hashCode());
		result = 37 * result + (getAttoptions() == null ? 0 : this.getAttoptions().hashCode());
		result = 37 * result + (getAttfdwoptions() == null ? 0 : this.getAttfdwoptions().hashCode());
		return result;
	}

}
