package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgAttribute generated by hbm2java
 */
@Entity
@Table(name = "pg_attribute", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "attrelid", "attname" }),
		@UniqueConstraint(columnNames = { "attrelid", "attnum" }) })
public class PgAttribute implements java.io.Serializable {

	private PgAttributeId id;

	public PgAttribute() {
	}

	public PgAttribute(PgAttributeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "attrelid", column = @Column(name = "attrelid", nullable = false)),
			@AttributeOverride(name = "attname", column = @Column(name = "attname", nullable = false, length = 64)),
			@AttributeOverride(name = "atttypid", column = @Column(name = "atttypid", nullable = false)),
			@AttributeOverride(name = "attstattarget", column = @Column(name = "attstattarget", nullable = false)),
			@AttributeOverride(name = "attlen", column = @Column(name = "attlen", nullable = false)),
			@AttributeOverride(name = "attnum", column = @Column(name = "attnum", nullable = false)),
			@AttributeOverride(name = "attndims", column = @Column(name = "attndims", nullable = false)),
			@AttributeOverride(name = "attcacheoff", column = @Column(name = "attcacheoff", nullable = false)),
			@AttributeOverride(name = "atttypmod", column = @Column(name = "atttypmod", nullable = false)),
			@AttributeOverride(name = "attbyval", column = @Column(name = "attbyval", nullable = false)),
			@AttributeOverride(name = "attstorage", column = @Column(name = "attstorage", nullable = false)),
			@AttributeOverride(name = "attalign", column = @Column(name = "attalign", nullable = false)),
			@AttributeOverride(name = "attnotnull", column = @Column(name = "attnotnull", nullable = false)),
			@AttributeOverride(name = "atthasdef", column = @Column(name = "atthasdef", nullable = false)),
			@AttributeOverride(name = "attisdropped", column = @Column(name = "attisdropped", nullable = false)),
			@AttributeOverride(name = "attislocal", column = @Column(name = "attislocal", nullable = false)),
			@AttributeOverride(name = "attinhcount", column = @Column(name = "attinhcount", nullable = false)),
			@AttributeOverride(name = "attcollation", column = @Column(name = "attcollation", nullable = false)),
			@AttributeOverride(name = "attacl", column = @Column(name = "attacl")),
			@AttributeOverride(name = "attoptions", column = @Column(name = "attoptions")),
			@AttributeOverride(name = "attfdwoptions", column = @Column(name = "attfdwoptions")) })
	public PgAttributeId getId() {
		return this.id;
	}

	public void setId(PgAttributeId id) {
		this.id = id;
	}

}
