package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgAttrdefId generated by hbm2java
 */
@Embeddable
public class PgAttrdefId implements java.io.Serializable {

	private int adrelid;
	private short adnum;
	private Serializable adbin;
	private String adsrc;

	public PgAttrdefId() {
	}

	public PgAttrdefId(int adrelid, short adnum) {
		this.adrelid = adrelid;
		this.adnum = adnum;
	}

	public PgAttrdefId(int adrelid, short adnum, Serializable adbin, String adsrc) {
		this.adrelid = adrelid;
		this.adnum = adnum;
		this.adbin = adbin;
		this.adsrc = adsrc;
	}

	@Column(name = "adrelid", nullable = false)
	public int getAdrelid() {
		return this.adrelid;
	}

	public void setAdrelid(int adrelid) {
		this.adrelid = adrelid;
	}

	@Column(name = "adnum", nullable = false)
	public short getAdnum() {
		return this.adnum;
	}

	public void setAdnum(short adnum) {
		this.adnum = adnum;
	}

	@Column(name = "adbin")
	public Serializable getAdbin() {
		return this.adbin;
	}

	public void setAdbin(Serializable adbin) {
		this.adbin = adbin;
	}

	@Column(name = "adsrc")
	public String getAdsrc() {
		return this.adsrc;
	}

	public void setAdsrc(String adsrc) {
		this.adsrc = adsrc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgAttrdefId))
			return false;
		PgAttrdefId castOther = (PgAttrdefId) other;

		return (this.getAdrelid() == castOther.getAdrelid()) && (this.getAdnum() == castOther.getAdnum())
				&& ((this.getAdbin() == castOther.getAdbin()) || (this.getAdbin() != null
						&& castOther.getAdbin() != null && this.getAdbin().equals(castOther.getAdbin())))
				&& ((this.getAdsrc() == castOther.getAdsrc()) || (this.getAdsrc() != null
						&& castOther.getAdsrc() != null && this.getAdsrc().equals(castOther.getAdsrc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAdrelid();
		result = 37 * result + this.getAdnum();
		result = 37 * result + (getAdbin() == null ? 0 : this.getAdbin().hashCode());
		result = 37 * result + (getAdsrc() == null ? 0 : this.getAdsrc().hashCode());
		return result;
	}

}
