package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgAuthidId generated by hbm2java
 */
@Embeddable
public class PgAuthidId implements java.io.Serializable {

	private String rolname;
	private boolean rolsuper;
	private boolean rolinherit;
	private boolean rolcreaterole;
	private boolean rolcreatedb;
	private boolean rolcanlogin;
	private boolean rolreplication;
	private boolean rolbypassrls;
	private int rolconnlimit;
	private String rolpassword;
	private Date rolvaliduntil;

	public PgAuthidId() {
	}

	public PgAuthidId(String rolname, boolean rolsuper, boolean rolinherit, boolean rolcreaterole, boolean rolcreatedb,
			boolean rolcanlogin, boolean rolreplication, boolean rolbypassrls, int rolconnlimit) {
		this.rolname = rolname;
		this.rolsuper = rolsuper;
		this.rolinherit = rolinherit;
		this.rolcreaterole = rolcreaterole;
		this.rolcreatedb = rolcreatedb;
		this.rolcanlogin = rolcanlogin;
		this.rolreplication = rolreplication;
		this.rolbypassrls = rolbypassrls;
		this.rolconnlimit = rolconnlimit;
	}

	public PgAuthidId(String rolname, boolean rolsuper, boolean rolinherit, boolean rolcreaterole, boolean rolcreatedb,
			boolean rolcanlogin, boolean rolreplication, boolean rolbypassrls, int rolconnlimit, String rolpassword,
			Date rolvaliduntil) {
		this.rolname = rolname;
		this.rolsuper = rolsuper;
		this.rolinherit = rolinherit;
		this.rolcreaterole = rolcreaterole;
		this.rolcreatedb = rolcreatedb;
		this.rolcanlogin = rolcanlogin;
		this.rolreplication = rolreplication;
		this.rolbypassrls = rolbypassrls;
		this.rolconnlimit = rolconnlimit;
		this.rolpassword = rolpassword;
		this.rolvaliduntil = rolvaliduntil;
	}

	@Column(name = "rolname", unique = true, nullable = false, length = 64)
	public String getRolname() {
		return this.rolname;
	}

	public void setRolname(String rolname) {
		this.rolname = rolname;
	}

	@Column(name = "rolsuper", nullable = false)
	public boolean isRolsuper() {
		return this.rolsuper;
	}

	public void setRolsuper(boolean rolsuper) {
		this.rolsuper = rolsuper;
	}

	@Column(name = "rolinherit", nullable = false)
	public boolean isRolinherit() {
		return this.rolinherit;
	}

	public void setRolinherit(boolean rolinherit) {
		this.rolinherit = rolinherit;
	}

	@Column(name = "rolcreaterole", nullable = false)
	public boolean isRolcreaterole() {
		return this.rolcreaterole;
	}

	public void setRolcreaterole(boolean rolcreaterole) {
		this.rolcreaterole = rolcreaterole;
	}

	@Column(name = "rolcreatedb", nullable = false)
	public boolean isRolcreatedb() {
		return this.rolcreatedb;
	}

	public void setRolcreatedb(boolean rolcreatedb) {
		this.rolcreatedb = rolcreatedb;
	}

	@Column(name = "rolcanlogin", nullable = false)
	public boolean isRolcanlogin() {
		return this.rolcanlogin;
	}

	public void setRolcanlogin(boolean rolcanlogin) {
		this.rolcanlogin = rolcanlogin;
	}

	@Column(name = "rolreplication", nullable = false)
	public boolean isRolreplication() {
		return this.rolreplication;
	}

	public void setRolreplication(boolean rolreplication) {
		this.rolreplication = rolreplication;
	}

	@Column(name = "rolbypassrls", nullable = false)
	public boolean isRolbypassrls() {
		return this.rolbypassrls;
	}

	public void setRolbypassrls(boolean rolbypassrls) {
		this.rolbypassrls = rolbypassrls;
	}

	@Column(name = "rolconnlimit", nullable = false)
	public int getRolconnlimit() {
		return this.rolconnlimit;
	}

	public void setRolconnlimit(int rolconnlimit) {
		this.rolconnlimit = rolconnlimit;
	}

	@Column(name = "rolpassword")
	public String getRolpassword() {
		return this.rolpassword;
	}

	public void setRolpassword(String rolpassword) {
		this.rolpassword = rolpassword;
	}

	@Column(name = "rolvaliduntil", length = 8)
	public Date getRolvaliduntil() {
		return this.rolvaliduntil;
	}

	public void setRolvaliduntil(Date rolvaliduntil) {
		this.rolvaliduntil = rolvaliduntil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgAuthidId))
			return false;
		PgAuthidId castOther = (PgAuthidId) other;

		return ((this.getRolname() == castOther.getRolname()) || (this.getRolname() != null
				&& castOther.getRolname() != null && this.getRolname().equals(castOther.getRolname())))
				&& (this.isRolsuper() == castOther.isRolsuper()) && (this.isRolinherit() == castOther.isRolinherit())
				&& (this.isRolcreaterole() == castOther.isRolcreaterole())
				&& (this.isRolcreatedb() == castOther.isRolcreatedb())
				&& (this.isRolcanlogin() == castOther.isRolcanlogin())
				&& (this.isRolreplication() == castOther.isRolreplication())
				&& (this.isRolbypassrls() == castOther.isRolbypassrls())
				&& (this.getRolconnlimit() == castOther.getRolconnlimit())
				&& ((this.getRolpassword() == castOther.getRolpassword())
						|| (this.getRolpassword() != null && castOther.getRolpassword() != null
								&& this.getRolpassword().equals(castOther.getRolpassword())))
				&& ((this.getRolvaliduntil() == castOther.getRolvaliduntil())
						|| (this.getRolvaliduntil() != null && castOther.getRolvaliduntil() != null
								&& this.getRolvaliduntil().equals(castOther.getRolvaliduntil())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRolname() == null ? 0 : this.getRolname().hashCode());
		result = 37 * result + (this.isRolsuper() ? 1 : 0);
		result = 37 * result + (this.isRolinherit() ? 1 : 0);
		result = 37 * result + (this.isRolcreaterole() ? 1 : 0);
		result = 37 * result + (this.isRolcreatedb() ? 1 : 0);
		result = 37 * result + (this.isRolcanlogin() ? 1 : 0);
		result = 37 * result + (this.isRolreplication() ? 1 : 0);
		result = 37 * result + (this.isRolbypassrls() ? 1 : 0);
		result = 37 * result + this.getRolconnlimit();
		result = 37 * result + (getRolpassword() == null ? 0 : this.getRolpassword().hashCode());
		result = 37 * result + (getRolvaliduntil() == null ? 0 : this.getRolvaliduntil().hashCode());
		return result;
	}

}
