package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgAuthMembers generated by hbm2java
 */
@Entity
@Table(name = "pg_auth_members", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = { "roleid",
		"member" }))
public class PgAuthMembers implements java.io.Serializable {

	private PgAuthMembersId id;

	public PgAuthMembers() {
	}

	public PgAuthMembers(PgAuthMembersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "roleid", column = @Column(name = "roleid", nullable = false)),
			@AttributeOverride(name = "member", column = @Column(name = "member", nullable = false)),
			@AttributeOverride(name = "grantor", column = @Column(name = "grantor", nullable = false)),
			@AttributeOverride(name = "adminOption", column = @Column(name = "admin_option", nullable = false)) })
	public PgAuthMembersId getId() {
		return this.id;
	}

	public void setId(PgAuthMembersId id) {
		this.id = id;
	}

}
