package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgAuthid generated by hbm2java
 */
@Entity
@Table(name = "pg_authid", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = "rolname") })
public class PgAuthid implements java.io.Serializable {

	private PgAuthidId id;

	public PgAuthid() {
	}

	public PgAuthid(PgAuthidId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rolname", column = @Column(name = "rolname", unique = true, nullable = false, length = 64)),
			@AttributeOverride(name = "rolsuper", column = @Column(name = "rolsuper", nullable = false)),
			@AttributeOverride(name = "rolinherit", column = @Column(name = "rolinherit", nullable = false)),
			@AttributeOverride(name = "rolcreaterole", column = @Column(name = "rolcreaterole", nullable = false)),
			@AttributeOverride(name = "rolcreatedb", column = @Column(name = "rolcreatedb", nullable = false)),
			@AttributeOverride(name = "rolcanlogin", column = @Column(name = "rolcanlogin", nullable = false)),
			@AttributeOverride(name = "rolreplication", column = @Column(name = "rolreplication", nullable = false)),
			@AttributeOverride(name = "rolbypassrls", column = @Column(name = "rolbypassrls", nullable = false)),
			@AttributeOverride(name = "rolconnlimit", column = @Column(name = "rolconnlimit", nullable = false)),
			@AttributeOverride(name = "rolpassword", column = @Column(name = "rolpassword")),
			@AttributeOverride(name = "rolvaliduntil", column = @Column(name = "rolvaliduntil", length = 8)) })
	public PgAuthidId getId() {
		return this.id;
	}

	public void setId(PgAuthidId id) {
		this.id = id;
	}

}
