package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgCast generated by hbm2java
 */
@Entity
@Table(name = "pg_cast", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "castsource", "casttarget" }) })
public class PgCast implements java.io.Serializable {

	private PgCastId id;

	public PgCast() {
	}

	public PgCast(PgCastId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "castsource", column = @Column(name = "castsource", nullable = false)),
			@AttributeOverride(name = "casttarget", column = @Column(name = "casttarget", nullable = false)),
			@AttributeOverride(name = "castfunc", column = @Column(name = "castfunc", nullable = false)),
			@AttributeOverride(name = "castcontext", column = @Column(name = "castcontext", nullable = false)),
			@AttributeOverride(name = "castmethod", column = @Column(name = "castmethod", nullable = false)) })
	public PgCastId getId() {
		return this.id;
	}

	public void setId(PgCastId id) {
		this.id = id;
	}

}
