package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgCastId generated by hbm2java
 */
@Embeddable
public class PgCastId implements java.io.Serializable {

	private int castsource;
	private int casttarget;
	private int castfunc;
	private Serializable castcontext;
	private Serializable castmethod;

	public PgCastId() {
	}

	public PgCastId(int castsource, int casttarget, int castfunc, Serializable castcontext, Serializable castmethod) {
		this.castsource = castsource;
		this.casttarget = casttarget;
		this.castfunc = castfunc;
		this.castcontext = castcontext;
		this.castmethod = castmethod;
	}

	@Column(name = "castsource", nullable = false)
	public int getCastsource() {
		return this.castsource;
	}

	public void setCastsource(int castsource) {
		this.castsource = castsource;
	}

	@Column(name = "casttarget", nullable = false)
	public int getCasttarget() {
		return this.casttarget;
	}

	public void setCasttarget(int casttarget) {
		this.casttarget = casttarget;
	}

	@Column(name = "castfunc", nullable = false)
	public int getCastfunc() {
		return this.castfunc;
	}

	public void setCastfunc(int castfunc) {
		this.castfunc = castfunc;
	}

	@Column(name = "castcontext", nullable = false)
	public Serializable getCastcontext() {
		return this.castcontext;
	}

	public void setCastcontext(Serializable castcontext) {
		this.castcontext = castcontext;
	}

	@Column(name = "castmethod", nullable = false)
	public Serializable getCastmethod() {
		return this.castmethod;
	}

	public void setCastmethod(Serializable castmethod) {
		this.castmethod = castmethod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgCastId))
			return false;
		PgCastId castOther = (PgCastId) other;

		return (this.getCastsource() == castOther.getCastsource())
				&& (this.getCasttarget() == castOther.getCasttarget())
				&& (this.getCastfunc() == castOther.getCastfunc())
				&& ((this.getCastcontext() == castOther.getCastcontext())
						|| (this.getCastcontext() != null && castOther.getCastcontext() != null
								&& this.getCastcontext().equals(castOther.getCastcontext())))
				&& ((this.getCastmethod() == castOther.getCastmethod())
						|| (this.getCastmethod() != null && castOther.getCastmethod() != null
								&& this.getCastmethod().equals(castOther.getCastmethod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCastsource();
		result = 37 * result + this.getCasttarget();
		result = 37 * result + this.getCastfunc();
		result = 37 * result + (getCastcontext() == null ? 0 : this.getCastcontext().hashCode());
		result = 37 * result + (getCastmethod() == null ? 0 : this.getCastmethod().hashCode());
		return result;
	}

}
