package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgClass generated by hbm2java
 */
@Entity
@Table(name = "pg_class", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "relname", "relnamespace" }) })
public class PgClass implements java.io.Serializable {

	private PgClassId id;

	public PgClass() {
	}

	public PgClass(PgClassId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "relname", column = @Column(name = "relname", nullable = false, length = 64)),
			@AttributeOverride(name = "relnamespace", column = @Column(name = "relnamespace", nullable = false)),
			@AttributeOverride(name = "reltype", column = @Column(name = "reltype", nullable = false)),
			@AttributeOverride(name = "reloftype", column = @Column(name = "reloftype", nullable = false)),
			@AttributeOverride(name = "relowner", column = @Column(name = "relowner", nullable = false)),
			@AttributeOverride(name = "relam", column = @Column(name = "relam", nullable = false)),
			@AttributeOverride(name = "relfilenode", column = @Column(name = "relfilenode", nullable = false)),
			@AttributeOverride(name = "reltablespace", column = @Column(name = "reltablespace", nullable = false)),
			@AttributeOverride(name = "relpages", column = @Column(name = "relpages", nullable = false)),
			@AttributeOverride(name = "reltuples", column = @Column(name = "reltuples", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "relallvisible", column = @Column(name = "relallvisible", nullable = false)),
			@AttributeOverride(name = "reltoastrelid", column = @Column(name = "reltoastrelid", nullable = false)),
			@AttributeOverride(name = "relhasindex", column = @Column(name = "relhasindex", nullable = false)),
			@AttributeOverride(name = "relisshared", column = @Column(name = "relisshared", nullable = false)),
			@AttributeOverride(name = "relpersistence", column = @Column(name = "relpersistence", nullable = false)),
			@AttributeOverride(name = "relkind", column = @Column(name = "relkind", nullable = false)),
			@AttributeOverride(name = "relnatts", column = @Column(name = "relnatts", nullable = false)),
			@AttributeOverride(name = "relchecks", column = @Column(name = "relchecks", nullable = false)),
			@AttributeOverride(name = "relhasoids", column = @Column(name = "relhasoids", nullable = false)),
			@AttributeOverride(name = "relhaspkey", column = @Column(name = "relhaspkey", nullable = false)),
			@AttributeOverride(name = "relhasrules", column = @Column(name = "relhasrules", nullable = false)),
			@AttributeOverride(name = "relhastriggers", column = @Column(name = "relhastriggers", nullable = false)),
			@AttributeOverride(name = "relhassubclass", column = @Column(name = "relhassubclass", nullable = false)),
			@AttributeOverride(name = "relrowsecurity", column = @Column(name = "relrowsecurity", nullable = false)),
			@AttributeOverride(name = "relforcerowsecurity", column = @Column(name = "relforcerowsecurity", nullable = false)),
			@AttributeOverride(name = "relispopulated", column = @Column(name = "relispopulated", nullable = false)),
			@AttributeOverride(name = "relreplident", column = @Column(name = "relreplident", nullable = false)),
			@AttributeOverride(name = "relfrozenxid", column = @Column(name = "relfrozenxid", nullable = false)),
			@AttributeOverride(name = "relminmxid", column = @Column(name = "relminmxid", nullable = false)),
			@AttributeOverride(name = "relacl", column = @Column(name = "relacl")),
			@AttributeOverride(name = "reloptions", column = @Column(name = "reloptions")) })
	public PgClassId getId() {
		return this.id;
	}

	public void setId(PgClassId id) {
		this.id = id;
	}

}
