package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgClassId generated by hbm2java
 */
@Embeddable
public class PgClassId implements java.io.Serializable {

	private String relname;
	private int relnamespace;
	private int reltype;
	private int reloftype;
	private int relowner;
	private int relam;
	private int relfilenode;
	private int reltablespace;
	private int relpages;
	private float reltuples;
	private int relallvisible;
	private int reltoastrelid;
	private boolean relhasindex;
	private boolean relisshared;
	private Serializable relpersistence;
	private Serializable relkind;
	private short relnatts;
	private short relchecks;
	private boolean relhasoids;
	private boolean relhaspkey;
	private boolean relhasrules;
	private boolean relhastriggers;
	private boolean relhassubclass;
	private boolean relrowsecurity;
	private boolean relforcerowsecurity;
	private boolean relispopulated;
	private Serializable relreplident;
	private Serializable relfrozenxid;
	private Serializable relminmxid;
	private Serializable relacl;
	private Serializable reloptions;

	public PgClassId() {
	}

	public PgClassId(String relname, int relnamespace, int reltype, int reloftype, int relowner, int relam,
			int relfilenode, int reltablespace, int relpages, float reltuples, int relallvisible, int reltoastrelid,
			boolean relhasindex, boolean relisshared, Serializable relpersistence, Serializable relkind, short relnatts,
			short relchecks, boolean relhasoids, boolean relhaspkey, boolean relhasrules, boolean relhastriggers,
			boolean relhassubclass, boolean relrowsecurity, boolean relforcerowsecurity, boolean relispopulated,
			Serializable relreplident, Serializable relfrozenxid, Serializable relminmxid) {
		this.relname = relname;
		this.relnamespace = relnamespace;
		this.reltype = reltype;
		this.reloftype = reloftype;
		this.relowner = relowner;
		this.relam = relam;
		this.relfilenode = relfilenode;
		this.reltablespace = reltablespace;
		this.relpages = relpages;
		this.reltuples = reltuples;
		this.relallvisible = relallvisible;
		this.reltoastrelid = reltoastrelid;
		this.relhasindex = relhasindex;
		this.relisshared = relisshared;
		this.relpersistence = relpersistence;
		this.relkind = relkind;
		this.relnatts = relnatts;
		this.relchecks = relchecks;
		this.relhasoids = relhasoids;
		this.relhaspkey = relhaspkey;
		this.relhasrules = relhasrules;
		this.relhastriggers = relhastriggers;
		this.relhassubclass = relhassubclass;
		this.relrowsecurity = relrowsecurity;
		this.relforcerowsecurity = relforcerowsecurity;
		this.relispopulated = relispopulated;
		this.relreplident = relreplident;
		this.relfrozenxid = relfrozenxid;
		this.relminmxid = relminmxid;
	}

	public PgClassId(String relname, int relnamespace, int reltype, int reloftype, int relowner, int relam,
			int relfilenode, int reltablespace, int relpages, float reltuples, int relallvisible, int reltoastrelid,
			boolean relhasindex, boolean relisshared, Serializable relpersistence, Serializable relkind, short relnatts,
			short relchecks, boolean relhasoids, boolean relhaspkey, boolean relhasrules, boolean relhastriggers,
			boolean relhassubclass, boolean relrowsecurity, boolean relforcerowsecurity, boolean relispopulated,
			Serializable relreplident, Serializable relfrozenxid, Serializable relminmxid, Serializable relacl,
			Serializable reloptions) {
		this.relname = relname;
		this.relnamespace = relnamespace;
		this.reltype = reltype;
		this.reloftype = reloftype;
		this.relowner = relowner;
		this.relam = relam;
		this.relfilenode = relfilenode;
		this.reltablespace = reltablespace;
		this.relpages = relpages;
		this.reltuples = reltuples;
		this.relallvisible = relallvisible;
		this.reltoastrelid = reltoastrelid;
		this.relhasindex = relhasindex;
		this.relisshared = relisshared;
		this.relpersistence = relpersistence;
		this.relkind = relkind;
		this.relnatts = relnatts;
		this.relchecks = relchecks;
		this.relhasoids = relhasoids;
		this.relhaspkey = relhaspkey;
		this.relhasrules = relhasrules;
		this.relhastriggers = relhastriggers;
		this.relhassubclass = relhassubclass;
		this.relrowsecurity = relrowsecurity;
		this.relforcerowsecurity = relforcerowsecurity;
		this.relispopulated = relispopulated;
		this.relreplident = relreplident;
		this.relfrozenxid = relfrozenxid;
		this.relminmxid = relminmxid;
		this.relacl = relacl;
		this.reloptions = reloptions;
	}

	@Column(name = "relname", nullable = false, length = 64)
	public String getRelname() {
		return this.relname;
	}

	public void setRelname(String relname) {
		this.relname = relname;
	}

	@Column(name = "relnamespace", nullable = false)
	public int getRelnamespace() {
		return this.relnamespace;
	}

	public void setRelnamespace(int relnamespace) {
		this.relnamespace = relnamespace;
	}

	@Column(name = "reltype", nullable = false)
	public int getReltype() {
		return this.reltype;
	}

	public void setReltype(int reltype) {
		this.reltype = reltype;
	}

	@Column(name = "reloftype", nullable = false)
	public int getReloftype() {
		return this.reloftype;
	}

	public void setReloftype(int reloftype) {
		this.reloftype = reloftype;
	}

	@Column(name = "relowner", nullable = false)
	public int getRelowner() {
		return this.relowner;
	}

	public void setRelowner(int relowner) {
		this.relowner = relowner;
	}

	@Column(name = "relam", nullable = false)
	public int getRelam() {
		return this.relam;
	}

	public void setRelam(int relam) {
		this.relam = relam;
	}

	@Column(name = "relfilenode", nullable = false)
	public int getRelfilenode() {
		return this.relfilenode;
	}

	public void setRelfilenode(int relfilenode) {
		this.relfilenode = relfilenode;
	}

	@Column(name = "reltablespace", nullable = false)
	public int getReltablespace() {
		return this.reltablespace;
	}

	public void setReltablespace(int reltablespace) {
		this.reltablespace = reltablespace;
	}

	@Column(name = "relpages", nullable = false)
	public int getRelpages() {
		return this.relpages;
	}

	public void setRelpages(int relpages) {
		this.relpages = relpages;
	}

	@Column(name = "reltuples", nullable = false, precision = 4, scale = 0)
	public float getReltuples() {
		return this.reltuples;
	}

	public void setReltuples(float reltuples) {
		this.reltuples = reltuples;
	}

	@Column(name = "relallvisible", nullable = false)
	public int getRelallvisible() {
		return this.relallvisible;
	}

	public void setRelallvisible(int relallvisible) {
		this.relallvisible = relallvisible;
	}

	@Column(name = "reltoastrelid", nullable = false)
	public int getReltoastrelid() {
		return this.reltoastrelid;
	}

	public void setReltoastrelid(int reltoastrelid) {
		this.reltoastrelid = reltoastrelid;
	}

	@Column(name = "relhasindex", nullable = false)
	public boolean isRelhasindex() {
		return this.relhasindex;
	}

	public void setRelhasindex(boolean relhasindex) {
		this.relhasindex = relhasindex;
	}

	@Column(name = "relisshared", nullable = false)
	public boolean isRelisshared() {
		return this.relisshared;
	}

	public void setRelisshared(boolean relisshared) {
		this.relisshared = relisshared;
	}

	@Column(name = "relpersistence", nullable = false)
	public Serializable getRelpersistence() {
		return this.relpersistence;
	}

	public void setRelpersistence(Serializable relpersistence) {
		this.relpersistence = relpersistence;
	}

	@Column(name = "relkind", nullable = false)
	public Serializable getRelkind() {
		return this.relkind;
	}

	public void setRelkind(Serializable relkind) {
		this.relkind = relkind;
	}

	@Column(name = "relnatts", nullable = false)
	public short getRelnatts() {
		return this.relnatts;
	}

	public void setRelnatts(short relnatts) {
		this.relnatts = relnatts;
	}

	@Column(name = "relchecks", nullable = false)
	public short getRelchecks() {
		return this.relchecks;
	}

	public void setRelchecks(short relchecks) {
		this.relchecks = relchecks;
	}

	@Column(name = "relhasoids", nullable = false)
	public boolean isRelhasoids() {
		return this.relhasoids;
	}

	public void setRelhasoids(boolean relhasoids) {
		this.relhasoids = relhasoids;
	}

	@Column(name = "relhaspkey", nullable = false)
	public boolean isRelhaspkey() {
		return this.relhaspkey;
	}

	public void setRelhaspkey(boolean relhaspkey) {
		this.relhaspkey = relhaspkey;
	}

	@Column(name = "relhasrules", nullable = false)
	public boolean isRelhasrules() {
		return this.relhasrules;
	}

	public void setRelhasrules(boolean relhasrules) {
		this.relhasrules = relhasrules;
	}

	@Column(name = "relhastriggers", nullable = false)
	public boolean isRelhastriggers() {
		return this.relhastriggers;
	}

	public void setRelhastriggers(boolean relhastriggers) {
		this.relhastriggers = relhastriggers;
	}

	@Column(name = "relhassubclass", nullable = false)
	public boolean isRelhassubclass() {
		return this.relhassubclass;
	}

	public void setRelhassubclass(boolean relhassubclass) {
		this.relhassubclass = relhassubclass;
	}

	@Column(name = "relrowsecurity", nullable = false)
	public boolean isRelrowsecurity() {
		return this.relrowsecurity;
	}

	public void setRelrowsecurity(boolean relrowsecurity) {
		this.relrowsecurity = relrowsecurity;
	}

	@Column(name = "relforcerowsecurity", nullable = false)
	public boolean isRelforcerowsecurity() {
		return this.relforcerowsecurity;
	}

	public void setRelforcerowsecurity(boolean relforcerowsecurity) {
		this.relforcerowsecurity = relforcerowsecurity;
	}

	@Column(name = "relispopulated", nullable = false)
	public boolean isRelispopulated() {
		return this.relispopulated;
	}

	public void setRelispopulated(boolean relispopulated) {
		this.relispopulated = relispopulated;
	}

	@Column(name = "relreplident", nullable = false)
	public Serializable getRelreplident() {
		return this.relreplident;
	}

	public void setRelreplident(Serializable relreplident) {
		this.relreplident = relreplident;
	}

	@Column(name = "relfrozenxid", nullable = false)
	public Serializable getRelfrozenxid() {
		return this.relfrozenxid;
	}

	public void setRelfrozenxid(Serializable relfrozenxid) {
		this.relfrozenxid = relfrozenxid;
	}

	@Column(name = "relminmxid", nullable = false)
	public Serializable getRelminmxid() {
		return this.relminmxid;
	}

	public void setRelminmxid(Serializable relminmxid) {
		this.relminmxid = relminmxid;
	}

	@Column(name = "relacl")
	public Serializable getRelacl() {
		return this.relacl;
	}

	public void setRelacl(Serializable relacl) {
		this.relacl = relacl;
	}

	@Column(name = "reloptions")
	public Serializable getReloptions() {
		return this.reloptions;
	}

	public void setReloptions(Serializable reloptions) {
		this.reloptions = reloptions;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgClassId))
			return false;
		PgClassId castOther = (PgClassId) other;

		return ((this.getRelname() == castOther.getRelname()) || (this.getRelname() != null
				&& castOther.getRelname() != null && this.getRelname().equals(castOther.getRelname())))
				&& (this.getRelnamespace() == castOther.getRelnamespace())
				&& (this.getReltype() == castOther.getReltype()) && (this.getReloftype() == castOther.getReloftype())
				&& (this.getRelowner() == castOther.getRelowner()) && (this.getRelam() == castOther.getRelam())
				&& (this.getRelfilenode() == castOther.getRelfilenode())
				&& (this.getReltablespace() == castOther.getReltablespace())
				&& (this.getRelpages() == castOther.getRelpages()) && (this.getReltuples() == castOther.getReltuples())
				&& (this.getRelallvisible() == castOther.getRelallvisible())
				&& (this.getReltoastrelid() == castOther.getReltoastrelid())
				&& (this.isRelhasindex() == castOther.isRelhasindex())
				&& (this.isRelisshared() == castOther.isRelisshared())
				&& ((this.getRelpersistence() == castOther.getRelpersistence())
						|| (this.getRelpersistence() != null && castOther.getRelpersistence() != null
								&& this.getRelpersistence().equals(castOther.getRelpersistence())))
				&& ((this.getRelkind() == castOther.getRelkind()) || (this.getRelkind() != null
						&& castOther.getRelkind() != null && this.getRelkind().equals(castOther.getRelkind())))
				&& (this.getRelnatts() == castOther.getRelnatts()) && (this.getRelchecks() == castOther.getRelchecks())
				&& (this.isRelhasoids() == castOther.isRelhasoids())
				&& (this.isRelhaspkey() == castOther.isRelhaspkey())
				&& (this.isRelhasrules() == castOther.isRelhasrules())
				&& (this.isRelhastriggers() == castOther.isRelhastriggers())
				&& (this.isRelhassubclass() == castOther.isRelhassubclass())
				&& (this.isRelrowsecurity() == castOther.isRelrowsecurity())
				&& (this.isRelforcerowsecurity() == castOther.isRelforcerowsecurity())
				&& (this.isRelispopulated() == castOther.isRelispopulated())
				&& ((this.getRelreplident() == castOther.getRelreplident())
						|| (this.getRelreplident() != null && castOther.getRelreplident() != null
								&& this.getRelreplident().equals(castOther.getRelreplident())))
				&& ((this.getRelfrozenxid() == castOther.getRelfrozenxid())
						|| (this.getRelfrozenxid() != null && castOther.getRelfrozenxid() != null
								&& this.getRelfrozenxid().equals(castOther.getRelfrozenxid())))
				&& ((this.getRelminmxid() == castOther.getRelminmxid()) || (this.getRelminmxid() != null
						&& castOther.getRelminmxid() != null && this.getRelminmxid().equals(castOther.getRelminmxid())))
				&& ((this.getRelacl() == castOther.getRelacl()) || (this.getRelacl() != null
						&& castOther.getRelacl() != null && this.getRelacl().equals(castOther.getRelacl())))
				&& ((this.getReloptions() == castOther.getReloptions())
						|| (this.getReloptions() != null && castOther.getReloptions() != null
								&& this.getReloptions().equals(castOther.getReloptions())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRelname() == null ? 0 : this.getRelname().hashCode());
		result = 37 * result + this.getRelnamespace();
		result = 37 * result + this.getReltype();
		result = 37 * result + this.getReloftype();
		result = 37 * result + this.getRelowner();
		result = 37 * result + this.getRelam();
		result = 37 * result + this.getRelfilenode();
		result = 37 * result + this.getReltablespace();
		result = 37 * result + this.getRelpages();
		result = 37 * result + (int) this.getReltuples();
		result = 37 * result + this.getRelallvisible();
		result = 37 * result + this.getReltoastrelid();
		result = 37 * result + (this.isRelhasindex() ? 1 : 0);
		result = 37 * result + (this.isRelisshared() ? 1 : 0);
		result = 37 * result + (getRelpersistence() == null ? 0 : this.getRelpersistence().hashCode());
		result = 37 * result + (getRelkind() == null ? 0 : this.getRelkind().hashCode());
		result = 37 * result + this.getRelnatts();
		result = 37 * result + this.getRelchecks();
		result = 37 * result + (this.isRelhasoids() ? 1 : 0);
		result = 37 * result + (this.isRelhaspkey() ? 1 : 0);
		result = 37 * result + (this.isRelhasrules() ? 1 : 0);
		result = 37 * result + (this.isRelhastriggers() ? 1 : 0);
		result = 37 * result + (this.isRelhassubclass() ? 1 : 0);
		result = 37 * result + (this.isRelrowsecurity() ? 1 : 0);
		result = 37 * result + (this.isRelforcerowsecurity() ? 1 : 0);
		result = 37 * result + (this.isRelispopulated() ? 1 : 0);
		result = 37 * result + (getRelreplident() == null ? 0 : this.getRelreplident().hashCode());
		result = 37 * result + (getRelfrozenxid() == null ? 0 : this.getRelfrozenxid().hashCode());
		result = 37 * result + (getRelminmxid() == null ? 0 : this.getRelminmxid().hashCode());
		result = 37 * result + (getRelacl() == null ? 0 : this.getRelacl().hashCode());
		result = 37 * result + (getReloptions() == null ? 0 : this.getReloptions().hashCode());
		return result;
	}

}
