package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgCollationId generated by hbm2java
 */
@Embeddable
public class PgCollationId implements java.io.Serializable {

	private String collname;
	private int collnamespace;
	private int collowner;
	private int collencoding;
	private String collcollate;
	private String collctype;

	public PgCollationId() {
	}

	public PgCollationId(String collname, int collnamespace, int collowner, int collencoding, String collcollate,
			String collctype) {
		this.collname = collname;
		this.collnamespace = collnamespace;
		this.collowner = collowner;
		this.collencoding = collencoding;
		this.collcollate = collcollate;
		this.collctype = collctype;
	}

	@Column(name = "collname", nullable = false, length = 64)
	public String getCollname() {
		return this.collname;
	}

	public void setCollname(String collname) {
		this.collname = collname;
	}

	@Column(name = "collnamespace", nullable = false)
	public int getCollnamespace() {
		return this.collnamespace;
	}

	public void setCollnamespace(int collnamespace) {
		this.collnamespace = collnamespace;
	}

	@Column(name = "collowner", nullable = false)
	public int getCollowner() {
		return this.collowner;
	}

	public void setCollowner(int collowner) {
		this.collowner = collowner;
	}

	@Column(name = "collencoding", nullable = false)
	public int getCollencoding() {
		return this.collencoding;
	}

	public void setCollencoding(int collencoding) {
		this.collencoding = collencoding;
	}

	@Column(name = "collcollate", nullable = false, length = 64)
	public String getCollcollate() {
		return this.collcollate;
	}

	public void setCollcollate(String collcollate) {
		this.collcollate = collcollate;
	}

	@Column(name = "collctype", nullable = false, length = 64)
	public String getCollctype() {
		return this.collctype;
	}

	public void setCollctype(String collctype) {
		this.collctype = collctype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgCollationId))
			return false;
		PgCollationId castOther = (PgCollationId) other;

		return ((this.getCollname() == castOther.getCollname()) || (this.getCollname() != null
				&& castOther.getCollname() != null && this.getCollname().equals(castOther.getCollname())))
				&& (this.getCollnamespace() == castOther.getCollnamespace())
				&& (this.getCollowner() == castOther.getCollowner())
				&& (this.getCollencoding() == castOther.getCollencoding())
				&& ((this.getCollcollate() == castOther.getCollcollate())
						|| (this.getCollcollate() != null && castOther.getCollcollate() != null
								&& this.getCollcollate().equals(castOther.getCollcollate())))
				&& ((this.getCollctype() == castOther.getCollctype()) || (this.getCollctype() != null
						&& castOther.getCollctype() != null && this.getCollctype().equals(castOther.getCollctype())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCollname() == null ? 0 : this.getCollname().hashCode());
		result = 37 * result + this.getCollnamespace();
		result = 37 * result + this.getCollowner();
		result = 37 * result + this.getCollencoding();
		result = 37 * result + (getCollcollate() == null ? 0 : this.getCollcollate().hashCode());
		result = 37 * result + (getCollctype() == null ? 0 : this.getCollctype().hashCode());
		return result;
	}

}
