package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgCollation generated by hbm2java
 */
@Entity
@Table(name = "pg_collation", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "collname", "collencoding", "collnamespace" }),
		@UniqueConstraint(columnNames = "oid") })
public class PgCollation implements java.io.Serializable {

	private PgCollationId id;

	public PgCollation() {
	}

	public PgCollation(PgCollationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "collname", column = @Column(name = "collname", nullable = false, length = 64)),
			@AttributeOverride(name = "collnamespace", column = @Column(name = "collnamespace", nullable = false)),
			@AttributeOverride(name = "collowner", column = @Column(name = "collowner", nullable = false)),
			@AttributeOverride(name = "collencoding", column = @Column(name = "collencoding", nullable = false)),
			@AttributeOverride(name = "collcollate", column = @Column(name = "collcollate", nullable = false, length = 64)),
			@AttributeOverride(name = "collctype", column = @Column(name = "collctype", nullable = false, length = 64)) })
	public PgCollationId getId() {
		return this.id;
	}

	public void setId(PgCollationId id) {
		this.id = id;
	}

}
