package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgConversion generated by hbm2java
 */
@Entity
@Table(name = "pg_conversion", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "connamespace", "conforencoding", "contoencoding", "oid" }),
		@UniqueConstraint(columnNames = { "conname", "connamespace" }), @UniqueConstraint(columnNames = "oid") })
public class PgConversion implements java.io.Serializable {

	private PgConversionId id;

	public PgConversion() {
	}

	public PgConversion(PgConversionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "conname", column = @Column(name = "conname", nullable = false, length = 64)),
			@AttributeOverride(name = "connamespace", column = @Column(name = "connamespace", nullable = false)),
			@AttributeOverride(name = "conowner", column = @Column(name = "conowner", nullable = false)),
			@AttributeOverride(name = "conforencoding", column = @Column(name = "conforencoding", nullable = false)),
			@AttributeOverride(name = "contoencoding", column = @Column(name = "contoencoding", nullable = false)),
			@AttributeOverride(name = "conproc", column = @Column(name = "conproc", nullable = false)),
			@AttributeOverride(name = "condefault", column = @Column(name = "condefault", nullable = false)) })
	public PgConversionId getId() {
		return this.id;
	}

	public void setId(PgConversionId id) {
		this.id = id;
	}

}
