package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgConstraint generated by hbm2java
 */
@Entity
@Table(name = "pg_constraint", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = "oid"))
public class PgConstraint implements java.io.Serializable {

	private PgConstraintId id;

	public PgConstraint() {
	}

	public PgConstraint(PgConstraintId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "conname", column = @Column(name = "conname", nullable = false, length = 64)),
			@AttributeOverride(name = "connamespace", column = @Column(name = "connamespace", nullable = false)),
			@AttributeOverride(name = "contype", column = @Column(name = "contype", nullable = false)),
			@AttributeOverride(name = "condeferrable", column = @Column(name = "condeferrable", nullable = false)),
			@AttributeOverride(name = "condeferred", column = @Column(name = "condeferred", nullable = false)),
			@AttributeOverride(name = "convalidated", column = @Column(name = "convalidated", nullable = false)),
			@AttributeOverride(name = "conrelid", column = @Column(name = "conrelid", nullable = false)),
			@AttributeOverride(name = "contypid", column = @Column(name = "contypid", nullable = false)),
			@AttributeOverride(name = "conindid", column = @Column(name = "conindid", nullable = false)),
			@AttributeOverride(name = "confrelid", column = @Column(name = "confrelid", nullable = false)),
			@AttributeOverride(name = "confupdtype", column = @Column(name = "confupdtype", nullable = false)),
			@AttributeOverride(name = "confdeltype", column = @Column(name = "confdeltype", nullable = false)),
			@AttributeOverride(name = "confmatchtype", column = @Column(name = "confmatchtype", nullable = false)),
			@AttributeOverride(name = "conislocal", column = @Column(name = "conislocal", nullable = false)),
			@AttributeOverride(name = "coninhcount", column = @Column(name = "coninhcount", nullable = false)),
			@AttributeOverride(name = "connoinherit", column = @Column(name = "connoinherit", nullable = false)),
			@AttributeOverride(name = "conkey", column = @Column(name = "conkey")),
			@AttributeOverride(name = "confkey", column = @Column(name = "confkey")),
			@AttributeOverride(name = "conpfeqop", column = @Column(name = "conpfeqop")),
			@AttributeOverride(name = "conppeqop", column = @Column(name = "conppeqop")),
			@AttributeOverride(name = "conffeqop", column = @Column(name = "conffeqop")),
			@AttributeOverride(name = "conexclop", column = @Column(name = "conexclop")),
			@AttributeOverride(name = "conbin", column = @Column(name = "conbin")),
			@AttributeOverride(name = "consrc", column = @Column(name = "consrc")) })
	public PgConstraintId getId() {
		return this.id;
	}

	public void setId(PgConstraintId id) {
		this.id = id;
	}

}
