package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgConversionId generated by hbm2java
 */
@Embeddable
public class PgConversionId implements java.io.Serializable {

	private String conname;
	private int connamespace;
	private int conowner;
	private int conforencoding;
	private int contoencoding;
	private Serializable conproc;
	private boolean condefault;

	public PgConversionId() {
	}

	public PgConversionId(String conname, int connamespace, int conowner, int conforencoding, int contoencoding,
			Serializable conproc, boolean condefault) {
		this.conname = conname;
		this.connamespace = connamespace;
		this.conowner = conowner;
		this.conforencoding = conforencoding;
		this.contoencoding = contoencoding;
		this.conproc = conproc;
		this.condefault = condefault;
	}

	@Column(name = "conname", nullable = false, length = 64)
	public String getConname() {
		return this.conname;
	}

	public void setConname(String conname) {
		this.conname = conname;
	}

	@Column(name = "connamespace", nullable = false)
	public int getConnamespace() {
		return this.connamespace;
	}

	public void setConnamespace(int connamespace) {
		this.connamespace = connamespace;
	}

	@Column(name = "conowner", nullable = false)
	public int getConowner() {
		return this.conowner;
	}

	public void setConowner(int conowner) {
		this.conowner = conowner;
	}

	@Column(name = "conforencoding", nullable = false)
	public int getConforencoding() {
		return this.conforencoding;
	}

	public void setConforencoding(int conforencoding) {
		this.conforencoding = conforencoding;
	}

	@Column(name = "contoencoding", nullable = false)
	public int getContoencoding() {
		return this.contoencoding;
	}

	public void setContoencoding(int contoencoding) {
		this.contoencoding = contoencoding;
	}

	@Column(name = "conproc", nullable = false)
	public Serializable getConproc() {
		return this.conproc;
	}

	public void setConproc(Serializable conproc) {
		this.conproc = conproc;
	}

	@Column(name = "condefault", nullable = false)
	public boolean isCondefault() {
		return this.condefault;
	}

	public void setCondefault(boolean condefault) {
		this.condefault = condefault;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgConversionId))
			return false;
		PgConversionId castOther = (PgConversionId) other;

		return ((this.getConname() == castOther.getConname()) || (this.getConname() != null
				&& castOther.getConname() != null && this.getConname().equals(castOther.getConname())))
				&& (this.getConnamespace() == castOther.getConnamespace())
				&& (this.getConowner() == castOther.getConowner())
				&& (this.getConforencoding() == castOther.getConforencoding())
				&& (this.getContoencoding() == castOther.getContoencoding())
				&& ((this.getConproc() == castOther.getConproc()) || (this.getConproc() != null
						&& castOther.getConproc() != null && this.getConproc().equals(castOther.getConproc())))
				&& (this.isCondefault() == castOther.isCondefault());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getConname() == null ? 0 : this.getConname().hashCode());
		result = 37 * result + this.getConnamespace();
		result = 37 * result + this.getConowner();
		result = 37 * result + this.getConforencoding();
		result = 37 * result + this.getContoencoding();
		result = 37 * result + (getConproc() == null ? 0 : this.getConproc().hashCode());
		result = 37 * result + (this.isCondefault() ? 1 : 0);
		return result;
	}

}
