package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgConstraintId generated by hbm2java
 */
@Embeddable
public class PgConstraintId implements java.io.Serializable {

	private String conname;
	private int connamespace;
	private Serializable contype;
	private boolean condeferrable;
	private boolean condeferred;
	private boolean convalidated;
	private int conrelid;
	private int contypid;
	private int conindid;
	private int confrelid;
	private Serializable confupdtype;
	private Serializable confdeltype;
	private Serializable confmatchtype;
	private boolean conislocal;
	private int coninhcount;
	private boolean connoinherit;
	private Serializable conkey;
	private Serializable confkey;
	private Serializable conpfeqop;
	private Serializable conppeqop;
	private Serializable conffeqop;
	private Serializable conexclop;
	private Serializable conbin;
	private String consrc;

	public PgConstraintId() {
	}

	public PgConstraintId(String conname, int connamespace, Serializable contype, boolean condeferrable,
			boolean condeferred, boolean convalidated, int conrelid, int contypid, int conindid, int confrelid,
			Serializable confupdtype, Serializable confdeltype, Serializable confmatchtype, boolean conislocal,
			int coninhcount, boolean connoinherit) {
		this.conname = conname;
		this.connamespace = connamespace;
		this.contype = contype;
		this.condeferrable = condeferrable;
		this.condeferred = condeferred;
		this.convalidated = convalidated;
		this.conrelid = conrelid;
		this.contypid = contypid;
		this.conindid = conindid;
		this.confrelid = confrelid;
		this.confupdtype = confupdtype;
		this.confdeltype = confdeltype;
		this.confmatchtype = confmatchtype;
		this.conislocal = conislocal;
		this.coninhcount = coninhcount;
		this.connoinherit = connoinherit;
	}

	public PgConstraintId(String conname, int connamespace, Serializable contype, boolean condeferrable,
			boolean condeferred, boolean convalidated, int conrelid, int contypid, int conindid, int confrelid,
			Serializable confupdtype, Serializable confdeltype, Serializable confmatchtype, boolean conislocal,
			int coninhcount, boolean connoinherit, Serializable conkey, Serializable confkey, Serializable conpfeqop,
			Serializable conppeqop, Serializable conffeqop, Serializable conexclop, Serializable conbin,
			String consrc) {
		this.conname = conname;
		this.connamespace = connamespace;
		this.contype = contype;
		this.condeferrable = condeferrable;
		this.condeferred = condeferred;
		this.convalidated = convalidated;
		this.conrelid = conrelid;
		this.contypid = contypid;
		this.conindid = conindid;
		this.confrelid = confrelid;
		this.confupdtype = confupdtype;
		this.confdeltype = confdeltype;
		this.confmatchtype = confmatchtype;
		this.conislocal = conislocal;
		this.coninhcount = coninhcount;
		this.connoinherit = connoinherit;
		this.conkey = conkey;
		this.confkey = confkey;
		this.conpfeqop = conpfeqop;
		this.conppeqop = conppeqop;
		this.conffeqop = conffeqop;
		this.conexclop = conexclop;
		this.conbin = conbin;
		this.consrc = consrc;
	}

	@Column(name = "conname", nullable = false, length = 64)
	public String getConname() {
		return this.conname;
	}

	public void setConname(String conname) {
		this.conname = conname;
	}

	@Column(name = "connamespace", nullable = false)
	public int getConnamespace() {
		return this.connamespace;
	}

	public void setConnamespace(int connamespace) {
		this.connamespace = connamespace;
	}

	@Column(name = "contype", nullable = false)
	public Serializable getContype() {
		return this.contype;
	}

	public void setContype(Serializable contype) {
		this.contype = contype;
	}

	@Column(name = "condeferrable", nullable = false)
	public boolean isCondeferrable() {
		return this.condeferrable;
	}

	public void setCondeferrable(boolean condeferrable) {
		this.condeferrable = condeferrable;
	}

	@Column(name = "condeferred", nullable = false)
	public boolean isCondeferred() {
		return this.condeferred;
	}

	public void setCondeferred(boolean condeferred) {
		this.condeferred = condeferred;
	}

	@Column(name = "convalidated", nullable = false)
	public boolean isConvalidated() {
		return this.convalidated;
	}

	public void setConvalidated(boolean convalidated) {
		this.convalidated = convalidated;
	}

	@Column(name = "conrelid", nullable = false)
	public int getConrelid() {
		return this.conrelid;
	}

	public void setConrelid(int conrelid) {
		this.conrelid = conrelid;
	}

	@Column(name = "contypid", nullable = false)
	public int getContypid() {
		return this.contypid;
	}

	public void setContypid(int contypid) {
		this.contypid = contypid;
	}

	@Column(name = "conindid", nullable = false)
	public int getConindid() {
		return this.conindid;
	}

	public void setConindid(int conindid) {
		this.conindid = conindid;
	}

	@Column(name = "confrelid", nullable = false)
	public int getConfrelid() {
		return this.confrelid;
	}

	public void setConfrelid(int confrelid) {
		this.confrelid = confrelid;
	}

	@Column(name = "confupdtype", nullable = false)
	public Serializable getConfupdtype() {
		return this.confupdtype;
	}

	public void setConfupdtype(Serializable confupdtype) {
		this.confupdtype = confupdtype;
	}

	@Column(name = "confdeltype", nullable = false)
	public Serializable getConfdeltype() {
		return this.confdeltype;
	}

	public void setConfdeltype(Serializable confdeltype) {
		this.confdeltype = confdeltype;
	}

	@Column(name = "confmatchtype", nullable = false)
	public Serializable getConfmatchtype() {
		return this.confmatchtype;
	}

	public void setConfmatchtype(Serializable confmatchtype) {
		this.confmatchtype = confmatchtype;
	}

	@Column(name = "conislocal", nullable = false)
	public boolean isConislocal() {
		return this.conislocal;
	}

	public void setConislocal(boolean conislocal) {
		this.conislocal = conislocal;
	}

	@Column(name = "coninhcount", nullable = false)
	public int getConinhcount() {
		return this.coninhcount;
	}

	public void setConinhcount(int coninhcount) {
		this.coninhcount = coninhcount;
	}

	@Column(name = "connoinherit", nullable = false)
	public boolean isConnoinherit() {
		return this.connoinherit;
	}

	public void setConnoinherit(boolean connoinherit) {
		this.connoinherit = connoinherit;
	}

	@Column(name = "conkey")
	public Serializable getConkey() {
		return this.conkey;
	}

	public void setConkey(Serializable conkey) {
		this.conkey = conkey;
	}

	@Column(name = "confkey")
	public Serializable getConfkey() {
		return this.confkey;
	}

	public void setConfkey(Serializable confkey) {
		this.confkey = confkey;
	}

	@Column(name = "conpfeqop")
	public Serializable getConpfeqop() {
		return this.conpfeqop;
	}

	public void setConpfeqop(Serializable conpfeqop) {
		this.conpfeqop = conpfeqop;
	}

	@Column(name = "conppeqop")
	public Serializable getConppeqop() {
		return this.conppeqop;
	}

	public void setConppeqop(Serializable conppeqop) {
		this.conppeqop = conppeqop;
	}

	@Column(name = "conffeqop")
	public Serializable getConffeqop() {
		return this.conffeqop;
	}

	public void setConffeqop(Serializable conffeqop) {
		this.conffeqop = conffeqop;
	}

	@Column(name = "conexclop")
	public Serializable getConexclop() {
		return this.conexclop;
	}

	public void setConexclop(Serializable conexclop) {
		this.conexclop = conexclop;
	}

	@Column(name = "conbin")
	public Serializable getConbin() {
		return this.conbin;
	}

	public void setConbin(Serializable conbin) {
		this.conbin = conbin;
	}

	@Column(name = "consrc")
	public String getConsrc() {
		return this.consrc;
	}

	public void setConsrc(String consrc) {
		this.consrc = consrc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgConstraintId))
			return false;
		PgConstraintId castOther = (PgConstraintId) other;

		return ((this.getConname() == castOther.getConname()) || (this.getConname() != null
				&& castOther.getConname() != null && this.getConname().equals(castOther.getConname())))
				&& (this.getConnamespace() == castOther.getConnamespace())
				&& ((this.getContype() == castOther.getContype()) || (this.getContype() != null
						&& castOther.getContype() != null && this.getContype().equals(castOther.getContype())))
				&& (this.isCondeferrable() == castOther.isCondeferrable())
				&& (this.isCondeferred() == castOther.isCondeferred())
				&& (this.isConvalidated() == castOther.isConvalidated())
				&& (this.getConrelid() == castOther.getConrelid()) && (this.getContypid() == castOther.getContypid())
				&& (this.getConindid() == castOther.getConindid()) && (this.getConfrelid() == castOther.getConfrelid())
				&& ((this.getConfupdtype() == castOther.getConfupdtype())
						|| (this.getConfupdtype() != null && castOther.getConfupdtype() != null
								&& this.getConfupdtype().equals(castOther.getConfupdtype())))
				&& ((this.getConfdeltype() == castOther.getConfdeltype())
						|| (this.getConfdeltype() != null && castOther.getConfdeltype() != null
								&& this.getConfdeltype().equals(castOther.getConfdeltype())))
				&& ((this.getConfmatchtype() == castOther.getConfmatchtype())
						|| (this.getConfmatchtype() != null && castOther.getConfmatchtype() != null
								&& this.getConfmatchtype().equals(castOther.getConfmatchtype())))
				&& (this.isConislocal() == castOther.isConislocal())
				&& (this.getConinhcount() == castOther.getConinhcount())
				&& (this.isConnoinherit() == castOther.isConnoinherit())
				&& ((this.getConkey() == castOther.getConkey()) || (this.getConkey() != null
						&& castOther.getConkey() != null && this.getConkey().equals(castOther.getConkey())))
				&& ((this.getConfkey() == castOther.getConfkey()) || (this.getConfkey() != null
						&& castOther.getConfkey() != null && this.getConfkey().equals(castOther.getConfkey())))
				&& ((this.getConpfeqop() == castOther.getConpfeqop()) || (this.getConpfeqop() != null
						&& castOther.getConpfeqop() != null && this.getConpfeqop().equals(castOther.getConpfeqop())))
				&& ((this.getConppeqop() == castOther.getConppeqop()) || (this.getConppeqop() != null
						&& castOther.getConppeqop() != null && this.getConppeqop().equals(castOther.getConppeqop())))
				&& ((this.getConffeqop() == castOther.getConffeqop()) || (this.getConffeqop() != null
						&& castOther.getConffeqop() != null && this.getConffeqop().equals(castOther.getConffeqop())))
				&& ((this.getConexclop() == castOther.getConexclop()) || (this.getConexclop() != null
						&& castOther.getConexclop() != null && this.getConexclop().equals(castOther.getConexclop())))
				&& ((this.getConbin() == castOther.getConbin()) || (this.getConbin() != null
						&& castOther.getConbin() != null && this.getConbin().equals(castOther.getConbin())))
				&& ((this.getConsrc() == castOther.getConsrc()) || (this.getConsrc() != null
						&& castOther.getConsrc() != null && this.getConsrc().equals(castOther.getConsrc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getConname() == null ? 0 : this.getConname().hashCode());
		result = 37 * result + this.getConnamespace();
		result = 37 * result + (getContype() == null ? 0 : this.getContype().hashCode());
		result = 37 * result + (this.isCondeferrable() ? 1 : 0);
		result = 37 * result + (this.isCondeferred() ? 1 : 0);
		result = 37 * result + (this.isConvalidated() ? 1 : 0);
		result = 37 * result + this.getConrelid();
		result = 37 * result + this.getContypid();
		result = 37 * result + this.getConindid();
		result = 37 * result + this.getConfrelid();
		result = 37 * result + (getConfupdtype() == null ? 0 : this.getConfupdtype().hashCode());
		result = 37 * result + (getConfdeltype() == null ? 0 : this.getConfdeltype().hashCode());
		result = 37 * result + (getConfmatchtype() == null ? 0 : this.getConfmatchtype().hashCode());
		result = 37 * result + (this.isConislocal() ? 1 : 0);
		result = 37 * result + this.getConinhcount();
		result = 37 * result + (this.isConnoinherit() ? 1 : 0);
		result = 37 * result + (getConkey() == null ? 0 : this.getConkey().hashCode());
		result = 37 * result + (getConfkey() == null ? 0 : this.getConfkey().hashCode());
		result = 37 * result + (getConpfeqop() == null ? 0 : this.getConpfeqop().hashCode());
		result = 37 * result + (getConppeqop() == null ? 0 : this.getConppeqop().hashCode());
		result = 37 * result + (getConffeqop() == null ? 0 : this.getConffeqop().hashCode());
		result = 37 * result + (getConexclop() == null ? 0 : this.getConexclop().hashCode());
		result = 37 * result + (getConbin() == null ? 0 : this.getConbin().hashCode());
		result = 37 * result + (getConsrc() == null ? 0 : this.getConsrc().hashCode());
		return result;
	}

}
