package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgDatabaseId generated by hbm2java
 */
@Embeddable
public class PgDatabaseId implements java.io.Serializable {

	private String datname;
	private int datdba;
	private int encoding;
	private String datcollate;
	private String datctype;
	private boolean datistemplate;
	private boolean datallowconn;
	private int datconnlimit;
	private int datlastsysoid;
	private Serializable datfrozenxid;
	private Serializable datminmxid;
	private int dattablespace;
	private Serializable datacl;

	public PgDatabaseId() {
	}

	public PgDatabaseId(String datname, int datdba, int encoding, String datcollate, String datctype,
			boolean datistemplate, boolean datallowconn, int datconnlimit, int datlastsysoid, Serializable datfrozenxid,
			Serializable datminmxid, int dattablespace) {
		this.datname = datname;
		this.datdba = datdba;
		this.encoding = encoding;
		this.datcollate = datcollate;
		this.datctype = datctype;
		this.datistemplate = datistemplate;
		this.datallowconn = datallowconn;
		this.datconnlimit = datconnlimit;
		this.datlastsysoid = datlastsysoid;
		this.datfrozenxid = datfrozenxid;
		this.datminmxid = datminmxid;
		this.dattablespace = dattablespace;
	}

	public PgDatabaseId(String datname, int datdba, int encoding, String datcollate, String datctype,
			boolean datistemplate, boolean datallowconn, int datconnlimit, int datlastsysoid, Serializable datfrozenxid,
			Serializable datminmxid, int dattablespace, Serializable datacl) {
		this.datname = datname;
		this.datdba = datdba;
		this.encoding = encoding;
		this.datcollate = datcollate;
		this.datctype = datctype;
		this.datistemplate = datistemplate;
		this.datallowconn = datallowconn;
		this.datconnlimit = datconnlimit;
		this.datlastsysoid = datlastsysoid;
		this.datfrozenxid = datfrozenxid;
		this.datminmxid = datminmxid;
		this.dattablespace = dattablespace;
		this.datacl = datacl;
	}

	@Column(name = "datname", unique = true, nullable = false, length = 64)
	public String getDatname() {
		return this.datname;
	}

	public void setDatname(String datname) {
		this.datname = datname;
	}

	@Column(name = "datdba", nullable = false)
	public int getDatdba() {
		return this.datdba;
	}

	public void setDatdba(int datdba) {
		this.datdba = datdba;
	}

	@Column(name = "encoding", nullable = false)
	public int getEncoding() {
		return this.encoding;
	}

	public void setEncoding(int encoding) {
		this.encoding = encoding;
	}

	@Column(name = "datcollate", nullable = false, length = 64)
	public String getDatcollate() {
		return this.datcollate;
	}

	public void setDatcollate(String datcollate) {
		this.datcollate = datcollate;
	}

	@Column(name = "datctype", nullable = false, length = 64)
	public String getDatctype() {
		return this.datctype;
	}

	public void setDatctype(String datctype) {
		this.datctype = datctype;
	}

	@Column(name = "datistemplate", nullable = false)
	public boolean isDatistemplate() {
		return this.datistemplate;
	}

	public void setDatistemplate(boolean datistemplate) {
		this.datistemplate = datistemplate;
	}

	@Column(name = "datallowconn", nullable = false)
	public boolean isDatallowconn() {
		return this.datallowconn;
	}

	public void setDatallowconn(boolean datallowconn) {
		this.datallowconn = datallowconn;
	}

	@Column(name = "datconnlimit", nullable = false)
	public int getDatconnlimit() {
		return this.datconnlimit;
	}

	public void setDatconnlimit(int datconnlimit) {
		this.datconnlimit = datconnlimit;
	}

	@Column(name = "datlastsysoid", nullable = false)
	public int getDatlastsysoid() {
		return this.datlastsysoid;
	}

	public void setDatlastsysoid(int datlastsysoid) {
		this.datlastsysoid = datlastsysoid;
	}

	@Column(name = "datfrozenxid", nullable = false)
	public Serializable getDatfrozenxid() {
		return this.datfrozenxid;
	}

	public void setDatfrozenxid(Serializable datfrozenxid) {
		this.datfrozenxid = datfrozenxid;
	}

	@Column(name = "datminmxid", nullable = false)
	public Serializable getDatminmxid() {
		return this.datminmxid;
	}

	public void setDatminmxid(Serializable datminmxid) {
		this.datminmxid = datminmxid;
	}

	@Column(name = "dattablespace", nullable = false)
	public int getDattablespace() {
		return this.dattablespace;
	}

	public void setDattablespace(int dattablespace) {
		this.dattablespace = dattablespace;
	}

	@Column(name = "datacl")
	public Serializable getDatacl() {
		return this.datacl;
	}

	public void setDatacl(Serializable datacl) {
		this.datacl = datacl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgDatabaseId))
			return false;
		PgDatabaseId castOther = (PgDatabaseId) other;

		return ((this.getDatname() == castOther.getDatname()) || (this.getDatname() != null
				&& castOther.getDatname() != null && this.getDatname().equals(castOther.getDatname())))
				&& (this.getDatdba() == castOther.getDatdba()) && (this.getEncoding() == castOther.getEncoding())
				&& ((this.getDatcollate() == castOther.getDatcollate()) || (this.getDatcollate() != null
						&& castOther.getDatcollate() != null && this.getDatcollate().equals(castOther.getDatcollate())))
				&& ((this.getDatctype() == castOther.getDatctype()) || (this.getDatctype() != null
						&& castOther.getDatctype() != null && this.getDatctype().equals(castOther.getDatctype())))
				&& (this.isDatistemplate() == castOther.isDatistemplate())
				&& (this.isDatallowconn() == castOther.isDatallowconn())
				&& (this.getDatconnlimit() == castOther.getDatconnlimit())
				&& (this.getDatlastsysoid() == castOther.getDatlastsysoid())
				&& ((this.getDatfrozenxid() == castOther.getDatfrozenxid())
						|| (this.getDatfrozenxid() != null && castOther.getDatfrozenxid() != null
								&& this.getDatfrozenxid().equals(castOther.getDatfrozenxid())))
				&& ((this.getDatminmxid() == castOther.getDatminmxid()) || (this.getDatminmxid() != null
						&& castOther.getDatminmxid() != null && this.getDatminmxid().equals(castOther.getDatminmxid())))
				&& (this.getDattablespace() == castOther.getDattablespace())
				&& ((this.getDatacl() == castOther.getDatacl()) || (this.getDatacl() != null
						&& castOther.getDatacl() != null && this.getDatacl().equals(castOther.getDatacl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDatname() == null ? 0 : this.getDatname().hashCode());
		result = 37 * result + this.getDatdba();
		result = 37 * result + this.getEncoding();
		result = 37 * result + (getDatcollate() == null ? 0 : this.getDatcollate().hashCode());
		result = 37 * result + (getDatctype() == null ? 0 : this.getDatctype().hashCode());
		result = 37 * result + (this.isDatistemplate() ? 1 : 0);
		result = 37 * result + (this.isDatallowconn() ? 1 : 0);
		result = 37 * result + this.getDatconnlimit();
		result = 37 * result + this.getDatlastsysoid();
		result = 37 * result + (getDatfrozenxid() == null ? 0 : this.getDatfrozenxid().hashCode());
		result = 37 * result + (getDatminmxid() == null ? 0 : this.getDatminmxid().hashCode());
		result = 37 * result + this.getDattablespace();
		result = 37 * result + (getDatacl() == null ? 0 : this.getDatacl().hashCode());
		return result;
	}

}
