package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgDbRoleSetting generated by hbm2java
 */
@Entity
@Table(name = "pg_db_role_setting", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = {
		"setdatabase", "setrole" }))
public class PgDbRoleSetting implements java.io.Serializable {

	private PgDbRoleSettingId id;

	public PgDbRoleSetting() {
	}

	public PgDbRoleSetting(PgDbRoleSettingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "setdatabase", column = @Column(name = "setdatabase", nullable = false)),
			@AttributeOverride(name = "setrole", column = @Column(name = "setrole", nullable = false)),
			@AttributeOverride(name = "setconfig", column = @Column(name = "setconfig")) })
	public PgDbRoleSettingId getId() {
		return this.id;
	}

	public void setId(PgDbRoleSettingId id) {
		this.id = id;
	}

}
