package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgDbRoleSettingId generated by hbm2java
 */
@Embeddable
public class PgDbRoleSettingId implements java.io.Serializable {

	private int setdatabase;
	private int setrole;
	private Serializable setconfig;

	public PgDbRoleSettingId() {
	}

	public PgDbRoleSettingId(int setdatabase, int setrole) {
		this.setdatabase = setdatabase;
		this.setrole = setrole;
	}

	public PgDbRoleSettingId(int setdatabase, int setrole, Serializable setconfig) {
		this.setdatabase = setdatabase;
		this.setrole = setrole;
		this.setconfig = setconfig;
	}

	@Column(name = "setdatabase", nullable = false)
	public int getSetdatabase() {
		return this.setdatabase;
	}

	public void setSetdatabase(int setdatabase) {
		this.setdatabase = setdatabase;
	}

	@Column(name = "setrole", nullable = false)
	public int getSetrole() {
		return this.setrole;
	}

	public void setSetrole(int setrole) {
		this.setrole = setrole;
	}

	@Column(name = "setconfig")
	public Serializable getSetconfig() {
		return this.setconfig;
	}

	public void setSetconfig(Serializable setconfig) {
		this.setconfig = setconfig;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgDbRoleSettingId))
			return false;
		PgDbRoleSettingId castOther = (PgDbRoleSettingId) other;

		return (this.getSetdatabase() == castOther.getSetdatabase()) && (this.getSetrole() == castOther.getSetrole())
				&& ((this.getSetconfig() == castOther.getSetconfig()) || (this.getSetconfig() != null
						&& castOther.getSetconfig() != null && this.getSetconfig().equals(castOther.getSetconfig())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSetdatabase();
		result = 37 * result + this.getSetrole();
		result = 37 * result + (getSetconfig() == null ? 0 : this.getSetconfig().hashCode());
		return result;
	}

}
