package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgDefaultAcl generated by hbm2java
 */
@Entity
@Table(name = "pg_default_acl", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "defaclrole", "defaclnamespace", "defaclobjtype" }) })
public class PgDefaultAcl implements java.io.Serializable {

	private PgDefaultAclId id;

	public PgDefaultAcl() {
	}

	public PgDefaultAcl(PgDefaultAclId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "defaclrole", column = @Column(name = "defaclrole", nullable = false)),
			@AttributeOverride(name = "defaclnamespace", column = @Column(name = "defaclnamespace", nullable = false)),
			@AttributeOverride(name = "defaclobjtype", column = @Column(name = "defaclobjtype", nullable = false)),
			@AttributeOverride(name = "defaclacl", column = @Column(name = "defaclacl")) })
	public PgDefaultAclId getId() {
		return this.id;
	}

	public void setId(PgDefaultAclId id) {
		this.id = id;
	}

}
