package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgDefaultAclId generated by hbm2java
 */
@Embeddable
public class PgDefaultAclId implements java.io.Serializable {

	private int defaclrole;
	private int defaclnamespace;
	private Serializable defaclobjtype;
	private Serializable defaclacl;

	public PgDefaultAclId() {
	}

	public PgDefaultAclId(int defaclrole, int defaclnamespace, Serializable defaclobjtype) {
		this.defaclrole = defaclrole;
		this.defaclnamespace = defaclnamespace;
		this.defaclobjtype = defaclobjtype;
	}

	public PgDefaultAclId(int defaclrole, int defaclnamespace, Serializable defaclobjtype, Serializable defaclacl) {
		this.defaclrole = defaclrole;
		this.defaclnamespace = defaclnamespace;
		this.defaclobjtype = defaclobjtype;
		this.defaclacl = defaclacl;
	}

	@Column(name = "defaclrole", nullable = false)
	public int getDefaclrole() {
		return this.defaclrole;
	}

	public void setDefaclrole(int defaclrole) {
		this.defaclrole = defaclrole;
	}

	@Column(name = "defaclnamespace", nullable = false)
	public int getDefaclnamespace() {
		return this.defaclnamespace;
	}

	public void setDefaclnamespace(int defaclnamespace) {
		this.defaclnamespace = defaclnamespace;
	}

	@Column(name = "defaclobjtype", nullable = false)
	public Serializable getDefaclobjtype() {
		return this.defaclobjtype;
	}

	public void setDefaclobjtype(Serializable defaclobjtype) {
		this.defaclobjtype = defaclobjtype;
	}

	@Column(name = "defaclacl")
	public Serializable getDefaclacl() {
		return this.defaclacl;
	}

	public void setDefaclacl(Serializable defaclacl) {
		this.defaclacl = defaclacl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgDefaultAclId))
			return false;
		PgDefaultAclId castOther = (PgDefaultAclId) other;

		return (this.getDefaclrole() == castOther.getDefaclrole())
				&& (this.getDefaclnamespace() == castOther.getDefaclnamespace())
				&& ((this.getDefaclobjtype() == castOther.getDefaclobjtype())
						|| (this.getDefaclobjtype() != null && castOther.getDefaclobjtype() != null
								&& this.getDefaclobjtype().equals(castOther.getDefaclobjtype())))
				&& ((this.getDefaclacl() == castOther.getDefaclacl()) || (this.getDefaclacl() != null
						&& castOther.getDefaclacl() != null && this.getDefaclacl().equals(castOther.getDefaclacl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDefaclrole();
		result = 37 * result + this.getDefaclnamespace();
		result = 37 * result + (getDefaclobjtype() == null ? 0 : this.getDefaclobjtype().hashCode());
		result = 37 * result + (getDefaclacl() == null ? 0 : this.getDefaclacl().hashCode());
		return result;
	}

}
