package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgDescriptionId generated by hbm2java
 */
@Embeddable
public class PgDescriptionId implements java.io.Serializable {

	private int objoid;
	private int classoid;
	private int objsubid;
	private String description;

	public PgDescriptionId() {
	}

	public PgDescriptionId(int objoid, int classoid, int objsubid, String description) {
		this.objoid = objoid;
		this.classoid = classoid;
		this.objsubid = objsubid;
		this.description = description;
	}

	@Column(name = "objoid", nullable = false)
	public int getObjoid() {
		return this.objoid;
	}

	public void setObjoid(int objoid) {
		this.objoid = objoid;
	}

	@Column(name = "classoid", nullable = false)
	public int getClassoid() {
		return this.classoid;
	}

	public void setClassoid(int classoid) {
		this.classoid = classoid;
	}

	@Column(name = "objsubid", nullable = false)
	public int getObjsubid() {
		return this.objsubid;
	}

	public void setObjsubid(int objsubid) {
		this.objsubid = objsubid;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgDescriptionId))
			return false;
		PgDescriptionId castOther = (PgDescriptionId) other;

		return (this.getObjoid() == castOther.getObjoid()) && (this.getClassoid() == castOther.getClassoid())
				&& (this.getObjsubid() == castOther.getObjsubid())
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getObjoid();
		result = 37 * result + this.getClassoid();
		result = 37 * result + this.getObjsubid();
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		return result;
	}

}
