package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PgDepend generated by hbm2java
 */
@Entity
@Table(name = "pg_depend", schema = "pg_catalog")
public class PgDepend implements java.io.Serializable {

	private PgDependId id;

	public PgDepend() {
	}

	public PgDepend(PgDependId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "classid", column = @Column(name = "classid", nullable = false)),
			@AttributeOverride(name = "objid", column = @Column(name = "objid", nullable = false)),
			@AttributeOverride(name = "objsubid", column = @Column(name = "objsubid", nullable = false)),
			@AttributeOverride(name = "refclassid", column = @Column(name = "refclassid", nullable = false)),
			@AttributeOverride(name = "refobjid", column = @Column(name = "refobjid", nullable = false)),
			@AttributeOverride(name = "refobjsubid", column = @Column(name = "refobjsubid", nullable = false)),
			@AttributeOverride(name = "deptype", column = @Column(name = "deptype", nullable = false)) })
	public PgDependId getId() {
		return this.id;
	}

	public void setId(PgDependId id) {
		this.id = id;
	}

}
