package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgDescription generated by hbm2java
 */
@Entity
@Table(name = "pg_description", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = { "objoid",
		"classoid", "objsubid" }))
public class PgDescription implements java.io.Serializable {

	private PgDescriptionId id;

	public PgDescription() {
	}

	public PgDescription(PgDescriptionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "objoid", column = @Column(name = "objoid", nullable = false)),
			@AttributeOverride(name = "classoid", column = @Column(name = "classoid", nullable = false)),
			@AttributeOverride(name = "objsubid", column = @Column(name = "objsubid", nullable = false)),
			@AttributeOverride(name = "description", column = @Column(name = "description", nullable = false)) })
	public PgDescriptionId getId() {
		return this.id;
	}

	public void setId(PgDescriptionId id) {
		this.id = id;
	}

}
