package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgEnumId generated by hbm2java
 */
@Embeddable
public class PgEnumId implements java.io.Serializable {

	private int enumtypid;
	private float enumsortorder;
	private String enumlabel;

	public PgEnumId() {
	}

	public PgEnumId(int enumtypid, float enumsortorder, String enumlabel) {
		this.enumtypid = enumtypid;
		this.enumsortorder = enumsortorder;
		this.enumlabel = enumlabel;
	}

	@Column(name = "enumtypid", nullable = false)
	public int getEnumtypid() {
		return this.enumtypid;
	}

	public void setEnumtypid(int enumtypid) {
		this.enumtypid = enumtypid;
	}

	@Column(name = "enumsortorder", nullable = false, precision = 4, scale = 0)
	public float getEnumsortorder() {
		return this.enumsortorder;
	}

	public void setEnumsortorder(float enumsortorder) {
		this.enumsortorder = enumsortorder;
	}

	@Column(name = "enumlabel", nullable = false, length = 64)
	public String getEnumlabel() {
		return this.enumlabel;
	}

	public void setEnumlabel(String enumlabel) {
		this.enumlabel = enumlabel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgEnumId))
			return false;
		PgEnumId castOther = (PgEnumId) other;

		return (this.getEnumtypid() == castOther.getEnumtypid())
				&& (this.getEnumsortorder() == castOther.getEnumsortorder())
				&& ((this.getEnumlabel() == castOther.getEnumlabel()) || (this.getEnumlabel() != null
						&& castOther.getEnumlabel() != null && this.getEnumlabel().equals(castOther.getEnumlabel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEnumtypid();
		result = 37 * result + (int) this.getEnumsortorder();
		result = 37 * result + (getEnumlabel() == null ? 0 : this.getEnumlabel().hashCode());
		return result;
	}

}
