package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgEnum generated by hbm2java
 */
@Entity
@Table(name = "pg_enum", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "enumtypid", "enumlabel" }),
		@UniqueConstraint(columnNames = { "enumtypid", "enumsortorder" }) })
public class PgEnum implements java.io.Serializable {

	private PgEnumId id;

	public PgEnum() {
	}

	public PgEnum(PgEnumId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "enumtypid", column = @Column(name = "enumtypid", nullable = false)),
			@AttributeOverride(name = "enumsortorder", column = @Column(name = "enumsortorder", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "enumlabel", column = @Column(name = "enumlabel", nullable = false, length = 64)) })
	public PgEnumId getId() {
		return this.id;
	}

	public void setId(PgEnumId id) {
		this.id = id;
	}

}
