package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgEventTrigger generated by hbm2java
 */
@Entity
@Table(name = "pg_event_trigger", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = "evtname"), @UniqueConstraint(columnNames = "oid") })
public class PgEventTrigger implements java.io.Serializable {

	private PgEventTriggerId id;

	public PgEventTrigger() {
	}

	public PgEventTrigger(PgEventTriggerId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "evtname", column = @Column(name = "evtname", unique = true, nullable = false, length = 64)),
			@AttributeOverride(name = "evtevent", column = @Column(name = "evtevent", nullable = false, length = 64)),
			@AttributeOverride(name = "evtowner", column = @Column(name = "evtowner", nullable = false)),
			@AttributeOverride(name = "evtfoid", column = @Column(name = "evtfoid", nullable = false)),
			@AttributeOverride(name = "evtenabled", column = @Column(name = "evtenabled", nullable = false)),
			@AttributeOverride(name = "evttags", column = @Column(name = "evttags")) })
	public PgEventTriggerId getId() {
		return this.id;
	}

	public void setId(PgEventTriggerId id) {
		this.id = id;
	}

}
