package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgEventTriggerId generated by hbm2java
 */
@Embeddable
public class PgEventTriggerId implements java.io.Serializable {

	private String evtname;
	private String evtevent;
	private int evtowner;
	private int evtfoid;
	private Serializable evtenabled;
	private Serializable evttags;

	public PgEventTriggerId() {
	}

	public PgEventTriggerId(String evtname, String evtevent, int evtowner, int evtfoid, Serializable evtenabled) {
		this.evtname = evtname;
		this.evtevent = evtevent;
		this.evtowner = evtowner;
		this.evtfoid = evtfoid;
		this.evtenabled = evtenabled;
	}

	public PgEventTriggerId(String evtname, String evtevent, int evtowner, int evtfoid, Serializable evtenabled,
			Serializable evttags) {
		this.evtname = evtname;
		this.evtevent = evtevent;
		this.evtowner = evtowner;
		this.evtfoid = evtfoid;
		this.evtenabled = evtenabled;
		this.evttags = evttags;
	}

	@Column(name = "evtname", unique = true, nullable = false, length = 64)
	public String getEvtname() {
		return this.evtname;
	}

	public void setEvtname(String evtname) {
		this.evtname = evtname;
	}

	@Column(name = "evtevent", nullable = false, length = 64)
	public String getEvtevent() {
		return this.evtevent;
	}

	public void setEvtevent(String evtevent) {
		this.evtevent = evtevent;
	}

	@Column(name = "evtowner", nullable = false)
	public int getEvtowner() {
		return this.evtowner;
	}

	public void setEvtowner(int evtowner) {
		this.evtowner = evtowner;
	}

	@Column(name = "evtfoid", nullable = false)
	public int getEvtfoid() {
		return this.evtfoid;
	}

	public void setEvtfoid(int evtfoid) {
		this.evtfoid = evtfoid;
	}

	@Column(name = "evtenabled", nullable = false)
	public Serializable getEvtenabled() {
		return this.evtenabled;
	}

	public void setEvtenabled(Serializable evtenabled) {
		this.evtenabled = evtenabled;
	}

	@Column(name = "evttags")
	public Serializable getEvttags() {
		return this.evttags;
	}

	public void setEvttags(Serializable evttags) {
		this.evttags = evttags;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgEventTriggerId))
			return false;
		PgEventTriggerId castOther = (PgEventTriggerId) other;

		return ((this.getEvtname() == castOther.getEvtname()) || (this.getEvtname() != null
				&& castOther.getEvtname() != null && this.getEvtname().equals(castOther.getEvtname())))
				&& ((this.getEvtevent() == castOther.getEvtevent()) || (this.getEvtevent() != null
						&& castOther.getEvtevent() != null && this.getEvtevent().equals(castOther.getEvtevent())))
				&& (this.getEvtowner() == castOther.getEvtowner()) && (this.getEvtfoid() == castOther.getEvtfoid())
				&& ((this.getEvtenabled() == castOther.getEvtenabled()) || (this.getEvtenabled() != null
						&& castOther.getEvtenabled() != null && this.getEvtenabled().equals(castOther.getEvtenabled())))
				&& ((this.getEvttags() == castOther.getEvttags()) || (this.getEvttags() != null
						&& castOther.getEvttags() != null && this.getEvttags().equals(castOther.getEvttags())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEvtname() == null ? 0 : this.getEvtname().hashCode());
		result = 37 * result + (getEvtevent() == null ? 0 : this.getEvtevent().hashCode());
		result = 37 * result + this.getEvtowner();
		result = 37 * result + this.getEvtfoid();
		result = 37 * result + (getEvtenabled() == null ? 0 : this.getEvtenabled().hashCode());
		result = 37 * result + (getEvttags() == null ? 0 : this.getEvttags().hashCode());
		return result;
	}

}
