package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgExtensionId generated by hbm2java
 */
@Embeddable
public class PgExtensionId implements java.io.Serializable {

	private String extname;
	private int extowner;
	private int extnamespace;
	private boolean extrelocatable;
	private String extversion;
	private Serializable extconfig;
	private Serializable extcondition;

	public PgExtensionId() {
	}

	public PgExtensionId(String extname, int extowner, int extnamespace, boolean extrelocatable, String extversion) {
		this.extname = extname;
		this.extowner = extowner;
		this.extnamespace = extnamespace;
		this.extrelocatable = extrelocatable;
		this.extversion = extversion;
	}

	public PgExtensionId(String extname, int extowner, int extnamespace, boolean extrelocatable, String extversion,
			Serializable extconfig, Serializable extcondition) {
		this.extname = extname;
		this.extowner = extowner;
		this.extnamespace = extnamespace;
		this.extrelocatable = extrelocatable;
		this.extversion = extversion;
		this.extconfig = extconfig;
		this.extcondition = extcondition;
	}

	@Column(name = "extname", unique = true, nullable = false, length = 64)
	public String getExtname() {
		return this.extname;
	}

	public void setExtname(String extname) {
		this.extname = extname;
	}

	@Column(name = "extowner", nullable = false)
	public int getExtowner() {
		return this.extowner;
	}

	public void setExtowner(int extowner) {
		this.extowner = extowner;
	}

	@Column(name = "extnamespace", nullable = false)
	public int getExtnamespace() {
		return this.extnamespace;
	}

	public void setExtnamespace(int extnamespace) {
		this.extnamespace = extnamespace;
	}

	@Column(name = "extrelocatable", nullable = false)
	public boolean isExtrelocatable() {
		return this.extrelocatable;
	}

	public void setExtrelocatable(boolean extrelocatable) {
		this.extrelocatable = extrelocatable;
	}

	@Column(name = "extversion", nullable = false)
	public String getExtversion() {
		return this.extversion;
	}

	public void setExtversion(String extversion) {
		this.extversion = extversion;
	}

	@Column(name = "extconfig")
	public Serializable getExtconfig() {
		return this.extconfig;
	}

	public void setExtconfig(Serializable extconfig) {
		this.extconfig = extconfig;
	}

	@Column(name = "extcondition")
	public Serializable getExtcondition() {
		return this.extcondition;
	}

	public void setExtcondition(Serializable extcondition) {
		this.extcondition = extcondition;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgExtensionId))
			return false;
		PgExtensionId castOther = (PgExtensionId) other;

		return ((this.getExtname() == castOther.getExtname()) || (this.getExtname() != null
				&& castOther.getExtname() != null && this.getExtname().equals(castOther.getExtname())))
				&& (this.getExtowner() == castOther.getExtowner())
				&& (this.getExtnamespace() == castOther.getExtnamespace())
				&& (this.isExtrelocatable() == castOther.isExtrelocatable())
				&& ((this.getExtversion() == castOther.getExtversion()) || (this.getExtversion() != null
						&& castOther.getExtversion() != null && this.getExtversion().equals(castOther.getExtversion())))
				&& ((this.getExtconfig() == castOther.getExtconfig()) || (this.getExtconfig() != null
						&& castOther.getExtconfig() != null && this.getExtconfig().equals(castOther.getExtconfig())))
				&& ((this.getExtcondition() == castOther.getExtcondition())
						|| (this.getExtcondition() != null && castOther.getExtcondition() != null
								&& this.getExtcondition().equals(castOther.getExtcondition())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getExtname() == null ? 0 : this.getExtname().hashCode());
		result = 37 * result + this.getExtowner();
		result = 37 * result + this.getExtnamespace();
		result = 37 * result + (this.isExtrelocatable() ? 1 : 0);
		result = 37 * result + (getExtversion() == null ? 0 : this.getExtversion().hashCode());
		result = 37 * result + (getExtconfig() == null ? 0 : this.getExtconfig().hashCode());
		result = 37 * result + (getExtcondition() == null ? 0 : this.getExtcondition().hashCode());
		return result;
	}

}
