package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgExtension generated by hbm2java
 */
@Entity
@Table(name = "pg_extension", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "extname"),
		@UniqueConstraint(columnNames = "oid") })
public class PgExtension implements java.io.Serializable {

	private PgExtensionId id;

	public PgExtension() {
	}

	public PgExtension(PgExtensionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "extname", column = @Column(name = "extname", unique = true, nullable = false, length = 64)),
			@AttributeOverride(name = "extowner", column = @Column(name = "extowner", nullable = false)),
			@AttributeOverride(name = "extnamespace", column = @Column(name = "extnamespace", nullable = false)),
			@AttributeOverride(name = "extrelocatable", column = @Column(name = "extrelocatable", nullable = false)),
			@AttributeOverride(name = "extversion", column = @Column(name = "extversion", nullable = false)),
			@AttributeOverride(name = "extconfig", column = @Column(name = "extconfig")),
			@AttributeOverride(name = "extcondition", column = @Column(name = "extcondition")) })
	public PgExtensionId getId() {
		return this.id;
	}

	public void setId(PgExtensionId id) {
		this.id = id;
	}

}
