package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgForeignServer generated by hbm2java
 */
@Entity
@Table(name = "pg_foreign_server", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = "srvname"), @UniqueConstraint(columnNames = "oid") })
public class PgForeignServer implements java.io.Serializable {

	private PgForeignServerId id;

	public PgForeignServer() {
	}

	public PgForeignServer(PgForeignServerId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "srvname", column = @Column(name = "srvname", unique = true, nullable = false, length = 64)),
			@AttributeOverride(name = "srvowner", column = @Column(name = "srvowner", nullable = false)),
			@AttributeOverride(name = "srvfdw", column = @Column(name = "srvfdw", nullable = false)),
			@AttributeOverride(name = "srvtype", column = @Column(name = "srvtype")),
			@AttributeOverride(name = "srvversion", column = @Column(name = "srvversion")),
			@AttributeOverride(name = "srvacl", column = @Column(name = "srvacl")),
			@AttributeOverride(name = "srvoptions", column = @Column(name = "srvoptions")) })
	public PgForeignServerId getId() {
		return this.id;
	}

	public void setId(PgForeignServerId id) {
		this.id = id;
	}

}
