package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgForeignServerId generated by hbm2java
 */
@Embeddable
public class PgForeignServerId implements java.io.Serializable {

	private String srvname;
	private int srvowner;
	private int srvfdw;
	private String srvtype;
	private String srvversion;
	private Serializable srvacl;
	private Serializable srvoptions;

	public PgForeignServerId() {
	}

	public PgForeignServerId(String srvname, int srvowner, int srvfdw) {
		this.srvname = srvname;
		this.srvowner = srvowner;
		this.srvfdw = srvfdw;
	}

	public PgForeignServerId(String srvname, int srvowner, int srvfdw, String srvtype, String srvversion,
			Serializable srvacl, Serializable srvoptions) {
		this.srvname = srvname;
		this.srvowner = srvowner;
		this.srvfdw = srvfdw;
		this.srvtype = srvtype;
		this.srvversion = srvversion;
		this.srvacl = srvacl;
		this.srvoptions = srvoptions;
	}

	@Column(name = "srvname", unique = true, nullable = false, length = 64)
	public String getSrvname() {
		return this.srvname;
	}

	public void setSrvname(String srvname) {
		this.srvname = srvname;
	}

	@Column(name = "srvowner", nullable = false)
	public int getSrvowner() {
		return this.srvowner;
	}

	public void setSrvowner(int srvowner) {
		this.srvowner = srvowner;
	}

	@Column(name = "srvfdw", nullable = false)
	public int getSrvfdw() {
		return this.srvfdw;
	}

	public void setSrvfdw(int srvfdw) {
		this.srvfdw = srvfdw;
	}

	@Column(name = "srvtype")
	public String getSrvtype() {
		return this.srvtype;
	}

	public void setSrvtype(String srvtype) {
		this.srvtype = srvtype;
	}

	@Column(name = "srvversion")
	public String getSrvversion() {
		return this.srvversion;
	}

	public void setSrvversion(String srvversion) {
		this.srvversion = srvversion;
	}

	@Column(name = "srvacl")
	public Serializable getSrvacl() {
		return this.srvacl;
	}

	public void setSrvacl(Serializable srvacl) {
		this.srvacl = srvacl;
	}

	@Column(name = "srvoptions")
	public Serializable getSrvoptions() {
		return this.srvoptions;
	}

	public void setSrvoptions(Serializable srvoptions) {
		this.srvoptions = srvoptions;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgForeignServerId))
			return false;
		PgForeignServerId castOther = (PgForeignServerId) other;

		return ((this.getSrvname() == castOther.getSrvname()) || (this.getSrvname() != null
				&& castOther.getSrvname() != null && this.getSrvname().equals(castOther.getSrvname())))
				&& (this.getSrvowner() == castOther.getSrvowner()) && (this.getSrvfdw() == castOther.getSrvfdw())
				&& ((this.getSrvtype() == castOther.getSrvtype()) || (this.getSrvtype() != null
						&& castOther.getSrvtype() != null && this.getSrvtype().equals(castOther.getSrvtype())))
				&& ((this.getSrvversion() == castOther.getSrvversion()) || (this.getSrvversion() != null
						&& castOther.getSrvversion() != null && this.getSrvversion().equals(castOther.getSrvversion())))
				&& ((this.getSrvacl() == castOther.getSrvacl()) || (this.getSrvacl() != null
						&& castOther.getSrvacl() != null && this.getSrvacl().equals(castOther.getSrvacl())))
				&& ((this.getSrvoptions() == castOther.getSrvoptions())
						|| (this.getSrvoptions() != null && castOther.getSrvoptions() != null
								&& this.getSrvoptions().equals(castOther.getSrvoptions())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSrvname() == null ? 0 : this.getSrvname().hashCode());
		result = 37 * result + this.getSrvowner();
		result = 37 * result + this.getSrvfdw();
		result = 37 * result + (getSrvtype() == null ? 0 : this.getSrvtype().hashCode());
		result = 37 * result + (getSrvversion() == null ? 0 : this.getSrvversion().hashCode());
		result = 37 * result + (getSrvacl() == null ? 0 : this.getSrvacl().hashCode());
		result = 37 * result + (getSrvoptions() == null ? 0 : this.getSrvoptions().hashCode());
		return result;
	}

}
