package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgForeignTable generated by hbm2java
 */
@Entity
@Table(name = "pg_foreign_table", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = "ftrelid"))
public class PgForeignTable implements java.io.Serializable {

	private PgForeignTableId id;

	public PgForeignTable() {
	}

	public PgForeignTable(PgForeignTableId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ftrelid", column = @Column(name = "ftrelid", unique = true, nullable = false)),
			@AttributeOverride(name = "ftserver", column = @Column(name = "ftserver", nullable = false)),
			@AttributeOverride(name = "ftoptions", column = @Column(name = "ftoptions")) })
	public PgForeignTableId getId() {
		return this.id;
	}

	public void setId(PgForeignTableId id) {
		this.id = id;
	}

}
