package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgForeignTableId generated by hbm2java
 */
@Embeddable
public class PgForeignTableId implements java.io.Serializable {

	private int ftrelid;
	private int ftserver;
	private Serializable ftoptions;

	public PgForeignTableId() {
	}

	public PgForeignTableId(int ftrelid, int ftserver) {
		this.ftrelid = ftrelid;
		this.ftserver = ftserver;
	}

	public PgForeignTableId(int ftrelid, int ftserver, Serializable ftoptions) {
		this.ftrelid = ftrelid;
		this.ftserver = ftserver;
		this.ftoptions = ftoptions;
	}

	@Column(name = "ftrelid", unique = true, nullable = false)
	public int getFtrelid() {
		return this.ftrelid;
	}

	public void setFtrelid(int ftrelid) {
		this.ftrelid = ftrelid;
	}

	@Column(name = "ftserver", nullable = false)
	public int getFtserver() {
		return this.ftserver;
	}

	public void setFtserver(int ftserver) {
		this.ftserver = ftserver;
	}

	@Column(name = "ftoptions")
	public Serializable getFtoptions() {
		return this.ftoptions;
	}

	public void setFtoptions(Serializable ftoptions) {
		this.ftoptions = ftoptions;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgForeignTableId))
			return false;
		PgForeignTableId castOther = (PgForeignTableId) other;

		return (this.getFtrelid() == castOther.getFtrelid()) && (this.getFtserver() == castOther.getFtserver())
				&& ((this.getFtoptions() == castOther.getFtoptions()) || (this.getFtoptions() != null
						&& castOther.getFtoptions() != null && this.getFtoptions().equals(castOther.getFtoptions())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFtrelid();
		result = 37 * result + this.getFtserver();
		result = 37 * result + (getFtoptions() == null ? 0 : this.getFtoptions().hashCode());
		return result;
	}

}
