package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgInherits generated by hbm2java
 */
@Entity
@Table(name = "pg_inherits", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = { "inhrelid",
		"inhseqno" }))
public class PgInherits implements java.io.Serializable {

	private PgInheritsId id;

	public PgInherits() {
	}

	public PgInherits(PgInheritsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "inhrelid", column = @Column(name = "inhrelid", nullable = false)),
			@AttributeOverride(name = "inhparent", column = @Column(name = "inhparent", nullable = false)),
			@AttributeOverride(name = "inhseqno", column = @Column(name = "inhseqno", nullable = false)) })
	public PgInheritsId getId() {
		return this.id;
	}

	public void setId(PgInheritsId id) {
		this.id = id;
	}

}
