package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgInitPrivsId generated by hbm2java
 */
@Embeddable
public class PgInitPrivsId implements java.io.Serializable {

	private int objoid;
	private int classoid;
	private int objsubid;
	private Serializable privtype;
	private Serializable initprivs;

	public PgInitPrivsId() {
	}

	public PgInitPrivsId(int objoid, int classoid, int objsubid, Serializable privtype, Serializable initprivs) {
		this.objoid = objoid;
		this.classoid = classoid;
		this.objsubid = objsubid;
		this.privtype = privtype;
		this.initprivs = initprivs;
	}

	@Column(name = "objoid", nullable = false)
	public int getObjoid() {
		return this.objoid;
	}

	public void setObjoid(int objoid) {
		this.objoid = objoid;
	}

	@Column(name = "classoid", nullable = false)
	public int getClassoid() {
		return this.classoid;
	}

	public void setClassoid(int classoid) {
		this.classoid = classoid;
	}

	@Column(name = "objsubid", nullable = false)
	public int getObjsubid() {
		return this.objsubid;
	}

	public void setObjsubid(int objsubid) {
		this.objsubid = objsubid;
	}

	@Column(name = "privtype", nullable = false)
	public Serializable getPrivtype() {
		return this.privtype;
	}

	public void setPrivtype(Serializable privtype) {
		this.privtype = privtype;
	}

	@Column(name = "initprivs", nullable = false)
	public Serializable getInitprivs() {
		return this.initprivs;
	}

	public void setInitprivs(Serializable initprivs) {
		this.initprivs = initprivs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgInitPrivsId))
			return false;
		PgInitPrivsId castOther = (PgInitPrivsId) other;

		return (this.getObjoid() == castOther.getObjoid()) && (this.getClassoid() == castOther.getClassoid())
				&& (this.getObjsubid() == castOther.getObjsubid())
				&& ((this.getPrivtype() == castOther.getPrivtype()) || (this.getPrivtype() != null
						&& castOther.getPrivtype() != null && this.getPrivtype().equals(castOther.getPrivtype())))
				&& ((this.getInitprivs() == castOther.getInitprivs()) || (this.getInitprivs() != null
						&& castOther.getInitprivs() != null && this.getInitprivs().equals(castOther.getInitprivs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getObjoid();
		result = 37 * result + this.getClassoid();
		result = 37 * result + this.getObjsubid();
		result = 37 * result + (getPrivtype() == null ? 0 : this.getPrivtype().hashCode());
		result = 37 * result + (getInitprivs() == null ? 0 : this.getInitprivs().hashCode());
		return result;
	}

}
