package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgIndex generated by hbm2java
 */
@Entity
@Table(name = "pg_index", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = "indexrelid"))
public class PgIndex implements java.io.Serializable {

	private PgIndexId id;

	public PgIndex() {
	}

	public PgIndex(PgIndexId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "indexrelid", column = @Column(name = "indexrelid", unique = true, nullable = false)),
			@AttributeOverride(name = "indrelid", column = @Column(name = "indrelid", nullable = false)),
			@AttributeOverride(name = "indnatts", column = @Column(name = "indnatts", nullable = false)),
			@AttributeOverride(name = "indisunique", column = @Column(name = "indisunique", nullable = false)),
			@AttributeOverride(name = "indisprimary", column = @Column(name = "indisprimary", nullable = false)),
			@AttributeOverride(name = "indisexclusion", column = @Column(name = "indisexclusion", nullable = false)),
			@AttributeOverride(name = "indimmediate", column = @Column(name = "indimmediate", nullable = false)),
			@AttributeOverride(name = "indisclustered", column = @Column(name = "indisclustered", nullable = false)),
			@AttributeOverride(name = "indisvalid", column = @Column(name = "indisvalid", nullable = false)),
			@AttributeOverride(name = "indcheckxmin", column = @Column(name = "indcheckxmin", nullable = false)),
			@AttributeOverride(name = "indisready", column = @Column(name = "indisready", nullable = false)),
			@AttributeOverride(name = "indislive", column = @Column(name = "indislive", nullable = false)),
			@AttributeOverride(name = "indisreplident", column = @Column(name = "indisreplident", nullable = false)),
			@AttributeOverride(name = "indkey", column = @Column(name = "indkey", nullable = false)),
			@AttributeOverride(name = "indcollation", column = @Column(name = "indcollation", nullable = false)),
			@AttributeOverride(name = "indclass", column = @Column(name = "indclass", nullable = false)),
			@AttributeOverride(name = "indoption", column = @Column(name = "indoption", nullable = false)),
			@AttributeOverride(name = "indexprs", column = @Column(name = "indexprs")),
			@AttributeOverride(name = "indpred", column = @Column(name = "indpred")) })
	public PgIndexId getId() {
		return this.id;
	}

	public void setId(PgIndexId id) {
		this.id = id;
	}

}
