package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgIndexId generated by hbm2java
 */
@Embeddable
public class PgIndexId implements java.io.Serializable {

	private int indexrelid;
	private int indrelid;
	private short indnatts;
	private boolean indisunique;
	private boolean indisprimary;
	private boolean indisexclusion;
	private boolean indimmediate;
	private boolean indisclustered;
	private boolean indisvalid;
	private boolean indcheckxmin;
	private boolean indisready;
	private boolean indislive;
	private boolean indisreplident;
	private Serializable indkey;
	private Serializable indcollation;
	private Serializable indclass;
	private Serializable indoption;
	private Serializable indexprs;
	private Serializable indpred;

	public PgIndexId() {
	}

	public PgIndexId(int indexrelid, int indrelid, short indnatts, boolean indisunique, boolean indisprimary,
			boolean indisexclusion, boolean indimmediate, boolean indisclustered, boolean indisvalid,
			boolean indcheckxmin, boolean indisready, boolean indislive, boolean indisreplident, Serializable indkey,
			Serializable indcollation, Serializable indclass, Serializable indoption) {
		this.indexrelid = indexrelid;
		this.indrelid = indrelid;
		this.indnatts = indnatts;
		this.indisunique = indisunique;
		this.indisprimary = indisprimary;
		this.indisexclusion = indisexclusion;
		this.indimmediate = indimmediate;
		this.indisclustered = indisclustered;
		this.indisvalid = indisvalid;
		this.indcheckxmin = indcheckxmin;
		this.indisready = indisready;
		this.indislive = indislive;
		this.indisreplident = indisreplident;
		this.indkey = indkey;
		this.indcollation = indcollation;
		this.indclass = indclass;
		this.indoption = indoption;
	}

	public PgIndexId(int indexrelid, int indrelid, short indnatts, boolean indisunique, boolean indisprimary,
			boolean indisexclusion, boolean indimmediate, boolean indisclustered, boolean indisvalid,
			boolean indcheckxmin, boolean indisready, boolean indislive, boolean indisreplident, Serializable indkey,
			Serializable indcollation, Serializable indclass, Serializable indoption, Serializable indexprs,
			Serializable indpred) {
		this.indexrelid = indexrelid;
		this.indrelid = indrelid;
		this.indnatts = indnatts;
		this.indisunique = indisunique;
		this.indisprimary = indisprimary;
		this.indisexclusion = indisexclusion;
		this.indimmediate = indimmediate;
		this.indisclustered = indisclustered;
		this.indisvalid = indisvalid;
		this.indcheckxmin = indcheckxmin;
		this.indisready = indisready;
		this.indislive = indislive;
		this.indisreplident = indisreplident;
		this.indkey = indkey;
		this.indcollation = indcollation;
		this.indclass = indclass;
		this.indoption = indoption;
		this.indexprs = indexprs;
		this.indpred = indpred;
	}

	@Column(name = "indexrelid", unique = true, nullable = false)
	public int getIndexrelid() {
		return this.indexrelid;
	}

	public void setIndexrelid(int indexrelid) {
		this.indexrelid = indexrelid;
	}

	@Column(name = "indrelid", nullable = false)
	public int getIndrelid() {
		return this.indrelid;
	}

	public void setIndrelid(int indrelid) {
		this.indrelid = indrelid;
	}

	@Column(name = "indnatts", nullable = false)
	public short getIndnatts() {
		return this.indnatts;
	}

	public void setIndnatts(short indnatts) {
		this.indnatts = indnatts;
	}

	@Column(name = "indisunique", nullable = false)
	public boolean isIndisunique() {
		return this.indisunique;
	}

	public void setIndisunique(boolean indisunique) {
		this.indisunique = indisunique;
	}

	@Column(name = "indisprimary", nullable = false)
	public boolean isIndisprimary() {
		return this.indisprimary;
	}

	public void setIndisprimary(boolean indisprimary) {
		this.indisprimary = indisprimary;
	}

	@Column(name = "indisexclusion", nullable = false)
	public boolean isIndisexclusion() {
		return this.indisexclusion;
	}

	public void setIndisexclusion(boolean indisexclusion) {
		this.indisexclusion = indisexclusion;
	}

	@Column(name = "indimmediate", nullable = false)
	public boolean isIndimmediate() {
		return this.indimmediate;
	}

	public void setIndimmediate(boolean indimmediate) {
		this.indimmediate = indimmediate;
	}

	@Column(name = "indisclustered", nullable = false)
	public boolean isIndisclustered() {
		return this.indisclustered;
	}

	public void setIndisclustered(boolean indisclustered) {
		this.indisclustered = indisclustered;
	}

	@Column(name = "indisvalid", nullable = false)
	public boolean isIndisvalid() {
		return this.indisvalid;
	}

	public void setIndisvalid(boolean indisvalid) {
		this.indisvalid = indisvalid;
	}

	@Column(name = "indcheckxmin", nullable = false)
	public boolean isIndcheckxmin() {
		return this.indcheckxmin;
	}

	public void setIndcheckxmin(boolean indcheckxmin) {
		this.indcheckxmin = indcheckxmin;
	}

	@Column(name = "indisready", nullable = false)
	public boolean isIndisready() {
		return this.indisready;
	}

	public void setIndisready(boolean indisready) {
		this.indisready = indisready;
	}

	@Column(name = "indislive", nullable = false)
	public boolean isIndislive() {
		return this.indislive;
	}

	public void setIndislive(boolean indislive) {
		this.indislive = indislive;
	}

	@Column(name = "indisreplident", nullable = false)
	public boolean isIndisreplident() {
		return this.indisreplident;
	}

	public void setIndisreplident(boolean indisreplident) {
		this.indisreplident = indisreplident;
	}

	@Column(name = "indkey", nullable = false)
	public Serializable getIndkey() {
		return this.indkey;
	}

	public void setIndkey(Serializable indkey) {
		this.indkey = indkey;
	}

	@Column(name = "indcollation", nullable = false)
	public Serializable getIndcollation() {
		return this.indcollation;
	}

	public void setIndcollation(Serializable indcollation) {
		this.indcollation = indcollation;
	}

	@Column(name = "indclass", nullable = false)
	public Serializable getIndclass() {
		return this.indclass;
	}

	public void setIndclass(Serializable indclass) {
		this.indclass = indclass;
	}

	@Column(name = "indoption", nullable = false)
	public Serializable getIndoption() {
		return this.indoption;
	}

	public void setIndoption(Serializable indoption) {
		this.indoption = indoption;
	}

	@Column(name = "indexprs")
	public Serializable getIndexprs() {
		return this.indexprs;
	}

	public void setIndexprs(Serializable indexprs) {
		this.indexprs = indexprs;
	}

	@Column(name = "indpred")
	public Serializable getIndpred() {
		return this.indpred;
	}

	public void setIndpred(Serializable indpred) {
		this.indpred = indpred;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgIndexId))
			return false;
		PgIndexId castOther = (PgIndexId) other;

		return (this.getIndexrelid() == castOther.getIndexrelid()) && (this.getIndrelid() == castOther.getIndrelid())
				&& (this.getIndnatts() == castOther.getIndnatts())
				&& (this.isIndisunique() == castOther.isIndisunique())
				&& (this.isIndisprimary() == castOther.isIndisprimary())
				&& (this.isIndisexclusion() == castOther.isIndisexclusion())
				&& (this.isIndimmediate() == castOther.isIndimmediate())
				&& (this.isIndisclustered() == castOther.isIndisclustered())
				&& (this.isIndisvalid() == castOther.isIndisvalid())
				&& (this.isIndcheckxmin() == castOther.isIndcheckxmin())
				&& (this.isIndisready() == castOther.isIndisready()) && (this.isIndislive() == castOther.isIndislive())
				&& (this.isIndisreplident() == castOther.isIndisreplident())
				&& ((this.getIndkey() == castOther.getIndkey()) || (this.getIndkey() != null
						&& castOther.getIndkey() != null && this.getIndkey().equals(castOther.getIndkey())))
				&& ((this.getIndcollation() == castOther.getIndcollation())
						|| (this.getIndcollation() != null && castOther.getIndcollation() != null
								&& this.getIndcollation().equals(castOther.getIndcollation())))
				&& ((this.getIndclass() == castOther.getIndclass()) || (this.getIndclass() != null
						&& castOther.getIndclass() != null && this.getIndclass().equals(castOther.getIndclass())))
				&& ((this.getIndoption() == castOther.getIndoption()) || (this.getIndoption() != null
						&& castOther.getIndoption() != null && this.getIndoption().equals(castOther.getIndoption())))
				&& ((this.getIndexprs() == castOther.getIndexprs()) || (this.getIndexprs() != null
						&& castOther.getIndexprs() != null && this.getIndexprs().equals(castOther.getIndexprs())))
				&& ((this.getIndpred() == castOther.getIndpred()) || (this.getIndpred() != null
						&& castOther.getIndpred() != null && this.getIndpred().equals(castOther.getIndpred())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIndexrelid();
		result = 37 * result + this.getIndrelid();
		result = 37 * result + this.getIndnatts();
		result = 37 * result + (this.isIndisunique() ? 1 : 0);
		result = 37 * result + (this.isIndisprimary() ? 1 : 0);
		result = 37 * result + (this.isIndisexclusion() ? 1 : 0);
		result = 37 * result + (this.isIndimmediate() ? 1 : 0);
		result = 37 * result + (this.isIndisclustered() ? 1 : 0);
		result = 37 * result + (this.isIndisvalid() ? 1 : 0);
		result = 37 * result + (this.isIndcheckxmin() ? 1 : 0);
		result = 37 * result + (this.isIndisready() ? 1 : 0);
		result = 37 * result + (this.isIndislive() ? 1 : 0);
		result = 37 * result + (this.isIndisreplident() ? 1 : 0);
		result = 37 * result + (getIndkey() == null ? 0 : this.getIndkey().hashCode());
		result = 37 * result + (getIndcollation() == null ? 0 : this.getIndcollation().hashCode());
		result = 37 * result + (getIndclass() == null ? 0 : this.getIndclass().hashCode());
		result = 37 * result + (getIndoption() == null ? 0 : this.getIndoption().hashCode());
		result = 37 * result + (getIndexprs() == null ? 0 : this.getIndexprs().hashCode());
		result = 37 * result + (getIndpred() == null ? 0 : this.getIndpred().hashCode());
		return result;
	}

}
