package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgInitPrivs generated by hbm2java
 */
@Entity
@Table(name = "pg_init_privs", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = { "objoid",
		"classoid", "objsubid" }))
public class PgInitPrivs implements java.io.Serializable {

	private PgInitPrivsId id;

	public PgInitPrivs() {
	}

	public PgInitPrivs(PgInitPrivsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "objoid", column = @Column(name = "objoid", nullable = false)),
			@AttributeOverride(name = "classoid", column = @Column(name = "classoid", nullable = false)),
			@AttributeOverride(name = "objsubid", column = @Column(name = "objsubid", nullable = false)),
			@AttributeOverride(name = "privtype", column = @Column(name = "privtype", nullable = false)),
			@AttributeOverride(name = "initprivs", column = @Column(name = "initprivs", nullable = false)) })
	public PgInitPrivsId getId() {
		return this.id;
	}

	public void setId(PgInitPrivsId id) {
		this.id = id;
	}

}
