package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgInheritsId generated by hbm2java
 */
@Embeddable
public class PgInheritsId implements java.io.Serializable {

	private int inhrelid;
	private int inhparent;
	private int inhseqno;

	public PgInheritsId() {
	}

	public PgInheritsId(int inhrelid, int inhparent, int inhseqno) {
		this.inhrelid = inhrelid;
		this.inhparent = inhparent;
		this.inhseqno = inhseqno;
	}

	@Column(name = "inhrelid", nullable = false)
	public int getInhrelid() {
		return this.inhrelid;
	}

	public void setInhrelid(int inhrelid) {
		this.inhrelid = inhrelid;
	}

	@Column(name = "inhparent", nullable = false)
	public int getInhparent() {
		return this.inhparent;
	}

	public void setInhparent(int inhparent) {
		this.inhparent = inhparent;
	}

	@Column(name = "inhseqno", nullable = false)
	public int getInhseqno() {
		return this.inhseqno;
	}

	public void setInhseqno(int inhseqno) {
		this.inhseqno = inhseqno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgInheritsId))
			return false;
		PgInheritsId castOther = (PgInheritsId) other;

		return (this.getInhrelid() == castOther.getInhrelid()) && (this.getInhparent() == castOther.getInhparent())
				&& (this.getInhseqno() == castOther.getInhseqno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInhrelid();
		result = 37 * result + this.getInhparent();
		result = 37 * result + this.getInhseqno();
		return result;
	}

}
