package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgLanguage generated by hbm2java
 */
@Entity
@Table(name = "pg_language", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "lanname"),
		@UniqueConstraint(columnNames = "oid") })
public class PgLanguage implements java.io.Serializable {

	private PgLanguageId id;

	public PgLanguage() {
	}

	public PgLanguage(PgLanguageId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "lanname", column = @Column(name = "lanname", unique = true, nullable = false, length = 64)),
			@AttributeOverride(name = "lanowner", column = @Column(name = "lanowner", nullable = false)),
			@AttributeOverride(name = "lanispl", column = @Column(name = "lanispl", nullable = false)),
			@AttributeOverride(name = "lanpltrusted", column = @Column(name = "lanpltrusted", nullable = false)),
			@AttributeOverride(name = "lanplcallfoid", column = @Column(name = "lanplcallfoid", nullable = false)),
			@AttributeOverride(name = "laninline", column = @Column(name = "laninline", nullable = false)),
			@AttributeOverride(name = "lanvalidator", column = @Column(name = "lanvalidator", nullable = false)),
			@AttributeOverride(name = "lanacl", column = @Column(name = "lanacl")) })
	public PgLanguageId getId() {
		return this.id;
	}

	public void setId(PgLanguageId id) {
		this.id = id;
	}

}
