package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgLargeobjectId generated by hbm2java
 */
@Embeddable
public class PgLargeobjectId implements java.io.Serializable {

	private int loid;
	private int pageno;
	private byte[] data;

	public PgLargeobjectId() {
	}

	public PgLargeobjectId(int loid, int pageno, byte[] data) {
		this.loid = loid;
		this.pageno = pageno;
		this.data = data;
	}

	@Column(name = "loid", nullable = false)
	public int getLoid() {
		return this.loid;
	}

	public void setLoid(int loid) {
		this.loid = loid;
	}

	@Column(name = "pageno", nullable = false)
	public int getPageno() {
		return this.pageno;
	}

	public void setPageno(int pageno) {
		this.pageno = pageno;
	}

	@Column(name = "data", nullable = false)
	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgLargeobjectId))
			return false;
		PgLargeobjectId castOther = (PgLargeobjectId) other;

		return (this.getLoid() == castOther.getLoid()) && (this.getPageno() == castOther.getPageno())
				&& ((this.getData() == castOther.getData()) || (this.getData() != null && castOther.getData() != null
						&& Arrays.equals(this.getData(), castOther.getData())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLoid();
		result = 37 * result + this.getPageno();
		int dataHashcode = 0;
		byte[] dataProperty = this.getData();
		if (dataProperty != null) {
			dataHashcode = 1;
			for (int i = 0; i < dataProperty.length; i++) {
				dataHashcode = 37 * dataHashcode + dataProperty[i];
			}
		}

		result = 37 * result + dataHashcode;

		return result;
	}

}
