package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgLanguageId generated by hbm2java
 */
@Embeddable
public class PgLanguageId implements java.io.Serializable {

	private String lanname;
	private int lanowner;
	private boolean lanispl;
	private boolean lanpltrusted;
	private int lanplcallfoid;
	private int laninline;
	private int lanvalidator;
	private Serializable lanacl;

	public PgLanguageId() {
	}

	public PgLanguageId(String lanname, int lanowner, boolean lanispl, boolean lanpltrusted, int lanplcallfoid,
			int laninline, int lanvalidator) {
		this.lanname = lanname;
		this.lanowner = lanowner;
		this.lanispl = lanispl;
		this.lanpltrusted = lanpltrusted;
		this.lanplcallfoid = lanplcallfoid;
		this.laninline = laninline;
		this.lanvalidator = lanvalidator;
	}

	public PgLanguageId(String lanname, int lanowner, boolean lanispl, boolean lanpltrusted, int lanplcallfoid,
			int laninline, int lanvalidator, Serializable lanacl) {
		this.lanname = lanname;
		this.lanowner = lanowner;
		this.lanispl = lanispl;
		this.lanpltrusted = lanpltrusted;
		this.lanplcallfoid = lanplcallfoid;
		this.laninline = laninline;
		this.lanvalidator = lanvalidator;
		this.lanacl = lanacl;
	}

	@Column(name = "lanname", unique = true, nullable = false, length = 64)
	public String getLanname() {
		return this.lanname;
	}

	public void setLanname(String lanname) {
		this.lanname = lanname;
	}

	@Column(name = "lanowner", nullable = false)
	public int getLanowner() {
		return this.lanowner;
	}

	public void setLanowner(int lanowner) {
		this.lanowner = lanowner;
	}

	@Column(name = "lanispl", nullable = false)
	public boolean isLanispl() {
		return this.lanispl;
	}

	public void setLanispl(boolean lanispl) {
		this.lanispl = lanispl;
	}

	@Column(name = "lanpltrusted", nullable = false)
	public boolean isLanpltrusted() {
		return this.lanpltrusted;
	}

	public void setLanpltrusted(boolean lanpltrusted) {
		this.lanpltrusted = lanpltrusted;
	}

	@Column(name = "lanplcallfoid", nullable = false)
	public int getLanplcallfoid() {
		return this.lanplcallfoid;
	}

	public void setLanplcallfoid(int lanplcallfoid) {
		this.lanplcallfoid = lanplcallfoid;
	}

	@Column(name = "laninline", nullable = false)
	public int getLaninline() {
		return this.laninline;
	}

	public void setLaninline(int laninline) {
		this.laninline = laninline;
	}

	@Column(name = "lanvalidator", nullable = false)
	public int getLanvalidator() {
		return this.lanvalidator;
	}

	public void setLanvalidator(int lanvalidator) {
		this.lanvalidator = lanvalidator;
	}

	@Column(name = "lanacl")
	public Serializable getLanacl() {
		return this.lanacl;
	}

	public void setLanacl(Serializable lanacl) {
		this.lanacl = lanacl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgLanguageId))
			return false;
		PgLanguageId castOther = (PgLanguageId) other;

		return ((this.getLanname() == castOther.getLanname()) || (this.getLanname() != null
				&& castOther.getLanname() != null && this.getLanname().equals(castOther.getLanname())))
				&& (this.getLanowner() == castOther.getLanowner()) && (this.isLanispl() == castOther.isLanispl())
				&& (this.isLanpltrusted() == castOther.isLanpltrusted())
				&& (this.getLanplcallfoid() == castOther.getLanplcallfoid())
				&& (this.getLaninline() == castOther.getLaninline())
				&& (this.getLanvalidator() == castOther.getLanvalidator())
				&& ((this.getLanacl() == castOther.getLanacl()) || (this.getLanacl() != null
						&& castOther.getLanacl() != null && this.getLanacl().equals(castOther.getLanacl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLanname() == null ? 0 : this.getLanname().hashCode());
		result = 37 * result + this.getLanowner();
		result = 37 * result + (this.isLanispl() ? 1 : 0);
		result = 37 * result + (this.isLanpltrusted() ? 1 : 0);
		result = 37 * result + this.getLanplcallfoid();
		result = 37 * result + this.getLaninline();
		result = 37 * result + this.getLanvalidator();
		result = 37 * result + (getLanacl() == null ? 0 : this.getLanacl().hashCode());
		return result;
	}

}
