package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgLargeobjectMetadata generated by hbm2java
 */
@Entity
@Table(name = "pg_largeobject_metadata", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = "oid"))
public class PgLargeobjectMetadata implements java.io.Serializable {

	private PgLargeobjectMetadataId id;

	public PgLargeobjectMetadata() {
	}

	public PgLargeobjectMetadata(PgLargeobjectMetadataId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "lomowner", column = @Column(name = "lomowner", nullable = false)),
			@AttributeOverride(name = "lomacl", column = @Column(name = "lomacl")) })
	public PgLargeobjectMetadataId getId() {
		return this.id;
	}

	public void setId(PgLargeobjectMetadataId id) {
		this.id = id;
	}

}
