package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgLargeobjectMetadataId generated by hbm2java
 */
@Embeddable
public class PgLargeobjectMetadataId implements java.io.Serializable {

	private int lomowner;
	private Serializable lomacl;

	public PgLargeobjectMetadataId() {
	}

	public PgLargeobjectMetadataId(int lomowner) {
		this.lomowner = lomowner;
	}

	public PgLargeobjectMetadataId(int lomowner, Serializable lomacl) {
		this.lomowner = lomowner;
		this.lomacl = lomacl;
	}

	@Column(name = "lomowner", nullable = false)
	public int getLomowner() {
		return this.lomowner;
	}

	public void setLomowner(int lomowner) {
		this.lomowner = lomowner;
	}

	@Column(name = "lomacl")
	public Serializable getLomacl() {
		return this.lomacl;
	}

	public void setLomacl(Serializable lomacl) {
		this.lomacl = lomacl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgLargeobjectMetadataId))
			return false;
		PgLargeobjectMetadataId castOther = (PgLargeobjectMetadataId) other;

		return (this.getLomowner() == castOther.getLomowner())
				&& ((this.getLomacl() == castOther.getLomacl()) || (this.getLomacl() != null
						&& castOther.getLomacl() != null && this.getLomacl().equals(castOther.getLomacl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLomowner();
		result = 37 * result + (getLomacl() == null ? 0 : this.getLomacl().hashCode());
		return result;
	}

}
