package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgNamespace generated by hbm2java
 */
@Entity
@Table(name = "pg_namespace", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "nspname"),
		@UniqueConstraint(columnNames = "oid") })
public class PgNamespace implements java.io.Serializable {

	private PgNamespaceId id;

	public PgNamespace() {
	}

	public PgNamespace(PgNamespaceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "nspname", column = @Column(name = "nspname", unique = true, nullable = false, length = 64)),
			@AttributeOverride(name = "nspowner", column = @Column(name = "nspowner", nullable = false)),
			@AttributeOverride(name = "nspacl", column = @Column(name = "nspacl")) })
	public PgNamespaceId getId() {
		return this.id;
	}

	public void setId(PgNamespaceId id) {
		this.id = id;
	}

}
