package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgNamespaceId generated by hbm2java
 */
@Embeddable
public class PgNamespaceId implements java.io.Serializable {

	private String nspname;
	private int nspowner;
	private Serializable nspacl;

	public PgNamespaceId() {
	}

	public PgNamespaceId(String nspname, int nspowner) {
		this.nspname = nspname;
		this.nspowner = nspowner;
	}

	public PgNamespaceId(String nspname, int nspowner, Serializable nspacl) {
		this.nspname = nspname;
		this.nspowner = nspowner;
		this.nspacl = nspacl;
	}

	@Column(name = "nspname", unique = true, nullable = false, length = 64)
	public String getNspname() {
		return this.nspname;
	}

	public void setNspname(String nspname) {
		this.nspname = nspname;
	}

	@Column(name = "nspowner", nullable = false)
	public int getNspowner() {
		return this.nspowner;
	}

	public void setNspowner(int nspowner) {
		this.nspowner = nspowner;
	}

	@Column(name = "nspacl")
	public Serializable getNspacl() {
		return this.nspacl;
	}

	public void setNspacl(Serializable nspacl) {
		this.nspacl = nspacl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgNamespaceId))
			return false;
		PgNamespaceId castOther = (PgNamespaceId) other;

		return ((this.getNspname() == castOther.getNspname()) || (this.getNspname() != null
				&& castOther.getNspname() != null && this.getNspname().equals(castOther.getNspname())))
				&& (this.getNspowner() == castOther.getNspowner())
				&& ((this.getNspacl() == castOther.getNspacl()) || (this.getNspacl() != null
						&& castOther.getNspacl() != null && this.getNspacl().equals(castOther.getNspacl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNspname() == null ? 0 : this.getNspname().hashCode());
		result = 37 * result + this.getNspowner();
		result = 37 * result + (getNspacl() == null ? 0 : this.getNspacl().hashCode());
		return result;
	}

}
