package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgOpclassId generated by hbm2java
 */
@Embeddable
public class PgOpclassId implements java.io.Serializable {

	private int opcmethod;
	private String opcname;
	private int opcnamespace;
	private int opcowner;
	private int opcfamily;
	private int opcintype;
	private boolean opcdefault;
	private int opckeytype;

	public PgOpclassId() {
	}

	public PgOpclassId(int opcmethod, String opcname, int opcnamespace, int opcowner, int opcfamily, int opcintype,
			boolean opcdefault, int opckeytype) {
		this.opcmethod = opcmethod;
		this.opcname = opcname;
		this.opcnamespace = opcnamespace;
		this.opcowner = opcowner;
		this.opcfamily = opcfamily;
		this.opcintype = opcintype;
		this.opcdefault = opcdefault;
		this.opckeytype = opckeytype;
	}

	@Column(name = "opcmethod", nullable = false)
	public int getOpcmethod() {
		return this.opcmethod;
	}

	public void setOpcmethod(int opcmethod) {
		this.opcmethod = opcmethod;
	}

	@Column(name = "opcname", nullable = false, length = 64)
	public String getOpcname() {
		return this.opcname;
	}

	public void setOpcname(String opcname) {
		this.opcname = opcname;
	}

	@Column(name = "opcnamespace", nullable = false)
	public int getOpcnamespace() {
		return this.opcnamespace;
	}

	public void setOpcnamespace(int opcnamespace) {
		this.opcnamespace = opcnamespace;
	}

	@Column(name = "opcowner", nullable = false)
	public int getOpcowner() {
		return this.opcowner;
	}

	public void setOpcowner(int opcowner) {
		this.opcowner = opcowner;
	}

	@Column(name = "opcfamily", nullable = false)
	public int getOpcfamily() {
		return this.opcfamily;
	}

	public void setOpcfamily(int opcfamily) {
		this.opcfamily = opcfamily;
	}

	@Column(name = "opcintype", nullable = false)
	public int getOpcintype() {
		return this.opcintype;
	}

	public void setOpcintype(int opcintype) {
		this.opcintype = opcintype;
	}

	@Column(name = "opcdefault", nullable = false)
	public boolean isOpcdefault() {
		return this.opcdefault;
	}

	public void setOpcdefault(boolean opcdefault) {
		this.opcdefault = opcdefault;
	}

	@Column(name = "opckeytype", nullable = false)
	public int getOpckeytype() {
		return this.opckeytype;
	}

	public void setOpckeytype(int opckeytype) {
		this.opckeytype = opckeytype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgOpclassId))
			return false;
		PgOpclassId castOther = (PgOpclassId) other;

		return (this.getOpcmethod() == castOther.getOpcmethod())
				&& ((this.getOpcname() == castOther.getOpcname()) || (this.getOpcname() != null
						&& castOther.getOpcname() != null && this.getOpcname().equals(castOther.getOpcname())))
				&& (this.getOpcnamespace() == castOther.getOpcnamespace())
				&& (this.getOpcowner() == castOther.getOpcowner()) && (this.getOpcfamily() == castOther.getOpcfamily())
				&& (this.getOpcintype() == castOther.getOpcintype())
				&& (this.isOpcdefault() == castOther.isOpcdefault())
				&& (this.getOpckeytype() == castOther.getOpckeytype());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOpcmethod();
		result = 37 * result + (getOpcname() == null ? 0 : this.getOpcname().hashCode());
		result = 37 * result + this.getOpcnamespace();
		result = 37 * result + this.getOpcowner();
		result = 37 * result + this.getOpcfamily();
		result = 37 * result + this.getOpcintype();
		result = 37 * result + (this.isOpcdefault() ? 1 : 0);
		result = 37 * result + this.getOpckeytype();
		return result;
	}

}
