package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgOperatorId generated by hbm2java
 */
@Embeddable
public class PgOperatorId implements java.io.Serializable {

	private String oprname;
	private int oprnamespace;
	private int oprowner;
	private Serializable oprkind;
	private boolean oprcanmerge;
	private boolean oprcanhash;
	private int oprleft;
	private int oprright;
	private int oprresult;
	private int oprcom;
	private int oprnegate;
	private Serializable oprcode;
	private Serializable oprrest;
	private Serializable oprjoin;

	public PgOperatorId() {
	}

	public PgOperatorId(String oprname, int oprnamespace, int oprowner, Serializable oprkind, boolean oprcanmerge,
			boolean oprcanhash, int oprleft, int oprright, int oprresult, int oprcom, int oprnegate,
			Serializable oprcode, Serializable oprrest, Serializable oprjoin) {
		this.oprname = oprname;
		this.oprnamespace = oprnamespace;
		this.oprowner = oprowner;
		this.oprkind = oprkind;
		this.oprcanmerge = oprcanmerge;
		this.oprcanhash = oprcanhash;
		this.oprleft = oprleft;
		this.oprright = oprright;
		this.oprresult = oprresult;
		this.oprcom = oprcom;
		this.oprnegate = oprnegate;
		this.oprcode = oprcode;
		this.oprrest = oprrest;
		this.oprjoin = oprjoin;
	}

	@Column(name = "oprname", nullable = false, length = 64)
	public String getOprname() {
		return this.oprname;
	}

	public void setOprname(String oprname) {
		this.oprname = oprname;
	}

	@Column(name = "oprnamespace", nullable = false)
	public int getOprnamespace() {
		return this.oprnamespace;
	}

	public void setOprnamespace(int oprnamespace) {
		this.oprnamespace = oprnamespace;
	}

	@Column(name = "oprowner", nullable = false)
	public int getOprowner() {
		return this.oprowner;
	}

	public void setOprowner(int oprowner) {
		this.oprowner = oprowner;
	}

	@Column(name = "oprkind", nullable = false)
	public Serializable getOprkind() {
		return this.oprkind;
	}

	public void setOprkind(Serializable oprkind) {
		this.oprkind = oprkind;
	}

	@Column(name = "oprcanmerge", nullable = false)
	public boolean isOprcanmerge() {
		return this.oprcanmerge;
	}

	public void setOprcanmerge(boolean oprcanmerge) {
		this.oprcanmerge = oprcanmerge;
	}

	@Column(name = "oprcanhash", nullable = false)
	public boolean isOprcanhash() {
		return this.oprcanhash;
	}

	public void setOprcanhash(boolean oprcanhash) {
		this.oprcanhash = oprcanhash;
	}

	@Column(name = "oprleft", nullable = false)
	public int getOprleft() {
		return this.oprleft;
	}

	public void setOprleft(int oprleft) {
		this.oprleft = oprleft;
	}

	@Column(name = "oprright", nullable = false)
	public int getOprright() {
		return this.oprright;
	}

	public void setOprright(int oprright) {
		this.oprright = oprright;
	}

	@Column(name = "oprresult", nullable = false)
	public int getOprresult() {
		return this.oprresult;
	}

	public void setOprresult(int oprresult) {
		this.oprresult = oprresult;
	}

	@Column(name = "oprcom", nullable = false)
	public int getOprcom() {
		return this.oprcom;
	}

	public void setOprcom(int oprcom) {
		this.oprcom = oprcom;
	}

	@Column(name = "oprnegate", nullable = false)
	public int getOprnegate() {
		return this.oprnegate;
	}

	public void setOprnegate(int oprnegate) {
		this.oprnegate = oprnegate;
	}

	@Column(name = "oprcode", nullable = false)
	public Serializable getOprcode() {
		return this.oprcode;
	}

	public void setOprcode(Serializable oprcode) {
		this.oprcode = oprcode;
	}

	@Column(name = "oprrest", nullable = false)
	public Serializable getOprrest() {
		return this.oprrest;
	}

	public void setOprrest(Serializable oprrest) {
		this.oprrest = oprrest;
	}

	@Column(name = "oprjoin", nullable = false)
	public Serializable getOprjoin() {
		return this.oprjoin;
	}

	public void setOprjoin(Serializable oprjoin) {
		this.oprjoin = oprjoin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgOperatorId))
			return false;
		PgOperatorId castOther = (PgOperatorId) other;

		return ((this.getOprname() == castOther.getOprname()) || (this.getOprname() != null
				&& castOther.getOprname() != null && this.getOprname().equals(castOther.getOprname())))
				&& (this.getOprnamespace() == castOther.getOprnamespace())
				&& (this.getOprowner() == castOther.getOprowner())
				&& ((this.getOprkind() == castOther.getOprkind()) || (this.getOprkind() != null
						&& castOther.getOprkind() != null && this.getOprkind().equals(castOther.getOprkind())))
				&& (this.isOprcanmerge() == castOther.isOprcanmerge())
				&& (this.isOprcanhash() == castOther.isOprcanhash()) && (this.getOprleft() == castOther.getOprleft())
				&& (this.getOprright() == castOther.getOprright()) && (this.getOprresult() == castOther.getOprresult())
				&& (this.getOprcom() == castOther.getOprcom()) && (this.getOprnegate() == castOther.getOprnegate())
				&& ((this.getOprcode() == castOther.getOprcode()) || (this.getOprcode() != null
						&& castOther.getOprcode() != null && this.getOprcode().equals(castOther.getOprcode())))
				&& ((this.getOprrest() == castOther.getOprrest()) || (this.getOprrest() != null
						&& castOther.getOprrest() != null && this.getOprrest().equals(castOther.getOprrest())))
				&& ((this.getOprjoin() == castOther.getOprjoin()) || (this.getOprjoin() != null
						&& castOther.getOprjoin() != null && this.getOprjoin().equals(castOther.getOprjoin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOprname() == null ? 0 : this.getOprname().hashCode());
		result = 37 * result + this.getOprnamespace();
		result = 37 * result + this.getOprowner();
		result = 37 * result + (getOprkind() == null ? 0 : this.getOprkind().hashCode());
		result = 37 * result + (this.isOprcanmerge() ? 1 : 0);
		result = 37 * result + (this.isOprcanhash() ? 1 : 0);
		result = 37 * result + this.getOprleft();
		result = 37 * result + this.getOprright();
		result = 37 * result + this.getOprresult();
		result = 37 * result + this.getOprcom();
		result = 37 * result + this.getOprnegate();
		result = 37 * result + (getOprcode() == null ? 0 : this.getOprcode().hashCode());
		result = 37 * result + (getOprrest() == null ? 0 : this.getOprrest().hashCode());
		result = 37 * result + (getOprjoin() == null ? 0 : this.getOprjoin().hashCode());
		return result;
	}

}
