package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgOpclass generated by hbm2java
 */
@Entity
@Table(name = "pg_opclass", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "opcmethod", "opcname", "opcnamespace" }),
		@UniqueConstraint(columnNames = "oid") })
public class PgOpclass implements java.io.Serializable {

	private PgOpclassId id;

	public PgOpclass() {
	}

	public PgOpclass(PgOpclassId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "opcmethod", column = @Column(name = "opcmethod", nullable = false)),
			@AttributeOverride(name = "opcname", column = @Column(name = "opcname", nullable = false, length = 64)),
			@AttributeOverride(name = "opcnamespace", column = @Column(name = "opcnamespace", nullable = false)),
			@AttributeOverride(name = "opcowner", column = @Column(name = "opcowner", nullable = false)),
			@AttributeOverride(name = "opcfamily", column = @Column(name = "opcfamily", nullable = false)),
			@AttributeOverride(name = "opcintype", column = @Column(name = "opcintype", nullable = false)),
			@AttributeOverride(name = "opcdefault", column = @Column(name = "opcdefault", nullable = false)),
			@AttributeOverride(name = "opckeytype", column = @Column(name = "opckeytype", nullable = false)) })
	public PgOpclassId getId() {
		return this.id;
	}

	public void setId(PgOpclassId id) {
		this.id = id;
	}

}
