package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgOpfamilyId generated by hbm2java
 */
@Embeddable
public class PgOpfamilyId implements java.io.Serializable {

	private int opfmethod;
	private String opfname;
	private int opfnamespace;
	private int opfowner;

	public PgOpfamilyId() {
	}

	public PgOpfamilyId(int opfmethod, String opfname, int opfnamespace, int opfowner) {
		this.opfmethod = opfmethod;
		this.opfname = opfname;
		this.opfnamespace = opfnamespace;
		this.opfowner = opfowner;
	}

	@Column(name = "opfmethod", nullable = false)
	public int getOpfmethod() {
		return this.opfmethod;
	}

	public void setOpfmethod(int opfmethod) {
		this.opfmethod = opfmethod;
	}

	@Column(name = "opfname", nullable = false, length = 64)
	public String getOpfname() {
		return this.opfname;
	}

	public void setOpfname(String opfname) {
		this.opfname = opfname;
	}

	@Column(name = "opfnamespace", nullable = false)
	public int getOpfnamespace() {
		return this.opfnamespace;
	}

	public void setOpfnamespace(int opfnamespace) {
		this.opfnamespace = opfnamespace;
	}

	@Column(name = "opfowner", nullable = false)
	public int getOpfowner() {
		return this.opfowner;
	}

	public void setOpfowner(int opfowner) {
		this.opfowner = opfowner;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgOpfamilyId))
			return false;
		PgOpfamilyId castOther = (PgOpfamilyId) other;

		return (this.getOpfmethod() == castOther.getOpfmethod())
				&& ((this.getOpfname() == castOther.getOpfname()) || (this.getOpfname() != null
						&& castOther.getOpfname() != null && this.getOpfname().equals(castOther.getOpfname())))
				&& (this.getOpfnamespace() == castOther.getOpfnamespace())
				&& (this.getOpfowner() == castOther.getOpfowner());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOpfmethod();
		result = 37 * result + (getOpfname() == null ? 0 : this.getOpfname().hashCode());
		result = 37 * result + this.getOpfnamespace();
		result = 37 * result + this.getOpfowner();
		return result;
	}

}
