package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgOpfamily generated by hbm2java
 */
@Entity
@Table(name = "pg_opfamily", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "opfmethod", "opfname", "opfnamespace" }),
		@UniqueConstraint(columnNames = "oid") })
public class PgOpfamily implements java.io.Serializable {

	private PgOpfamilyId id;

	public PgOpfamily() {
	}

	public PgOpfamily(PgOpfamilyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "opfmethod", column = @Column(name = "opfmethod", nullable = false)),
			@AttributeOverride(name = "opfname", column = @Column(name = "opfname", nullable = false, length = 64)),
			@AttributeOverride(name = "opfnamespace", column = @Column(name = "opfnamespace", nullable = false)),
			@AttributeOverride(name = "opfowner", column = @Column(name = "opfowner", nullable = false)) })
	public PgOpfamilyId getId() {
		return this.id;
	}

	public void setId(PgOpfamilyId id) {
		this.id = id;
	}

}
