package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgOperator generated by hbm2java
 */
@Entity
@Table(name = "pg_operator", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "oprname", "oprleft", "oprright", "oprnamespace" }) })
public class PgOperator implements java.io.Serializable {

	private PgOperatorId id;

	public PgOperator() {
	}

	public PgOperator(PgOperatorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "oprname", column = @Column(name = "oprname", nullable = false, length = 64)),
			@AttributeOverride(name = "oprnamespace", column = @Column(name = "oprnamespace", nullable = false)),
			@AttributeOverride(name = "oprowner", column = @Column(name = "oprowner", nullable = false)),
			@AttributeOverride(name = "oprkind", column = @Column(name = "oprkind", nullable = false)),
			@AttributeOverride(name = "oprcanmerge", column = @Column(name = "oprcanmerge", nullable = false)),
			@AttributeOverride(name = "oprcanhash", column = @Column(name = "oprcanhash", nullable = false)),
			@AttributeOverride(name = "oprleft", column = @Column(name = "oprleft", nullable = false)),
			@AttributeOverride(name = "oprright", column = @Column(name = "oprright", nullable = false)),
			@AttributeOverride(name = "oprresult", column = @Column(name = "oprresult", nullable = false)),
			@AttributeOverride(name = "oprcom", column = @Column(name = "oprcom", nullable = false)),
			@AttributeOverride(name = "oprnegate", column = @Column(name = "oprnegate", nullable = false)),
			@AttributeOverride(name = "oprcode", column = @Column(name = "oprcode", nullable = false)),
			@AttributeOverride(name = "oprrest", column = @Column(name = "oprrest", nullable = false)),
			@AttributeOverride(name = "oprjoin", column = @Column(name = "oprjoin", nullable = false)) })
	public PgOperatorId getId() {
		return this.id;
	}

	public void setId(PgOperatorId id) {
		this.id = id;
	}

}
