package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgPltemplate generated by hbm2java
 */
@Entity
@Table(name = "pg_pltemplate", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = "tmplname"))
public class PgPltemplate implements java.io.Serializable {

	private PgPltemplateId id;

	public PgPltemplate() {
	}

	public PgPltemplate(PgPltemplateId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tmplname", column = @Column(name = "tmplname", unique = true, nullable = false, length = 64)),
			@AttributeOverride(name = "tmpltrusted", column = @Column(name = "tmpltrusted", nullable = false)),
			@AttributeOverride(name = "tmpldbacreate", column = @Column(name = "tmpldbacreate", nullable = false)),
			@AttributeOverride(name = "tmplhandler", column = @Column(name = "tmplhandler", nullable = false)),
			@AttributeOverride(name = "tmplinline", column = @Column(name = "tmplinline")),
			@AttributeOverride(name = "tmplvalidator", column = @Column(name = "tmplvalidator")),
			@AttributeOverride(name = "tmpllibrary", column = @Column(name = "tmpllibrary", nullable = false)),
			@AttributeOverride(name = "tmplacl", column = @Column(name = "tmplacl")) })
	public PgPltemplateId getId() {
		return this.id;
	}

	public void setId(PgPltemplateId id) {
		this.id = id;
	}

}
