package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgPltemplateId generated by hbm2java
 */
@Embeddable
public class PgPltemplateId implements java.io.Serializable {

	private String tmplname;
	private boolean tmpltrusted;
	private boolean tmpldbacreate;
	private String tmplhandler;
	private String tmplinline;
	private String tmplvalidator;
	private String tmpllibrary;
	private Serializable tmplacl;

	public PgPltemplateId() {
	}

	public PgPltemplateId(String tmplname, boolean tmpltrusted, boolean tmpldbacreate, String tmplhandler,
			String tmpllibrary) {
		this.tmplname = tmplname;
		this.tmpltrusted = tmpltrusted;
		this.tmpldbacreate = tmpldbacreate;
		this.tmplhandler = tmplhandler;
		this.tmpllibrary = tmpllibrary;
	}

	public PgPltemplateId(String tmplname, boolean tmpltrusted, boolean tmpldbacreate, String tmplhandler,
			String tmplinline, String tmplvalidator, String tmpllibrary, Serializable tmplacl) {
		this.tmplname = tmplname;
		this.tmpltrusted = tmpltrusted;
		this.tmpldbacreate = tmpldbacreate;
		this.tmplhandler = tmplhandler;
		this.tmplinline = tmplinline;
		this.tmplvalidator = tmplvalidator;
		this.tmpllibrary = tmpllibrary;
		this.tmplacl = tmplacl;
	}

	@Column(name = "tmplname", unique = true, nullable = false, length = 64)
	public String getTmplname() {
		return this.tmplname;
	}

	public void setTmplname(String tmplname) {
		this.tmplname = tmplname;
	}

	@Column(name = "tmpltrusted", nullable = false)
	public boolean isTmpltrusted() {
		return this.tmpltrusted;
	}

	public void setTmpltrusted(boolean tmpltrusted) {
		this.tmpltrusted = tmpltrusted;
	}

	@Column(name = "tmpldbacreate", nullable = false)
	public boolean isTmpldbacreate() {
		return this.tmpldbacreate;
	}

	public void setTmpldbacreate(boolean tmpldbacreate) {
		this.tmpldbacreate = tmpldbacreate;
	}

	@Column(name = "tmplhandler", nullable = false)
	public String getTmplhandler() {
		return this.tmplhandler;
	}

	public void setTmplhandler(String tmplhandler) {
		this.tmplhandler = tmplhandler;
	}

	@Column(name = "tmplinline")
	public String getTmplinline() {
		return this.tmplinline;
	}

	public void setTmplinline(String tmplinline) {
		this.tmplinline = tmplinline;
	}

	@Column(name = "tmplvalidator")
	public String getTmplvalidator() {
		return this.tmplvalidator;
	}

	public void setTmplvalidator(String tmplvalidator) {
		this.tmplvalidator = tmplvalidator;
	}

	@Column(name = "tmpllibrary", nullable = false)
	public String getTmpllibrary() {
		return this.tmpllibrary;
	}

	public void setTmpllibrary(String tmpllibrary) {
		this.tmpllibrary = tmpllibrary;
	}

	@Column(name = "tmplacl")
	public Serializable getTmplacl() {
		return this.tmplacl;
	}

	public void setTmplacl(Serializable tmplacl) {
		this.tmplacl = tmplacl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgPltemplateId))
			return false;
		PgPltemplateId castOther = (PgPltemplateId) other;

		return ((this.getTmplname() == castOther.getTmplname()) || (this.getTmplname() != null
				&& castOther.getTmplname() != null && this.getTmplname().equals(castOther.getTmplname())))
				&& (this.isTmpltrusted() == castOther.isTmpltrusted())
				&& (this.isTmpldbacreate() == castOther.isTmpldbacreate())
				&& ((this.getTmplhandler() == castOther.getTmplhandler())
						|| (this.getTmplhandler() != null && castOther.getTmplhandler() != null
								&& this.getTmplhandler().equals(castOther.getTmplhandler())))
				&& ((this.getTmplinline() == castOther.getTmplinline()) || (this.getTmplinline() != null
						&& castOther.getTmplinline() != null && this.getTmplinline().equals(castOther.getTmplinline())))
				&& ((this.getTmplvalidator() == castOther.getTmplvalidator())
						|| (this.getTmplvalidator() != null && castOther.getTmplvalidator() != null
								&& this.getTmplvalidator().equals(castOther.getTmplvalidator())))
				&& ((this.getTmpllibrary() == castOther.getTmpllibrary())
						|| (this.getTmpllibrary() != null && castOther.getTmpllibrary() != null
								&& this.getTmpllibrary().equals(castOther.getTmpllibrary())))
				&& ((this.getTmplacl() == castOther.getTmplacl()) || (this.getTmplacl() != null
						&& castOther.getTmplacl() != null && this.getTmplacl().equals(castOther.getTmplacl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTmplname() == null ? 0 : this.getTmplname().hashCode());
		result = 37 * result + (this.isTmpltrusted() ? 1 : 0);
		result = 37 * result + (this.isTmpldbacreate() ? 1 : 0);
		result = 37 * result + (getTmplhandler() == null ? 0 : this.getTmplhandler().hashCode());
		result = 37 * result + (getTmplinline() == null ? 0 : this.getTmplinline().hashCode());
		result = 37 * result + (getTmplvalidator() == null ? 0 : this.getTmplvalidator().hashCode());
		result = 37 * result + (getTmpllibrary() == null ? 0 : this.getTmpllibrary().hashCode());
		result = 37 * result + (getTmplacl() == null ? 0 : this.getTmplacl().hashCode());
		return result;
	}

}
