package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgPolicyId generated by hbm2java
 */
@Embeddable
public class PgPolicyId implements java.io.Serializable {

	private String polname;
	private int polrelid;
	private Serializable polcmd;
	private Serializable polroles;
	private Serializable polqual;
	private Serializable polwithcheck;

	public PgPolicyId() {
	}

	public PgPolicyId(String polname, int polrelid, Serializable polcmd) {
		this.polname = polname;
		this.polrelid = polrelid;
		this.polcmd = polcmd;
	}

	public PgPolicyId(String polname, int polrelid, Serializable polcmd, Serializable polroles, Serializable polqual,
			Serializable polwithcheck) {
		this.polname = polname;
		this.polrelid = polrelid;
		this.polcmd = polcmd;
		this.polroles = polroles;
		this.polqual = polqual;
		this.polwithcheck = polwithcheck;
	}

	@Column(name = "polname", nullable = false, length = 64)
	public String getPolname() {
		return this.polname;
	}

	public void setPolname(String polname) {
		this.polname = polname;
	}

	@Column(name = "polrelid", nullable = false)
	public int getPolrelid() {
		return this.polrelid;
	}

	public void setPolrelid(int polrelid) {
		this.polrelid = polrelid;
	}

	@Column(name = "polcmd", nullable = false)
	public Serializable getPolcmd() {
		return this.polcmd;
	}

	public void setPolcmd(Serializable polcmd) {
		this.polcmd = polcmd;
	}

	@Column(name = "polroles")
	public Serializable getPolroles() {
		return this.polroles;
	}

	public void setPolroles(Serializable polroles) {
		this.polroles = polroles;
	}

	@Column(name = "polqual")
	public Serializable getPolqual() {
		return this.polqual;
	}

	public void setPolqual(Serializable polqual) {
		this.polqual = polqual;
	}

	@Column(name = "polwithcheck")
	public Serializable getPolwithcheck() {
		return this.polwithcheck;
	}

	public void setPolwithcheck(Serializable polwithcheck) {
		this.polwithcheck = polwithcheck;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgPolicyId))
			return false;
		PgPolicyId castOther = (PgPolicyId) other;

		return ((this.getPolname() == castOther.getPolname()) || (this.getPolname() != null
				&& castOther.getPolname() != null && this.getPolname().equals(castOther.getPolname())))
				&& (this.getPolrelid() == castOther.getPolrelid())
				&& ((this.getPolcmd() == castOther.getPolcmd()) || (this.getPolcmd() != null
						&& castOther.getPolcmd() != null && this.getPolcmd().equals(castOther.getPolcmd())))
				&& ((this.getPolroles() == castOther.getPolroles()) || (this.getPolroles() != null
						&& castOther.getPolroles() != null && this.getPolroles().equals(castOther.getPolroles())))
				&& ((this.getPolqual() == castOther.getPolqual()) || (this.getPolqual() != null
						&& castOther.getPolqual() != null && this.getPolqual().equals(castOther.getPolqual())))
				&& ((this.getPolwithcheck() == castOther.getPolwithcheck())
						|| (this.getPolwithcheck() != null && castOther.getPolwithcheck() != null
								&& this.getPolwithcheck().equals(castOther.getPolwithcheck())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPolname() == null ? 0 : this.getPolname().hashCode());
		result = 37 * result + this.getPolrelid();
		result = 37 * result + (getPolcmd() == null ? 0 : this.getPolcmd().hashCode());
		result = 37 * result + (getPolroles() == null ? 0 : this.getPolroles().hashCode());
		result = 37 * result + (getPolqual() == null ? 0 : this.getPolqual().hashCode());
		result = 37 * result + (getPolwithcheck() == null ? 0 : this.getPolwithcheck().hashCode());
		return result;
	}

}
