package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgPolicy generated by hbm2java
 */
@Entity
@Table(name = "pg_policy", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "polrelid", "polname" }) })
public class PgPolicy implements java.io.Serializable {

	private PgPolicyId id;

	public PgPolicy() {
	}

	public PgPolicy(PgPolicyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "polname", column = @Column(name = "polname", nullable = false, length = 64)),
			@AttributeOverride(name = "polrelid", column = @Column(name = "polrelid", nullable = false)),
			@AttributeOverride(name = "polcmd", column = @Column(name = "polcmd", nullable = false)),
			@AttributeOverride(name = "polroles", column = @Column(name = "polroles")),
			@AttributeOverride(name = "polqual", column = @Column(name = "polqual")),
			@AttributeOverride(name = "polwithcheck", column = @Column(name = "polwithcheck")) })
	public PgPolicyId getId() {
		return this.id;
	}

	public void setId(PgPolicyId id) {
		this.id = id;
	}

}
