package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgProcId generated by hbm2java
 */
@Embeddable
public class PgProcId implements java.io.Serializable {

	private String proname;
	private int pronamespace;
	private int proowner;
	private int prolang;
	private float procost;
	private float prorows;
	private int provariadic;
	private Serializable protransform;
	private boolean proisagg;
	private boolean proiswindow;
	private boolean prosecdef;
	private boolean proleakproof;
	private boolean proisstrict;
	private boolean proretset;
	private Serializable provolatile;
	private Serializable proparallel;
	private short pronargs;
	private short pronargdefaults;
	private int prorettype;
	private Serializable proargtypes;
	private Serializable proallargtypes;
	private Serializable proargmodes;
	private Serializable proargnames;
	private Serializable proargdefaults;
	private Serializable protrftypes;
	private String prosrc;
	private String probin;
	private Serializable proconfig;
	private Serializable proacl;

	public PgProcId() {
	}

	public PgProcId(String proname, int pronamespace, int proowner, int prolang, float procost, float prorows,
			int provariadic, Serializable protransform, boolean proisagg, boolean proiswindow, boolean prosecdef,
			boolean proleakproof, boolean proisstrict, boolean proretset, Serializable provolatile,
			Serializable proparallel, short pronargs, short pronargdefaults, int prorettype, Serializable proargtypes,
			String prosrc) {
		this.proname = proname;
		this.pronamespace = pronamespace;
		this.proowner = proowner;
		this.prolang = prolang;
		this.procost = procost;
		this.prorows = prorows;
		this.provariadic = provariadic;
		this.protransform = protransform;
		this.proisagg = proisagg;
		this.proiswindow = proiswindow;
		this.prosecdef = prosecdef;
		this.proleakproof = proleakproof;
		this.proisstrict = proisstrict;
		this.proretset = proretset;
		this.provolatile = provolatile;
		this.proparallel = proparallel;
		this.pronargs = pronargs;
		this.pronargdefaults = pronargdefaults;
		this.prorettype = prorettype;
		this.proargtypes = proargtypes;
		this.prosrc = prosrc;
	}

	public PgProcId(String proname, int pronamespace, int proowner, int prolang, float procost, float prorows,
			int provariadic, Serializable protransform, boolean proisagg, boolean proiswindow, boolean prosecdef,
			boolean proleakproof, boolean proisstrict, boolean proretset, Serializable provolatile,
			Serializable proparallel, short pronargs, short pronargdefaults, int prorettype, Serializable proargtypes,
			Serializable proallargtypes, Serializable proargmodes, Serializable proargnames,
			Serializable proargdefaults, Serializable protrftypes, String prosrc, String probin, Serializable proconfig,
			Serializable proacl) {
		this.proname = proname;
		this.pronamespace = pronamespace;
		this.proowner = proowner;
		this.prolang = prolang;
		this.procost = procost;
		this.prorows = prorows;
		this.provariadic = provariadic;
		this.protransform = protransform;
		this.proisagg = proisagg;
		this.proiswindow = proiswindow;
		this.prosecdef = prosecdef;
		this.proleakproof = proleakproof;
		this.proisstrict = proisstrict;
		this.proretset = proretset;
		this.provolatile = provolatile;
		this.proparallel = proparallel;
		this.pronargs = pronargs;
		this.pronargdefaults = pronargdefaults;
		this.prorettype = prorettype;
		this.proargtypes = proargtypes;
		this.proallargtypes = proallargtypes;
		this.proargmodes = proargmodes;
		this.proargnames = proargnames;
		this.proargdefaults = proargdefaults;
		this.protrftypes = protrftypes;
		this.prosrc = prosrc;
		this.probin = probin;
		this.proconfig = proconfig;
		this.proacl = proacl;
	}

	@Column(name = "proname", nullable = false, length = 64)
	public String getProname() {
		return this.proname;
	}

	public void setProname(String proname) {
		this.proname = proname;
	}

	@Column(name = "pronamespace", nullable = false)
	public int getPronamespace() {
		return this.pronamespace;
	}

	public void setPronamespace(int pronamespace) {
		this.pronamespace = pronamespace;
	}

	@Column(name = "proowner", nullable = false)
	public int getProowner() {
		return this.proowner;
	}

	public void setProowner(int proowner) {
		this.proowner = proowner;
	}

	@Column(name = "prolang", nullable = false)
	public int getProlang() {
		return this.prolang;
	}

	public void setProlang(int prolang) {
		this.prolang = prolang;
	}

	@Column(name = "procost", nullable = false, precision = 4, scale = 0)
	public float getProcost() {
		return this.procost;
	}

	public void setProcost(float procost) {
		this.procost = procost;
	}

	@Column(name = "prorows", nullable = false, precision = 4, scale = 0)
	public float getProrows() {
		return this.prorows;
	}

	public void setProrows(float prorows) {
		this.prorows = prorows;
	}

	@Column(name = "provariadic", nullable = false)
	public int getProvariadic() {
		return this.provariadic;
	}

	public void setProvariadic(int provariadic) {
		this.provariadic = provariadic;
	}

	@Column(name = "protransform", nullable = false)
	public Serializable getProtransform() {
		return this.protransform;
	}

	public void setProtransform(Serializable protransform) {
		this.protransform = protransform;
	}

	@Column(name = "proisagg", nullable = false)
	public boolean isProisagg() {
		return this.proisagg;
	}

	public void setProisagg(boolean proisagg) {
		this.proisagg = proisagg;
	}

	@Column(name = "proiswindow", nullable = false)
	public boolean isProiswindow() {
		return this.proiswindow;
	}

	public void setProiswindow(boolean proiswindow) {
		this.proiswindow = proiswindow;
	}

	@Column(name = "prosecdef", nullable = false)
	public boolean isProsecdef() {
		return this.prosecdef;
	}

	public void setProsecdef(boolean prosecdef) {
		this.prosecdef = prosecdef;
	}

	@Column(name = "proleakproof", nullable = false)
	public boolean isProleakproof() {
		return this.proleakproof;
	}

	public void setProleakproof(boolean proleakproof) {
		this.proleakproof = proleakproof;
	}

	@Column(name = "proisstrict", nullable = false)
	public boolean isProisstrict() {
		return this.proisstrict;
	}

	public void setProisstrict(boolean proisstrict) {
		this.proisstrict = proisstrict;
	}

	@Column(name = "proretset", nullable = false)
	public boolean isProretset() {
		return this.proretset;
	}

	public void setProretset(boolean proretset) {
		this.proretset = proretset;
	}

	@Column(name = "provolatile", nullable = false)
	public Serializable getProvolatile() {
		return this.provolatile;
	}

	public void setProvolatile(Serializable provolatile) {
		this.provolatile = provolatile;
	}

	@Column(name = "proparallel", nullable = false)
	public Serializable getProparallel() {
		return this.proparallel;
	}

	public void setProparallel(Serializable proparallel) {
		this.proparallel = proparallel;
	}

	@Column(name = "pronargs", nullable = false)
	public short getPronargs() {
		return this.pronargs;
	}

	public void setPronargs(short pronargs) {
		this.pronargs = pronargs;
	}

	@Column(name = "pronargdefaults", nullable = false)
	public short getPronargdefaults() {
		return this.pronargdefaults;
	}

	public void setPronargdefaults(short pronargdefaults) {
		this.pronargdefaults = pronargdefaults;
	}

	@Column(name = "prorettype", nullable = false)
	public int getProrettype() {
		return this.prorettype;
	}

	public void setProrettype(int prorettype) {
		this.prorettype = prorettype;
	}

	@Column(name = "proargtypes", nullable = false)
	public Serializable getProargtypes() {
		return this.proargtypes;
	}

	public void setProargtypes(Serializable proargtypes) {
		this.proargtypes = proargtypes;
	}

	@Column(name = "proallargtypes")
	public Serializable getProallargtypes() {
		return this.proallargtypes;
	}

	public void setProallargtypes(Serializable proallargtypes) {
		this.proallargtypes = proallargtypes;
	}

	@Column(name = "proargmodes")
	public Serializable getProargmodes() {
		return this.proargmodes;
	}

	public void setProargmodes(Serializable proargmodes) {
		this.proargmodes = proargmodes;
	}

	@Column(name = "proargnames")
	public Serializable getProargnames() {
		return this.proargnames;
	}

	public void setProargnames(Serializable proargnames) {
		this.proargnames = proargnames;
	}

	@Column(name = "proargdefaults")
	public Serializable getProargdefaults() {
		return this.proargdefaults;
	}

	public void setProargdefaults(Serializable proargdefaults) {
		this.proargdefaults = proargdefaults;
	}

	@Column(name = "protrftypes")
	public Serializable getProtrftypes() {
		return this.protrftypes;
	}

	public void setProtrftypes(Serializable protrftypes) {
		this.protrftypes = protrftypes;
	}

	@Column(name = "prosrc", nullable = false)
	public String getProsrc() {
		return this.prosrc;
	}

	public void setProsrc(String prosrc) {
		this.prosrc = prosrc;
	}

	@Column(name = "probin")
	public String getProbin() {
		return this.probin;
	}

	public void setProbin(String probin) {
		this.probin = probin;
	}

	@Column(name = "proconfig")
	public Serializable getProconfig() {
		return this.proconfig;
	}

	public void setProconfig(Serializable proconfig) {
		this.proconfig = proconfig;
	}

	@Column(name = "proacl")
	public Serializable getProacl() {
		return this.proacl;
	}

	public void setProacl(Serializable proacl) {
		this.proacl = proacl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgProcId))
			return false;
		PgProcId castOther = (PgProcId) other;

		return ((this.getProname() == castOther.getProname()) || (this.getProname() != null
				&& castOther.getProname() != null && this.getProname().equals(castOther.getProname())))
				&& (this.getPronamespace() == castOther.getPronamespace())
				&& (this.getProowner() == castOther.getProowner()) && (this.getProlang() == castOther.getProlang())
				&& (this.getProcost() == castOther.getProcost()) && (this.getProrows() == castOther.getProrows())
				&& (this.getProvariadic() == castOther.getProvariadic())
				&& ((this.getProtransform() == castOther.getProtransform())
						|| (this.getProtransform() != null && castOther.getProtransform() != null
								&& this.getProtransform().equals(castOther.getProtransform())))
				&& (this.isProisagg() == castOther.isProisagg()) && (this.isProiswindow() == castOther.isProiswindow())
				&& (this.isProsecdef() == castOther.isProsecdef())
				&& (this.isProleakproof() == castOther.isProleakproof())
				&& (this.isProisstrict() == castOther.isProisstrict())
				&& (this.isProretset() == castOther.isProretset())
				&& ((this.getProvolatile() == castOther.getProvolatile())
						|| (this.getProvolatile() != null && castOther.getProvolatile() != null
								&& this.getProvolatile().equals(castOther.getProvolatile())))
				&& ((this.getProparallel() == castOther.getProparallel())
						|| (this.getProparallel() != null && castOther.getProparallel() != null
								&& this.getProparallel().equals(castOther.getProparallel())))
				&& (this.getPronargs() == castOther.getPronargs())
				&& (this.getPronargdefaults() == castOther.getPronargdefaults())
				&& (this.getProrettype() == castOther.getProrettype())
				&& ((this.getProargtypes() == castOther.getProargtypes())
						|| (this.getProargtypes() != null && castOther.getProargtypes() != null
								&& this.getProargtypes().equals(castOther.getProargtypes())))
				&& ((this.getProallargtypes() == castOther.getProallargtypes())
						|| (this.getProallargtypes() != null && castOther.getProallargtypes() != null
								&& this.getProallargtypes().equals(castOther.getProallargtypes())))
				&& ((this.getProargmodes() == castOther.getProargmodes())
						|| (this.getProargmodes() != null && castOther.getProargmodes() != null
								&& this.getProargmodes().equals(castOther.getProargmodes())))
				&& ((this.getProargnames() == castOther.getProargnames())
						|| (this.getProargnames() != null && castOther.getProargnames() != null
								&& this.getProargnames().equals(castOther.getProargnames())))
				&& ((this.getProargdefaults() == castOther.getProargdefaults())
						|| (this.getProargdefaults() != null && castOther.getProargdefaults() != null
								&& this.getProargdefaults().equals(castOther.getProargdefaults())))
				&& ((this.getProtrftypes() == castOther.getProtrftypes())
						|| (this.getProtrftypes() != null && castOther.getProtrftypes() != null
								&& this.getProtrftypes().equals(castOther.getProtrftypes())))
				&& ((this.getProsrc() == castOther.getProsrc()) || (this.getProsrc() != null
						&& castOther.getProsrc() != null && this.getProsrc().equals(castOther.getProsrc())))
				&& ((this.getProbin() == castOther.getProbin()) || (this.getProbin() != null
						&& castOther.getProbin() != null && this.getProbin().equals(castOther.getProbin())))
				&& ((this.getProconfig() == castOther.getProconfig()) || (this.getProconfig() != null
						&& castOther.getProconfig() != null && this.getProconfig().equals(castOther.getProconfig())))
				&& ((this.getProacl() == castOther.getProacl()) || (this.getProacl() != null
						&& castOther.getProacl() != null && this.getProacl().equals(castOther.getProacl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProname() == null ? 0 : this.getProname().hashCode());
		result = 37 * result + this.getPronamespace();
		result = 37 * result + this.getProowner();
		result = 37 * result + this.getProlang();
		result = 37 * result + (int) this.getProcost();
		result = 37 * result + (int) this.getProrows();
		result = 37 * result + this.getProvariadic();
		result = 37 * result + (getProtransform() == null ? 0 : this.getProtransform().hashCode());
		result = 37 * result + (this.isProisagg() ? 1 : 0);
		result = 37 * result + (this.isProiswindow() ? 1 : 0);
		result = 37 * result + (this.isProsecdef() ? 1 : 0);
		result = 37 * result + (this.isProleakproof() ? 1 : 0);
		result = 37 * result + (this.isProisstrict() ? 1 : 0);
		result = 37 * result + (this.isProretset() ? 1 : 0);
		result = 37 * result + (getProvolatile() == null ? 0 : this.getProvolatile().hashCode());
		result = 37 * result + (getProparallel() == null ? 0 : this.getProparallel().hashCode());
		result = 37 * result + this.getPronargs();
		result = 37 * result + this.getPronargdefaults();
		result = 37 * result + this.getProrettype();
		result = 37 * result + (getProargtypes() == null ? 0 : this.getProargtypes().hashCode());
		result = 37 * result + (getProallargtypes() == null ? 0 : this.getProallargtypes().hashCode());
		result = 37 * result + (getProargmodes() == null ? 0 : this.getProargmodes().hashCode());
		result = 37 * result + (getProargnames() == null ? 0 : this.getProargnames().hashCode());
		result = 37 * result + (getProargdefaults() == null ? 0 : this.getProargdefaults().hashCode());
		result = 37 * result + (getProtrftypes() == null ? 0 : this.getProtrftypes().hashCode());
		result = 37 * result + (getProsrc() == null ? 0 : this.getProsrc().hashCode());
		result = 37 * result + (getProbin() == null ? 0 : this.getProbin().hashCode());
		result = 37 * result + (getProconfig() == null ? 0 : this.getProconfig().hashCode());
		result = 37 * result + (getProacl() == null ? 0 : this.getProacl().hashCode());
		return result;
	}

}
