package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgRange generated by hbm2java
 */
@Entity
@Table(name = "pg_range", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = "rngtypid"))
public class PgRange implements java.io.Serializable {

	private PgRangeId id;

	public PgRange() {
	}

	public PgRange(PgRangeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rngtypid", column = @Column(name = "rngtypid", unique = true, nullable = false)),
			@AttributeOverride(name = "rngsubtype", column = @Column(name = "rngsubtype", nullable = false)),
			@AttributeOverride(name = "rngcollation", column = @Column(name = "rngcollation", nullable = false)),
			@AttributeOverride(name = "rngsubopc", column = @Column(name = "rngsubopc", nullable = false)),
			@AttributeOverride(name = "rngcanonical", column = @Column(name = "rngcanonical", nullable = false)),
			@AttributeOverride(name = "rngsubdiff", column = @Column(name = "rngsubdiff", nullable = false)) })
	public PgRangeId getId() {
		return this.id;
	}

	public void setId(PgRangeId id) {
		this.id = id;
	}

}
