package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgReplicationOrigin generated by hbm2java
 */
@Entity
@Table(name = "pg_replication_origin", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = "roident"), @UniqueConstraint(columnNames = "roname") })
public class PgReplicationOrigin implements java.io.Serializable {

	private PgReplicationOriginId id;

	public PgReplicationOrigin() {
	}

	public PgReplicationOrigin(PgReplicationOriginId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "roident", column = @Column(name = "roident", unique = true, nullable = false)),
			@AttributeOverride(name = "roname", column = @Column(name = "roname", unique = true, nullable = false)) })
	public PgReplicationOriginId getId() {
		return this.id;
	}

	public void setId(PgReplicationOriginId id) {
		this.id = id;
	}

}
