package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgRewriteId generated by hbm2java
 */
@Embeddable
public class PgRewriteId implements java.io.Serializable {

	private String rulename;
	private int evClass;
	private Serializable evType;
	private Serializable evEnabled;
	private boolean isInstead;
	private Serializable evQual;
	private Serializable evAction;

	public PgRewriteId() {
	}

	public PgRewriteId(String rulename, int evClass, Serializable evType, Serializable evEnabled, boolean isInstead) {
		this.rulename = rulename;
		this.evClass = evClass;
		this.evType = evType;
		this.evEnabled = evEnabled;
		this.isInstead = isInstead;
	}

	public PgRewriteId(String rulename, int evClass, Serializable evType, Serializable evEnabled, boolean isInstead,
			Serializable evQual, Serializable evAction) {
		this.rulename = rulename;
		this.evClass = evClass;
		this.evType = evType;
		this.evEnabled = evEnabled;
		this.isInstead = isInstead;
		this.evQual = evQual;
		this.evAction = evAction;
	}

	@Column(name = "rulename", nullable = false, length = 64)
	public String getRulename() {
		return this.rulename;
	}

	public void setRulename(String rulename) {
		this.rulename = rulename;
	}

	@Column(name = "ev_class", nullable = false)
	public int getEvClass() {
		return this.evClass;
	}

	public void setEvClass(int evClass) {
		this.evClass = evClass;
	}

	@Column(name = "ev_type", nullable = false)
	public Serializable getEvType() {
		return this.evType;
	}

	public void setEvType(Serializable evType) {
		this.evType = evType;
	}

	@Column(name = "ev_enabled", nullable = false)
	public Serializable getEvEnabled() {
		return this.evEnabled;
	}

	public void setEvEnabled(Serializable evEnabled) {
		this.evEnabled = evEnabled;
	}

	@Column(name = "is_instead", nullable = false)
	public boolean isIsInstead() {
		return this.isInstead;
	}

	public void setIsInstead(boolean isInstead) {
		this.isInstead = isInstead;
	}

	@Column(name = "ev_qual")
	public Serializable getEvQual() {
		return this.evQual;
	}

	public void setEvQual(Serializable evQual) {
		this.evQual = evQual;
	}

	@Column(name = "ev_action")
	public Serializable getEvAction() {
		return this.evAction;
	}

	public void setEvAction(Serializable evAction) {
		this.evAction = evAction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgRewriteId))
			return false;
		PgRewriteId castOther = (PgRewriteId) other;

		return ((this.getRulename() == castOther.getRulename()) || (this.getRulename() != null
				&& castOther.getRulename() != null && this.getRulename().equals(castOther.getRulename())))
				&& (this.getEvClass() == castOther.getEvClass())
				&& ((this.getEvType() == castOther.getEvType()) || (this.getEvType() != null
						&& castOther.getEvType() != null && this.getEvType().equals(castOther.getEvType())))
				&& ((this.getEvEnabled() == castOther.getEvEnabled()) || (this.getEvEnabled() != null
						&& castOther.getEvEnabled() != null && this.getEvEnabled().equals(castOther.getEvEnabled())))
				&& (this.isIsInstead() == castOther.isIsInstead())
				&& ((this.getEvQual() == castOther.getEvQual()) || (this.getEvQual() != null
						&& castOther.getEvQual() != null && this.getEvQual().equals(castOther.getEvQual())))
				&& ((this.getEvAction() == castOther.getEvAction()) || (this.getEvAction() != null
						&& castOther.getEvAction() != null && this.getEvAction().equals(castOther.getEvAction())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRulename() == null ? 0 : this.getRulename().hashCode());
		result = 37 * result + this.getEvClass();
		result = 37 * result + (getEvType() == null ? 0 : this.getEvType().hashCode());
		result = 37 * result + (getEvEnabled() == null ? 0 : this.getEvEnabled().hashCode());
		result = 37 * result + (this.isIsInstead() ? 1 : 0);
		result = 37 * result + (getEvQual() == null ? 0 : this.getEvQual().hashCode());
		result = 37 * result + (getEvAction() == null ? 0 : this.getEvAction().hashCode());
		return result;
	}

}
