package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgRewrite generated by hbm2java
 */
@Entity
@Table(name = "pg_rewrite", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "ev_class", "rulename" }) })
public class PgRewrite implements java.io.Serializable {

	private PgRewriteId id;

	public PgRewrite() {
	}

	public PgRewrite(PgRewriteId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rulename", column = @Column(name = "rulename", nullable = false, length = 64)),
			@AttributeOverride(name = "evClass", column = @Column(name = "ev_class", nullable = false)),
			@AttributeOverride(name = "evType", column = @Column(name = "ev_type", nullable = false)),
			@AttributeOverride(name = "evEnabled", column = @Column(name = "ev_enabled", nullable = false)),
			@AttributeOverride(name = "isInstead", column = @Column(name = "is_instead", nullable = false)),
			@AttributeOverride(name = "evQual", column = @Column(name = "ev_qual")),
			@AttributeOverride(name = "evAction", column = @Column(name = "ev_action")) })
	public PgRewriteId getId() {
		return this.id;
	}

	public void setId(PgRewriteId id) {
		this.id = id;
	}

}
