package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgSeclabelId generated by hbm2java
 */
@Embeddable
public class PgSeclabelId implements java.io.Serializable {

	private int objoid;
	private int classoid;
	private int objsubid;
	private String provider;
	private String label;

	public PgSeclabelId() {
	}

	public PgSeclabelId(int objoid, int classoid, int objsubid, String provider, String label) {
		this.objoid = objoid;
		this.classoid = classoid;
		this.objsubid = objsubid;
		this.provider = provider;
		this.label = label;
	}

	@Column(name = "objoid", nullable = false)
	public int getObjoid() {
		return this.objoid;
	}

	public void setObjoid(int objoid) {
		this.objoid = objoid;
	}

	@Column(name = "classoid", nullable = false)
	public int getClassoid() {
		return this.classoid;
	}

	public void setClassoid(int classoid) {
		this.classoid = classoid;
	}

	@Column(name = "objsubid", nullable = false)
	public int getObjsubid() {
		return this.objsubid;
	}

	public void setObjsubid(int objsubid) {
		this.objsubid = objsubid;
	}

	@Column(name = "provider", nullable = false)
	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	@Column(name = "label", nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgSeclabelId))
			return false;
		PgSeclabelId castOther = (PgSeclabelId) other;

		return (this.getObjoid() == castOther.getObjoid()) && (this.getClassoid() == castOther.getClassoid())
				&& (this.getObjsubid() == castOther.getObjsubid())
				&& ((this.getProvider() == castOther.getProvider()) || (this.getProvider() != null
						&& castOther.getProvider() != null && this.getProvider().equals(castOther.getProvider())))
				&& ((this.getLabel() == castOther.getLabel()) || (this.getLabel() != null
						&& castOther.getLabel() != null && this.getLabel().equals(castOther.getLabel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getObjoid();
		result = 37 * result + this.getClassoid();
		result = 37 * result + this.getObjsubid();
		result = 37 * result + (getProvider() == null ? 0 : this.getProvider().hashCode());
		result = 37 * result + (getLabel() == null ? 0 : this.getLabel().hashCode());
		return result;
	}

}
