package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgSeclabel generated by hbm2java
 */
@Entity
@Table(name = "pg_seclabel", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = { "objoid",
		"classoid", "objsubid", "provider" }))
public class PgSeclabel implements java.io.Serializable {

	private PgSeclabelId id;

	public PgSeclabel() {
	}

	public PgSeclabel(PgSeclabelId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "objoid", column = @Column(name = "objoid", nullable = false)),
			@AttributeOverride(name = "classoid", column = @Column(name = "classoid", nullable = false)),
			@AttributeOverride(name = "objsubid", column = @Column(name = "objsubid", nullable = false)),
			@AttributeOverride(name = "provider", column = @Column(name = "provider", nullable = false)),
			@AttributeOverride(name = "label", column = @Column(name = "label", nullable = false)) })
	public PgSeclabelId getId() {
		return this.id;
	}

	public void setId(PgSeclabelId id) {
		this.id = id;
	}

}
