package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgShdependId generated by hbm2java
 */
@Embeddable
public class PgShdependId implements java.io.Serializable {

	private int dbid;
	private int classid;
	private int objid;
	private int objsubid;
	private int refclassid;
	private int refobjid;
	private Serializable deptype;

	public PgShdependId() {
	}

	public PgShdependId(int dbid, int classid, int objid, int objsubid, int refclassid, int refobjid,
			Serializable deptype) {
		this.dbid = dbid;
		this.classid = classid;
		this.objid = objid;
		this.objsubid = objsubid;
		this.refclassid = refclassid;
		this.refobjid = refobjid;
		this.deptype = deptype;
	}

	@Column(name = "dbid", nullable = false)
	public int getDbid() {
		return this.dbid;
	}

	public void setDbid(int dbid) {
		this.dbid = dbid;
	}

	@Column(name = "classid", nullable = false)
	public int getClassid() {
		return this.classid;
	}

	public void setClassid(int classid) {
		this.classid = classid;
	}

	@Column(name = "objid", nullable = false)
	public int getObjid() {
		return this.objid;
	}

	public void setObjid(int objid) {
		this.objid = objid;
	}

	@Column(name = "objsubid", nullable = false)
	public int getObjsubid() {
		return this.objsubid;
	}

	public void setObjsubid(int objsubid) {
		this.objsubid = objsubid;
	}

	@Column(name = "refclassid", nullable = false)
	public int getRefclassid() {
		return this.refclassid;
	}

	public void setRefclassid(int refclassid) {
		this.refclassid = refclassid;
	}

	@Column(name = "refobjid", nullable = false)
	public int getRefobjid() {
		return this.refobjid;
	}

	public void setRefobjid(int refobjid) {
		this.refobjid = refobjid;
	}

	@Column(name = "deptype", nullable = false)
	public Serializable getDeptype() {
		return this.deptype;
	}

	public void setDeptype(Serializable deptype) {
		this.deptype = deptype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgShdependId))
			return false;
		PgShdependId castOther = (PgShdependId) other;

		return (this.getDbid() == castOther.getDbid()) && (this.getClassid() == castOther.getClassid())
				&& (this.getObjid() == castOther.getObjid()) && (this.getObjsubid() == castOther.getObjsubid())
				&& (this.getRefclassid() == castOther.getRefclassid())
				&& (this.getRefobjid() == castOther.getRefobjid())
				&& ((this.getDeptype() == castOther.getDeptype()) || (this.getDeptype() != null
						&& castOther.getDeptype() != null && this.getDeptype().equals(castOther.getDeptype())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDbid();
		result = 37 * result + this.getClassid();
		result = 37 * result + this.getObjid();
		result = 37 * result + this.getObjsubid();
		result = 37 * result + this.getRefclassid();
		result = 37 * result + this.getRefobjid();
		result = 37 * result + (getDeptype() == null ? 0 : this.getDeptype().hashCode());
		return result;
	}

}
