package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgShseclabel generated by hbm2java
 */
@Entity
@Table(name = "pg_shseclabel", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = { "objoid",
		"classoid", "provider" }))
public class PgShseclabel implements java.io.Serializable {

	private PgShseclabelId id;

	public PgShseclabel() {
	}

	public PgShseclabel(PgShseclabelId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "objoid", column = @Column(name = "objoid", nullable = false)),
			@AttributeOverride(name = "classoid", column = @Column(name = "classoid", nullable = false)),
			@AttributeOverride(name = "provider", column = @Column(name = "provider", nullable = false)),
			@AttributeOverride(name = "label", column = @Column(name = "label", nullable = false)) })
	public PgShseclabelId getId() {
		return this.id;
	}

	public void setId(PgShseclabelId id) {
		this.id = id;
	}

}
