package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgShdescriptionId generated by hbm2java
 */
@Embeddable
public class PgShdescriptionId implements java.io.Serializable {

	private int objoid;
	private int classoid;
	private String description;

	public PgShdescriptionId() {
	}

	public PgShdescriptionId(int objoid, int classoid, String description) {
		this.objoid = objoid;
		this.classoid = classoid;
		this.description = description;
	}

	@Column(name = "objoid", nullable = false)
	public int getObjoid() {
		return this.objoid;
	}

	public void setObjoid(int objoid) {
		this.objoid = objoid;
	}

	@Column(name = "classoid", nullable = false)
	public int getClassoid() {
		return this.classoid;
	}

	public void setClassoid(int classoid) {
		this.classoid = classoid;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgShdescriptionId))
			return false;
		PgShdescriptionId castOther = (PgShdescriptionId) other;

		return (this.getObjoid() == castOther.getObjoid()) && (this.getClassoid() == castOther.getClassoid())
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getObjoid();
		result = 37 * result + this.getClassoid();
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		return result;
	}

}
