package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgShdescription generated by hbm2java
 */
@Entity
@Table(name = "pg_shdescription", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = { "objoid",
		"classoid" }))
public class PgShdescription implements java.io.Serializable {

	private PgShdescriptionId id;

	public PgShdescription() {
	}

	public PgShdescription(PgShdescriptionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "objoid", column = @Column(name = "objoid", nullable = false)),
			@AttributeOverride(name = "classoid", column = @Column(name = "classoid", nullable = false)),
			@AttributeOverride(name = "description", column = @Column(name = "description", nullable = false)) })
	public PgShdescriptionId getId() {
		return this.id;
	}

	public void setId(PgShdescriptionId id) {
		this.id = id;
	}

}
