package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgStatisticId generated by hbm2java
 */
@Embeddable
public class PgStatisticId implements java.io.Serializable {

	private int starelid;
	private short staattnum;
	private boolean stainherit;
	private float stanullfrac;
	private int stawidth;
	private float stadistinct;
	private short stakind1;
	private short stakind2;
	private short stakind3;
	private short stakind4;
	private short stakind5;
	private int staop1;
	private int staop2;
	private int staop3;
	private int staop4;
	private int staop5;
	private Serializable stanumbers1;
	private Serializable stanumbers2;
	private Serializable stanumbers3;
	private Serializable stanumbers4;
	private Serializable stanumbers5;
	private Serializable stavalues1;
	private Serializable stavalues2;
	private Serializable stavalues3;
	private Serializable stavalues4;
	private Serializable stavalues5;

	public PgStatisticId() {
	}

	public PgStatisticId(int starelid, short staattnum, boolean stainherit, float stanullfrac, int stawidth,
			float stadistinct, short stakind1, short stakind2, short stakind3, short stakind4, short stakind5,
			int staop1, int staop2, int staop3, int staop4, int staop5) {
		this.starelid = starelid;
		this.staattnum = staattnum;
		this.stainherit = stainherit;
		this.stanullfrac = stanullfrac;
		this.stawidth = stawidth;
		this.stadistinct = stadistinct;
		this.stakind1 = stakind1;
		this.stakind2 = stakind2;
		this.stakind3 = stakind3;
		this.stakind4 = stakind4;
		this.stakind5 = stakind5;
		this.staop1 = staop1;
		this.staop2 = staop2;
		this.staop3 = staop3;
		this.staop4 = staop4;
		this.staop5 = staop5;
	}

	public PgStatisticId(int starelid, short staattnum, boolean stainherit, float stanullfrac, int stawidth,
			float stadistinct, short stakind1, short stakind2, short stakind3, short stakind4, short stakind5,
			int staop1, int staop2, int staop3, int staop4, int staop5, Serializable stanumbers1,
			Serializable stanumbers2, Serializable stanumbers3, Serializable stanumbers4, Serializable stanumbers5,
			Serializable stavalues1, Serializable stavalues2, Serializable stavalues3, Serializable stavalues4,
			Serializable stavalues5) {
		this.starelid = starelid;
		this.staattnum = staattnum;
		this.stainherit = stainherit;
		this.stanullfrac = stanullfrac;
		this.stawidth = stawidth;
		this.stadistinct = stadistinct;
		this.stakind1 = stakind1;
		this.stakind2 = stakind2;
		this.stakind3 = stakind3;
		this.stakind4 = stakind4;
		this.stakind5 = stakind5;
		this.staop1 = staop1;
		this.staop2 = staop2;
		this.staop3 = staop3;
		this.staop4 = staop4;
		this.staop5 = staop5;
		this.stanumbers1 = stanumbers1;
		this.stanumbers2 = stanumbers2;
		this.stanumbers3 = stanumbers3;
		this.stanumbers4 = stanumbers4;
		this.stanumbers5 = stanumbers5;
		this.stavalues1 = stavalues1;
		this.stavalues2 = stavalues2;
		this.stavalues3 = stavalues3;
		this.stavalues4 = stavalues4;
		this.stavalues5 = stavalues5;
	}

	@Column(name = "starelid", nullable = false)
	public int getStarelid() {
		return this.starelid;
	}

	public void setStarelid(int starelid) {
		this.starelid = starelid;
	}

	@Column(name = "staattnum", nullable = false)
	public short getStaattnum() {
		return this.staattnum;
	}

	public void setStaattnum(short staattnum) {
		this.staattnum = staattnum;
	}

	@Column(name = "stainherit", nullable = false)
	public boolean isStainherit() {
		return this.stainherit;
	}

	public void setStainherit(boolean stainherit) {
		this.stainherit = stainherit;
	}

	@Column(name = "stanullfrac", nullable = false, precision = 4, scale = 0)
	public float getStanullfrac() {
		return this.stanullfrac;
	}

	public void setStanullfrac(float stanullfrac) {
		this.stanullfrac = stanullfrac;
	}

	@Column(name = "stawidth", nullable = false)
	public int getStawidth() {
		return this.stawidth;
	}

	public void setStawidth(int stawidth) {
		this.stawidth = stawidth;
	}

	@Column(name = "stadistinct", nullable = false, precision = 4, scale = 0)
	public float getStadistinct() {
		return this.stadistinct;
	}

	public void setStadistinct(float stadistinct) {
		this.stadistinct = stadistinct;
	}

	@Column(name = "stakind1", nullable = false)
	public short getStakind1() {
		return this.stakind1;
	}

	public void setStakind1(short stakind1) {
		this.stakind1 = stakind1;
	}

	@Column(name = "stakind2", nullable = false)
	public short getStakind2() {
		return this.stakind2;
	}

	public void setStakind2(short stakind2) {
		this.stakind2 = stakind2;
	}

	@Column(name = "stakind3", nullable = false)
	public short getStakind3() {
		return this.stakind3;
	}

	public void setStakind3(short stakind3) {
		this.stakind3 = stakind3;
	}

	@Column(name = "stakind4", nullable = false)
	public short getStakind4() {
		return this.stakind4;
	}

	public void setStakind4(short stakind4) {
		this.stakind4 = stakind4;
	}

	@Column(name = "stakind5", nullable = false)
	public short getStakind5() {
		return this.stakind5;
	}

	public void setStakind5(short stakind5) {
		this.stakind5 = stakind5;
	}

	@Column(name = "staop1", nullable = false)
	public int getStaop1() {
		return this.staop1;
	}

	public void setStaop1(int staop1) {
		this.staop1 = staop1;
	}

	@Column(name = "staop2", nullable = false)
	public int getStaop2() {
		return this.staop2;
	}

	public void setStaop2(int staop2) {
		this.staop2 = staop2;
	}

	@Column(name = "staop3", nullable = false)
	public int getStaop3() {
		return this.staop3;
	}

	public void setStaop3(int staop3) {
		this.staop3 = staop3;
	}

	@Column(name = "staop4", nullable = false)
	public int getStaop4() {
		return this.staop4;
	}

	public void setStaop4(int staop4) {
		this.staop4 = staop4;
	}

	@Column(name = "staop5", nullable = false)
	public int getStaop5() {
		return this.staop5;
	}

	public void setStaop5(int staop5) {
		this.staop5 = staop5;
	}

	@Column(name = "stanumbers1")
	public Serializable getStanumbers1() {
		return this.stanumbers1;
	}

	public void setStanumbers1(Serializable stanumbers1) {
		this.stanumbers1 = stanumbers1;
	}

	@Column(name = "stanumbers2")
	public Serializable getStanumbers2() {
		return this.stanumbers2;
	}

	public void setStanumbers2(Serializable stanumbers2) {
		this.stanumbers2 = stanumbers2;
	}

	@Column(name = "stanumbers3")
	public Serializable getStanumbers3() {
		return this.stanumbers3;
	}

	public void setStanumbers3(Serializable stanumbers3) {
		this.stanumbers3 = stanumbers3;
	}

	@Column(name = "stanumbers4")
	public Serializable getStanumbers4() {
		return this.stanumbers4;
	}

	public void setStanumbers4(Serializable stanumbers4) {
		this.stanumbers4 = stanumbers4;
	}

	@Column(name = "stanumbers5")
	public Serializable getStanumbers5() {
		return this.stanumbers5;
	}

	public void setStanumbers5(Serializable stanumbers5) {
		this.stanumbers5 = stanumbers5;
	}

	@Column(name = "stavalues1")
	public Serializable getStavalues1() {
		return this.stavalues1;
	}

	public void setStavalues1(Serializable stavalues1) {
		this.stavalues1 = stavalues1;
	}

	@Column(name = "stavalues2")
	public Serializable getStavalues2() {
		return this.stavalues2;
	}

	public void setStavalues2(Serializable stavalues2) {
		this.stavalues2 = stavalues2;
	}

	@Column(name = "stavalues3")
	public Serializable getStavalues3() {
		return this.stavalues3;
	}

	public void setStavalues3(Serializable stavalues3) {
		this.stavalues3 = stavalues3;
	}

	@Column(name = "stavalues4")
	public Serializable getStavalues4() {
		return this.stavalues4;
	}

	public void setStavalues4(Serializable stavalues4) {
		this.stavalues4 = stavalues4;
	}

	@Column(name = "stavalues5")
	public Serializable getStavalues5() {
		return this.stavalues5;
	}

	public void setStavalues5(Serializable stavalues5) {
		this.stavalues5 = stavalues5;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgStatisticId))
			return false;
		PgStatisticId castOther = (PgStatisticId) other;

		return (this.getStarelid() == castOther.getStarelid()) && (this.getStaattnum() == castOther.getStaattnum())
				&& (this.isStainherit() == castOther.isStainherit())
				&& (this.getStanullfrac() == castOther.getStanullfrac())
				&& (this.getStawidth() == castOther.getStawidth())
				&& (this.getStadistinct() == castOther.getStadistinct())
				&& (this.getStakind1() == castOther.getStakind1()) && (this.getStakind2() == castOther.getStakind2())
				&& (this.getStakind3() == castOther.getStakind3()) && (this.getStakind4() == castOther.getStakind4())
				&& (this.getStakind5() == castOther.getStakind5()) && (this.getStaop1() == castOther.getStaop1())
				&& (this.getStaop2() == castOther.getStaop2()) && (this.getStaop3() == castOther.getStaop3())
				&& (this.getStaop4() == castOther.getStaop4()) && (this.getStaop5() == castOther.getStaop5())
				&& ((this.getStanumbers1() == castOther.getStanumbers1())
						|| (this.getStanumbers1() != null && castOther.getStanumbers1() != null
								&& this.getStanumbers1().equals(castOther.getStanumbers1())))
				&& ((this.getStanumbers2() == castOther.getStanumbers2())
						|| (this.getStanumbers2() != null && castOther.getStanumbers2() != null
								&& this.getStanumbers2().equals(castOther.getStanumbers2())))
				&& ((this.getStanumbers3() == castOther.getStanumbers3())
						|| (this.getStanumbers3() != null && castOther.getStanumbers3() != null
								&& this.getStanumbers3().equals(castOther.getStanumbers3())))
				&& ((this.getStanumbers4() == castOther.getStanumbers4())
						|| (this.getStanumbers4() != null && castOther.getStanumbers4() != null
								&& this.getStanumbers4().equals(castOther.getStanumbers4())))
				&& ((this.getStanumbers5() == castOther.getStanumbers5())
						|| (this.getStanumbers5() != null && castOther.getStanumbers5() != null
								&& this.getStanumbers5().equals(castOther.getStanumbers5())))
				&& ((this.getStavalues1() == castOther.getStavalues1()) || (this.getStavalues1() != null
						&& castOther.getStavalues1() != null && this.getStavalues1().equals(castOther.getStavalues1())))
				&& ((this.getStavalues2() == castOther.getStavalues2()) || (this.getStavalues2() != null
						&& castOther.getStavalues2() != null && this.getStavalues2().equals(castOther.getStavalues2())))
				&& ((this.getStavalues3() == castOther.getStavalues3()) || (this.getStavalues3() != null
						&& castOther.getStavalues3() != null && this.getStavalues3().equals(castOther.getStavalues3())))
				&& ((this.getStavalues4() == castOther.getStavalues4()) || (this.getStavalues4() != null
						&& castOther.getStavalues4() != null && this.getStavalues4().equals(castOther.getStavalues4())))
				&& ((this.getStavalues5() == castOther.getStavalues5())
						|| (this.getStavalues5() != null && castOther.getStavalues5() != null
								&& this.getStavalues5().equals(castOther.getStavalues5())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStarelid();
		result = 37 * result + this.getStaattnum();
		result = 37 * result + (this.isStainherit() ? 1 : 0);
		result = 37 * result + (int) this.getStanullfrac();
		result = 37 * result + this.getStawidth();
		result = 37 * result + (int) this.getStadistinct();
		result = 37 * result + this.getStakind1();
		result = 37 * result + this.getStakind2();
		result = 37 * result + this.getStakind3();
		result = 37 * result + this.getStakind4();
		result = 37 * result + this.getStakind5();
		result = 37 * result + this.getStaop1();
		result = 37 * result + this.getStaop2();
		result = 37 * result + this.getStaop3();
		result = 37 * result + this.getStaop4();
		result = 37 * result + this.getStaop5();
		result = 37 * result + (getStanumbers1() == null ? 0 : this.getStanumbers1().hashCode());
		result = 37 * result + (getStanumbers2() == null ? 0 : this.getStanumbers2().hashCode());
		result = 37 * result + (getStanumbers3() == null ? 0 : this.getStanumbers3().hashCode());
		result = 37 * result + (getStanumbers4() == null ? 0 : this.getStanumbers4().hashCode());
		result = 37 * result + (getStanumbers5() == null ? 0 : this.getStanumbers5().hashCode());
		result = 37 * result + (getStavalues1() == null ? 0 : this.getStavalues1().hashCode());
		result = 37 * result + (getStavalues2() == null ? 0 : this.getStavalues2().hashCode());
		result = 37 * result + (getStavalues3() == null ? 0 : this.getStavalues3().hashCode());
		result = 37 * result + (getStavalues4() == null ? 0 : this.getStavalues4().hashCode());
		result = 37 * result + (getStavalues5() == null ? 0 : this.getStavalues5().hashCode());
		return result;
	}

}
