package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgStatistic generated by hbm2java
 */
@Entity
@Table(name = "pg_statistic", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = { "starelid",
		"staattnum", "stainherit" }))
public class PgStatistic implements java.io.Serializable {

	private PgStatisticId id;

	public PgStatistic() {
	}

	public PgStatistic(PgStatisticId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "starelid", column = @Column(name = "starelid", nullable = false)),
			@AttributeOverride(name = "staattnum", column = @Column(name = "staattnum", nullable = false)),
			@AttributeOverride(name = "stainherit", column = @Column(name = "stainherit", nullable = false)),
			@AttributeOverride(name = "stanullfrac", column = @Column(name = "stanullfrac", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "stawidth", column = @Column(name = "stawidth", nullable = false)),
			@AttributeOverride(name = "stadistinct", column = @Column(name = "stadistinct", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "stakind1", column = @Column(name = "stakind1", nullable = false)),
			@AttributeOverride(name = "stakind2", column = @Column(name = "stakind2", nullable = false)),
			@AttributeOverride(name = "stakind3", column = @Column(name = "stakind3", nullable = false)),
			@AttributeOverride(name = "stakind4", column = @Column(name = "stakind4", nullable = false)),
			@AttributeOverride(name = "stakind5", column = @Column(name = "stakind5", nullable = false)),
			@AttributeOverride(name = "staop1", column = @Column(name = "staop1", nullable = false)),
			@AttributeOverride(name = "staop2", column = @Column(name = "staop2", nullable = false)),
			@AttributeOverride(name = "staop3", column = @Column(name = "staop3", nullable = false)),
			@AttributeOverride(name = "staop4", column = @Column(name = "staop4", nullable = false)),
			@AttributeOverride(name = "staop5", column = @Column(name = "staop5", nullable = false)),
			@AttributeOverride(name = "stanumbers1", column = @Column(name = "stanumbers1")),
			@AttributeOverride(name = "stanumbers2", column = @Column(name = "stanumbers2")),
			@AttributeOverride(name = "stanumbers3", column = @Column(name = "stanumbers3")),
			@AttributeOverride(name = "stanumbers4", column = @Column(name = "stanumbers4")),
			@AttributeOverride(name = "stanumbers5", column = @Column(name = "stanumbers5")),
			@AttributeOverride(name = "stavalues1", column = @Column(name = "stavalues1")),
			@AttributeOverride(name = "stavalues2", column = @Column(name = "stavalues2")),
			@AttributeOverride(name = "stavalues3", column = @Column(name = "stavalues3")),
			@AttributeOverride(name = "stavalues4", column = @Column(name = "stavalues4")),
			@AttributeOverride(name = "stavalues5", column = @Column(name = "stavalues5")) })
	public PgStatisticId getId() {
		return this.id;
	}

	public void setId(PgStatisticId id) {
		this.id = id;
	}

}
