package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgTablespace generated by hbm2java
 */
@Entity
@Table(name = "pg_tablespace", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = "spcname") })
public class PgTablespace implements java.io.Serializable {

	private PgTablespaceId id;

	public PgTablespace() {
	}

	public PgTablespace(PgTablespaceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "spcname", column = @Column(name = "spcname", unique = true, nullable = false, length = 64)),
			@AttributeOverride(name = "spcowner", column = @Column(name = "spcowner", nullable = false)),
			@AttributeOverride(name = "spcacl", column = @Column(name = "spcacl")),
			@AttributeOverride(name = "spcoptions", column = @Column(name = "spcoptions")) })
	public PgTablespaceId getId() {
		return this.id;
	}

	public void setId(PgTablespaceId id) {
		this.id = id;
	}

}
