package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgTablespaceId generated by hbm2java
 */
@Embeddable
public class PgTablespaceId implements java.io.Serializable {

	private String spcname;
	private int spcowner;
	private Serializable spcacl;
	private Serializable spcoptions;

	public PgTablespaceId() {
	}

	public PgTablespaceId(String spcname, int spcowner) {
		this.spcname = spcname;
		this.spcowner = spcowner;
	}

	public PgTablespaceId(String spcname, int spcowner, Serializable spcacl, Serializable spcoptions) {
		this.spcname = spcname;
		this.spcowner = spcowner;
		this.spcacl = spcacl;
		this.spcoptions = spcoptions;
	}

	@Column(name = "spcname", unique = true, nullable = false, length = 64)
	public String getSpcname() {
		return this.spcname;
	}

	public void setSpcname(String spcname) {
		this.spcname = spcname;
	}

	@Column(name = "spcowner", nullable = false)
	public int getSpcowner() {
		return this.spcowner;
	}

	public void setSpcowner(int spcowner) {
		this.spcowner = spcowner;
	}

	@Column(name = "spcacl")
	public Serializable getSpcacl() {
		return this.spcacl;
	}

	public void setSpcacl(Serializable spcacl) {
		this.spcacl = spcacl;
	}

	@Column(name = "spcoptions")
	public Serializable getSpcoptions() {
		return this.spcoptions;
	}

	public void setSpcoptions(Serializable spcoptions) {
		this.spcoptions = spcoptions;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgTablespaceId))
			return false;
		PgTablespaceId castOther = (PgTablespaceId) other;

		return ((this.getSpcname() == castOther.getSpcname()) || (this.getSpcname() != null
				&& castOther.getSpcname() != null && this.getSpcname().equals(castOther.getSpcname())))
				&& (this.getSpcowner() == castOther.getSpcowner())
				&& ((this.getSpcacl() == castOther.getSpcacl()) || (this.getSpcacl() != null
						&& castOther.getSpcacl() != null && this.getSpcacl().equals(castOther.getSpcacl())))
				&& ((this.getSpcoptions() == castOther.getSpcoptions())
						|| (this.getSpcoptions() != null && castOther.getSpcoptions() != null
								&& this.getSpcoptions().equals(castOther.getSpcoptions())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSpcname() == null ? 0 : this.getSpcname().hashCode());
		result = 37 * result + this.getSpcowner();
		result = 37 * result + (getSpcacl() == null ? 0 : this.getSpcacl().hashCode());
		result = 37 * result + (getSpcoptions() == null ? 0 : this.getSpcoptions().hashCode());
		return result;
	}

}
