package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgTrigger generated by hbm2java
 */
@Entity
@Table(name = "pg_trigger", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "tgrelid", "tgname" }) })
public class PgTrigger implements java.io.Serializable {

	private PgTriggerId id;

	public PgTrigger() {
	}

	public PgTrigger(PgTriggerId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "tgrelid", column = @Column(name = "tgrelid", nullable = false)),
			@AttributeOverride(name = "tgname", column = @Column(name = "tgname", nullable = false, length = 64)),
			@AttributeOverride(name = "tgfoid", column = @Column(name = "tgfoid", nullable = false)),
			@AttributeOverride(name = "tgtype", column = @Column(name = "tgtype", nullable = false)),
			@AttributeOverride(name = "tgenabled", column = @Column(name = "tgenabled", nullable = false)),
			@AttributeOverride(name = "tgisinternal", column = @Column(name = "tgisinternal", nullable = false)),
			@AttributeOverride(name = "tgconstrrelid", column = @Column(name = "tgconstrrelid", nullable = false)),
			@AttributeOverride(name = "tgconstrindid", column = @Column(name = "tgconstrindid", nullable = false)),
			@AttributeOverride(name = "tgconstraint", column = @Column(name = "tgconstraint", nullable = false)),
			@AttributeOverride(name = "tgdeferrable", column = @Column(name = "tgdeferrable", nullable = false)),
			@AttributeOverride(name = "tginitdeferred", column = @Column(name = "tginitdeferred", nullable = false)),
			@AttributeOverride(name = "tgnargs", column = @Column(name = "tgnargs", nullable = false)),
			@AttributeOverride(name = "tgattr", column = @Column(name = "tgattr", nullable = false)),
			@AttributeOverride(name = "tgargs", column = @Column(name = "tgargs", nullable = false)),
			@AttributeOverride(name = "tgqual", column = @Column(name = "tgqual")) })
	public PgTriggerId getId() {
		return this.id;
	}

	public void setId(PgTriggerId id) {
		this.id = id;
	}

}
