package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgTransform generated by hbm2java
 */
@Entity
@Table(name = "pg_transform", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "trftype", "trflang" }) })
public class PgTransform implements java.io.Serializable {

	private PgTransformId id;

	public PgTransform() {
	}

	public PgTransform(PgTransformId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "trftype", column = @Column(name = "trftype", nullable = false)),
			@AttributeOverride(name = "trflang", column = @Column(name = "trflang", nullable = false)),
			@AttributeOverride(name = "trffromsql", column = @Column(name = "trffromsql", nullable = false)),
			@AttributeOverride(name = "trftosql", column = @Column(name = "trftosql", nullable = false)) })
	public PgTransformId getId() {
		return this.id;
	}

	public void setId(PgTransformId id) {
		this.id = id;
	}

}
