package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgTriggerId generated by hbm2java
 */
@Embeddable
public class PgTriggerId implements java.io.Serializable {

	private int tgrelid;
	private String tgname;
	private int tgfoid;
	private short tgtype;
	private Serializable tgenabled;
	private boolean tgisinternal;
	private int tgconstrrelid;
	private int tgconstrindid;
	private int tgconstraint;
	private boolean tgdeferrable;
	private boolean tginitdeferred;
	private short tgnargs;
	private Serializable tgattr;
	private byte[] tgargs;
	private Serializable tgqual;

	public PgTriggerId() {
	}

	public PgTriggerId(int tgrelid, String tgname, int tgfoid, short tgtype, Serializable tgenabled,
			boolean tgisinternal, int tgconstrrelid, int tgconstrindid, int tgconstraint, boolean tgdeferrable,
			boolean tginitdeferred, short tgnargs, Serializable tgattr, byte[] tgargs) {
		this.tgrelid = tgrelid;
		this.tgname = tgname;
		this.tgfoid = tgfoid;
		this.tgtype = tgtype;
		this.tgenabled = tgenabled;
		this.tgisinternal = tgisinternal;
		this.tgconstrrelid = tgconstrrelid;
		this.tgconstrindid = tgconstrindid;
		this.tgconstraint = tgconstraint;
		this.tgdeferrable = tgdeferrable;
		this.tginitdeferred = tginitdeferred;
		this.tgnargs = tgnargs;
		this.tgattr = tgattr;
		this.tgargs = tgargs;
	}

	public PgTriggerId(int tgrelid, String tgname, int tgfoid, short tgtype, Serializable tgenabled,
			boolean tgisinternal, int tgconstrrelid, int tgconstrindid, int tgconstraint, boolean tgdeferrable,
			boolean tginitdeferred, short tgnargs, Serializable tgattr, byte[] tgargs, Serializable tgqual) {
		this.tgrelid = tgrelid;
		this.tgname = tgname;
		this.tgfoid = tgfoid;
		this.tgtype = tgtype;
		this.tgenabled = tgenabled;
		this.tgisinternal = tgisinternal;
		this.tgconstrrelid = tgconstrrelid;
		this.tgconstrindid = tgconstrindid;
		this.tgconstraint = tgconstraint;
		this.tgdeferrable = tgdeferrable;
		this.tginitdeferred = tginitdeferred;
		this.tgnargs = tgnargs;
		this.tgattr = tgattr;
		this.tgargs = tgargs;
		this.tgqual = tgqual;
	}

	@Column(name = "tgrelid", nullable = false)
	public int getTgrelid() {
		return this.tgrelid;
	}

	public void setTgrelid(int tgrelid) {
		this.tgrelid = tgrelid;
	}

	@Column(name = "tgname", nullable = false, length = 64)
	public String getTgname() {
		return this.tgname;
	}

	public void setTgname(String tgname) {
		this.tgname = tgname;
	}

	@Column(name = "tgfoid", nullable = false)
	public int getTgfoid() {
		return this.tgfoid;
	}

	public void setTgfoid(int tgfoid) {
		this.tgfoid = tgfoid;
	}

	@Column(name = "tgtype", nullable = false)
	public short getTgtype() {
		return this.tgtype;
	}

	public void setTgtype(short tgtype) {
		this.tgtype = tgtype;
	}

	@Column(name = "tgenabled", nullable = false)
	public Serializable getTgenabled() {
		return this.tgenabled;
	}

	public void setTgenabled(Serializable tgenabled) {
		this.tgenabled = tgenabled;
	}

	@Column(name = "tgisinternal", nullable = false)
	public boolean isTgisinternal() {
		return this.tgisinternal;
	}

	public void setTgisinternal(boolean tgisinternal) {
		this.tgisinternal = tgisinternal;
	}

	@Column(name = "tgconstrrelid", nullable = false)
	public int getTgconstrrelid() {
		return this.tgconstrrelid;
	}

	public void setTgconstrrelid(int tgconstrrelid) {
		this.tgconstrrelid = tgconstrrelid;
	}

	@Column(name = "tgconstrindid", nullable = false)
	public int getTgconstrindid() {
		return this.tgconstrindid;
	}

	public void setTgconstrindid(int tgconstrindid) {
		this.tgconstrindid = tgconstrindid;
	}

	@Column(name = "tgconstraint", nullable = false)
	public int getTgconstraint() {
		return this.tgconstraint;
	}

	public void setTgconstraint(int tgconstraint) {
		this.tgconstraint = tgconstraint;
	}

	@Column(name = "tgdeferrable", nullable = false)
	public boolean isTgdeferrable() {
		return this.tgdeferrable;
	}

	public void setTgdeferrable(boolean tgdeferrable) {
		this.tgdeferrable = tgdeferrable;
	}

	@Column(name = "tginitdeferred", nullable = false)
	public boolean isTginitdeferred() {
		return this.tginitdeferred;
	}

	public void setTginitdeferred(boolean tginitdeferred) {
		this.tginitdeferred = tginitdeferred;
	}

	@Column(name = "tgnargs", nullable = false)
	public short getTgnargs() {
		return this.tgnargs;
	}

	public void setTgnargs(short tgnargs) {
		this.tgnargs = tgnargs;
	}

	@Column(name = "tgattr", nullable = false)
	public Serializable getTgattr() {
		return this.tgattr;
	}

	public void setTgattr(Serializable tgattr) {
		this.tgattr = tgattr;
	}

	@Column(name = "tgargs", nullable = false)
	public byte[] getTgargs() {
		return this.tgargs;
	}

	public void setTgargs(byte[] tgargs) {
		this.tgargs = tgargs;
	}

	@Column(name = "tgqual")
	public Serializable getTgqual() {
		return this.tgqual;
	}

	public void setTgqual(Serializable tgqual) {
		this.tgqual = tgqual;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgTriggerId))
			return false;
		PgTriggerId castOther = (PgTriggerId) other;

		return (this.getTgrelid() == castOther.getTgrelid())
				&& ((this.getTgname() == castOther.getTgname()) || (this.getTgname() != null
						&& castOther.getTgname() != null && this.getTgname().equals(castOther.getTgname())))
				&& (this.getTgfoid() == castOther.getTgfoid()) && (this.getTgtype() == castOther.getTgtype())
				&& ((this.getTgenabled() == castOther.getTgenabled()) || (this.getTgenabled() != null
						&& castOther.getTgenabled() != null && this.getTgenabled().equals(castOther.getTgenabled())))
				&& (this.isTgisinternal() == castOther.isTgisinternal())
				&& (this.getTgconstrrelid() == castOther.getTgconstrrelid())
				&& (this.getTgconstrindid() == castOther.getTgconstrindid())
				&& (this.getTgconstraint() == castOther.getTgconstraint())
				&& (this.isTgdeferrable() == castOther.isTgdeferrable())
				&& (this.isTginitdeferred() == castOther.isTginitdeferred())
				&& (this.getTgnargs() == castOther.getTgnargs())
				&& ((this.getTgattr() == castOther.getTgattr()) || (this.getTgattr() != null
						&& castOther.getTgattr() != null && this.getTgattr().equals(castOther.getTgattr())))
				&& ((this.getTgargs() == castOther.getTgargs()) || (this.getTgargs() != null
						&& castOther.getTgargs() != null && Arrays.equals(this.getTgargs(), castOther.getTgargs())))
				&& ((this.getTgqual() == castOther.getTgqual()) || (this.getTgqual() != null
						&& castOther.getTgqual() != null && this.getTgqual().equals(castOther.getTgqual())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTgrelid();
		result = 37 * result + (getTgname() == null ? 0 : this.getTgname().hashCode());
		result = 37 * result + this.getTgfoid();
		result = 37 * result + this.getTgtype();
		result = 37 * result + (getTgenabled() == null ? 0 : this.getTgenabled().hashCode());
		result = 37 * result + (this.isTgisinternal() ? 1 : 0);
		result = 37 * result + this.getTgconstrrelid();
		result = 37 * result + this.getTgconstrindid();
		result = 37 * result + this.getTgconstraint();
		result = 37 * result + (this.isTgdeferrable() ? 1 : 0);
		result = 37 * result + (this.isTginitdeferred() ? 1 : 0);
		result = 37 * result + this.getTgnargs();
		result = 37 * result + (getTgattr() == null ? 0 : this.getTgattr().hashCode());
		int tgargsHashcode = 0;
		byte[] tgargsProperty = this.getTgargs();
		if (tgargsProperty != null) {
			tgargsHashcode = 1;
			for (int i = 0; i < tgargsProperty.length; i++) {
				tgargsHashcode = 37 * tgargsHashcode + tgargsProperty[i];
			}
		}

		result = 37 * result + tgargsHashcode;

		result = 37 * result + (getTgqual() == null ? 0 : this.getTgqual().hashCode());
		return result;
	}

}
