package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgTransformId generated by hbm2java
 */
@Embeddable
public class PgTransformId implements java.io.Serializable {

	private int trftype;
	private int trflang;
	private Serializable trffromsql;
	private Serializable trftosql;

	public PgTransformId() {
	}

	public PgTransformId(int trftype, int trflang, Serializable trffromsql, Serializable trftosql) {
		this.trftype = trftype;
		this.trflang = trflang;
		this.trffromsql = trffromsql;
		this.trftosql = trftosql;
	}

	@Column(name = "trftype", nullable = false)
	public int getTrftype() {
		return this.trftype;
	}

	public void setTrftype(int trftype) {
		this.trftype = trftype;
	}

	@Column(name = "trflang", nullable = false)
	public int getTrflang() {
		return this.trflang;
	}

	public void setTrflang(int trflang) {
		this.trflang = trflang;
	}

	@Column(name = "trffromsql", nullable = false)
	public Serializable getTrffromsql() {
		return this.trffromsql;
	}

	public void setTrffromsql(Serializable trffromsql) {
		this.trffromsql = trffromsql;
	}

	@Column(name = "trftosql", nullable = false)
	public Serializable getTrftosql() {
		return this.trftosql;
	}

	public void setTrftosql(Serializable trftosql) {
		this.trftosql = trftosql;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgTransformId))
			return false;
		PgTransformId castOther = (PgTransformId) other;

		return (this.getTrftype() == castOther.getTrftype()) && (this.getTrflang() == castOther.getTrflang())
				&& ((this.getTrffromsql() == castOther.getTrffromsql()) || (this.getTrffromsql() != null
						&& castOther.getTrffromsql() != null && this.getTrffromsql().equals(castOther.getTrffromsql())))
				&& ((this.getTrftosql() == castOther.getTrftosql()) || (this.getTrftosql() != null
						&& castOther.getTrftosql() != null && this.getTrftosql().equals(castOther.getTrftosql())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTrftype();
		result = 37 * result + this.getTrflang();
		result = 37 * result + (getTrffromsql() == null ? 0 : this.getTrffromsql().hashCode());
		result = 37 * result + (getTrftosql() == null ? 0 : this.getTrftosql().hashCode());
		return result;
	}

}
