package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgTsParserId generated by hbm2java
 */
@Embeddable
public class PgTsParserId implements java.io.Serializable {

	private String prsname;
	private int prsnamespace;
	private Serializable prsstart;
	private Serializable prstoken;
	private Serializable prsend;
	private Serializable prsheadline;
	private Serializable prslextype;

	public PgTsParserId() {
	}

	public PgTsParserId(String prsname, int prsnamespace, Serializable prsstart, Serializable prstoken,
			Serializable prsend, Serializable prsheadline, Serializable prslextype) {
		this.prsname = prsname;
		this.prsnamespace = prsnamespace;
		this.prsstart = prsstart;
		this.prstoken = prstoken;
		this.prsend = prsend;
		this.prsheadline = prsheadline;
		this.prslextype = prslextype;
	}

	@Column(name = "prsname", nullable = false, length = 64)
	public String getPrsname() {
		return this.prsname;
	}

	public void setPrsname(String prsname) {
		this.prsname = prsname;
	}

	@Column(name = "prsnamespace", nullable = false)
	public int getPrsnamespace() {
		return this.prsnamespace;
	}

	public void setPrsnamespace(int prsnamespace) {
		this.prsnamespace = prsnamespace;
	}

	@Column(name = "prsstart", nullable = false)
	public Serializable getPrsstart() {
		return this.prsstart;
	}

	public void setPrsstart(Serializable prsstart) {
		this.prsstart = prsstart;
	}

	@Column(name = "prstoken", nullable = false)
	public Serializable getPrstoken() {
		return this.prstoken;
	}

	public void setPrstoken(Serializable prstoken) {
		this.prstoken = prstoken;
	}

	@Column(name = "prsend", nullable = false)
	public Serializable getPrsend() {
		return this.prsend;
	}

	public void setPrsend(Serializable prsend) {
		this.prsend = prsend;
	}

	@Column(name = "prsheadline", nullable = false)
	public Serializable getPrsheadline() {
		return this.prsheadline;
	}

	public void setPrsheadline(Serializable prsheadline) {
		this.prsheadline = prsheadline;
	}

	@Column(name = "prslextype", nullable = false)
	public Serializable getPrslextype() {
		return this.prslextype;
	}

	public void setPrslextype(Serializable prslextype) {
		this.prslextype = prslextype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgTsParserId))
			return false;
		PgTsParserId castOther = (PgTsParserId) other;

		return ((this.getPrsname() == castOther.getPrsname()) || (this.getPrsname() != null
				&& castOther.getPrsname() != null && this.getPrsname().equals(castOther.getPrsname())))
				&& (this.getPrsnamespace() == castOther.getPrsnamespace())
				&& ((this.getPrsstart() == castOther.getPrsstart()) || (this.getPrsstart() != null
						&& castOther.getPrsstart() != null && this.getPrsstart().equals(castOther.getPrsstart())))
				&& ((this.getPrstoken() == castOther.getPrstoken()) || (this.getPrstoken() != null
						&& castOther.getPrstoken() != null && this.getPrstoken().equals(castOther.getPrstoken())))
				&& ((this.getPrsend() == castOther.getPrsend()) || (this.getPrsend() != null
						&& castOther.getPrsend() != null && this.getPrsend().equals(castOther.getPrsend())))
				&& ((this.getPrsheadline() == castOther.getPrsheadline())
						|| (this.getPrsheadline() != null && castOther.getPrsheadline() != null
								&& this.getPrsheadline().equals(castOther.getPrsheadline())))
				&& ((this.getPrslextype() == castOther.getPrslextype())
						|| (this.getPrslextype() != null && castOther.getPrslextype() != null
								&& this.getPrslextype().equals(castOther.getPrslextype())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPrsname() == null ? 0 : this.getPrsname().hashCode());
		result = 37 * result + this.getPrsnamespace();
		result = 37 * result + (getPrsstart() == null ? 0 : this.getPrsstart().hashCode());
		result = 37 * result + (getPrstoken() == null ? 0 : this.getPrstoken().hashCode());
		result = 37 * result + (getPrsend() == null ? 0 : this.getPrsend().hashCode());
		result = 37 * result + (getPrsheadline() == null ? 0 : this.getPrsheadline().hashCode());
		result = 37 * result + (getPrslextype() == null ? 0 : this.getPrslextype().hashCode());
		return result;
	}

}
