package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgTsConfigMapId generated by hbm2java
 */
@Embeddable
public class PgTsConfigMapId implements java.io.Serializable {

	private int mapcfg;
	private int maptokentype;
	private int mapseqno;
	private int mapdict;

	public PgTsConfigMapId() {
	}

	public PgTsConfigMapId(int mapcfg, int maptokentype, int mapseqno, int mapdict) {
		this.mapcfg = mapcfg;
		this.maptokentype = maptokentype;
		this.mapseqno = mapseqno;
		this.mapdict = mapdict;
	}

	@Column(name = "mapcfg", nullable = false)
	public int getMapcfg() {
		return this.mapcfg;
	}

	public void setMapcfg(int mapcfg) {
		this.mapcfg = mapcfg;
	}

	@Column(name = "maptokentype", nullable = false)
	public int getMaptokentype() {
		return this.maptokentype;
	}

	public void setMaptokentype(int maptokentype) {
		this.maptokentype = maptokentype;
	}

	@Column(name = "mapseqno", nullable = false)
	public int getMapseqno() {
		return this.mapseqno;
	}

	public void setMapseqno(int mapseqno) {
		this.mapseqno = mapseqno;
	}

	@Column(name = "mapdict", nullable = false)
	public int getMapdict() {
		return this.mapdict;
	}

	public void setMapdict(int mapdict) {
		this.mapdict = mapdict;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgTsConfigMapId))
			return false;
		PgTsConfigMapId castOther = (PgTsConfigMapId) other;

		return (this.getMapcfg() == castOther.getMapcfg()) && (this.getMaptokentype() == castOther.getMaptokentype())
				&& (this.getMapseqno() == castOther.getMapseqno()) && (this.getMapdict() == castOther.getMapdict());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMapcfg();
		result = 37 * result + this.getMaptokentype();
		result = 37 * result + this.getMapseqno();
		result = 37 * result + this.getMapdict();
		return result;
	}

}
