package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgTsConfigMap generated by hbm2java
 */
@Entity
@Table(name = "pg_ts_config_map", schema = "pg_catalog", uniqueConstraints = @UniqueConstraint(columnNames = { "mapcfg",
		"maptokentype", "mapseqno" }))
public class PgTsConfigMap implements java.io.Serializable {

	private PgTsConfigMapId id;

	public PgTsConfigMap() {
	}

	public PgTsConfigMap(PgTsConfigMapId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "mapcfg", column = @Column(name = "mapcfg", nullable = false)),
			@AttributeOverride(name = "maptokentype", column = @Column(name = "maptokentype", nullable = false)),
			@AttributeOverride(name = "mapseqno", column = @Column(name = "mapseqno", nullable = false)),
			@AttributeOverride(name = "mapdict", column = @Column(name = "mapdict", nullable = false)) })
	public PgTsConfigMapId getId() {
		return this.id;
	}

	public void setId(PgTsConfigMapId id) {
		this.id = id;
	}

}
