package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgTsTemplateId generated by hbm2java
 */
@Embeddable
public class PgTsTemplateId implements java.io.Serializable {

	private String tmplname;
	private int tmplnamespace;
	private Serializable tmplinit;
	private Serializable tmpllexize;

	public PgTsTemplateId() {
	}

	public PgTsTemplateId(String tmplname, int tmplnamespace, Serializable tmplinit, Serializable tmpllexize) {
		this.tmplname = tmplname;
		this.tmplnamespace = tmplnamespace;
		this.tmplinit = tmplinit;
		this.tmpllexize = tmpllexize;
	}

	@Column(name = "tmplname", nullable = false, length = 64)
	public String getTmplname() {
		return this.tmplname;
	}

	public void setTmplname(String tmplname) {
		this.tmplname = tmplname;
	}

	@Column(name = "tmplnamespace", nullable = false)
	public int getTmplnamespace() {
		return this.tmplnamespace;
	}

	public void setTmplnamespace(int tmplnamespace) {
		this.tmplnamespace = tmplnamespace;
	}

	@Column(name = "tmplinit", nullable = false)
	public Serializable getTmplinit() {
		return this.tmplinit;
	}

	public void setTmplinit(Serializable tmplinit) {
		this.tmplinit = tmplinit;
	}

	@Column(name = "tmpllexize", nullable = false)
	public Serializable getTmpllexize() {
		return this.tmpllexize;
	}

	public void setTmpllexize(Serializable tmpllexize) {
		this.tmpllexize = tmpllexize;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgTsTemplateId))
			return false;
		PgTsTemplateId castOther = (PgTsTemplateId) other;

		return ((this.getTmplname() == castOther.getTmplname()) || (this.getTmplname() != null
				&& castOther.getTmplname() != null && this.getTmplname().equals(castOther.getTmplname())))
				&& (this.getTmplnamespace() == castOther.getTmplnamespace())
				&& ((this.getTmplinit() == castOther.getTmplinit()) || (this.getTmplinit() != null
						&& castOther.getTmplinit() != null && this.getTmplinit().equals(castOther.getTmplinit())))
				&& ((this.getTmpllexize() == castOther.getTmpllexize())
						|| (this.getTmpllexize() != null && castOther.getTmpllexize() != null
								&& this.getTmpllexize().equals(castOther.getTmpllexize())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTmplname() == null ? 0 : this.getTmplname().hashCode());
		result = 37 * result + this.getTmplnamespace();
		result = 37 * result + (getTmplinit() == null ? 0 : this.getTmplinit().hashCode());
		result = 37 * result + (getTmpllexize() == null ? 0 : this.getTmpllexize().hashCode());
		return result;
	}

}
