package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgTsParser generated by hbm2java
 */
@Entity
@Table(name = "pg_ts_parser", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "prsname", "prsnamespace" }) })
public class PgTsParser implements java.io.Serializable {

	private PgTsParserId id;

	public PgTsParser() {
	}

	public PgTsParser(PgTsParserId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "prsname", column = @Column(name = "prsname", nullable = false, length = 64)),
			@AttributeOverride(name = "prsnamespace", column = @Column(name = "prsnamespace", nullable = false)),
			@AttributeOverride(name = "prsstart", column = @Column(name = "prsstart", nullable = false)),
			@AttributeOverride(name = "prstoken", column = @Column(name = "prstoken", nullable = false)),
			@AttributeOverride(name = "prsend", column = @Column(name = "prsend", nullable = false)),
			@AttributeOverride(name = "prsheadline", column = @Column(name = "prsheadline", nullable = false)),
			@AttributeOverride(name = "prslextype", column = @Column(name = "prslextype", nullable = false)) })
	public PgTsParserId getId() {
		return this.id;
	}

	public void setId(PgTsParserId id) {
		this.id = id;
	}

}
