package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgTsTemplate generated by hbm2java
 */
@Entity
@Table(name = "pg_ts_template", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "tmplname", "tmplnamespace" }) })
public class PgTsTemplate implements java.io.Serializable {

	private PgTsTemplateId id;

	public PgTsTemplate() {
	}

	public PgTsTemplate(PgTsTemplateId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tmplname", column = @Column(name = "tmplname", nullable = false, length = 64)),
			@AttributeOverride(name = "tmplnamespace", column = @Column(name = "tmplnamespace", nullable = false)),
			@AttributeOverride(name = "tmplinit", column = @Column(name = "tmplinit", nullable = false)),
			@AttributeOverride(name = "tmpllexize", column = @Column(name = "tmpllexize", nullable = false)) })
	public PgTsTemplateId getId() {
		return this.id;
	}

	public void setId(PgTsTemplateId id) {
		this.id = id;
	}

}
