package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgTsDict generated by hbm2java
 */
@Entity
@Table(name = "pg_ts_dict", schema = "pg_catalog", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "dictname", "dictnamespace" }), @UniqueConstraint(columnNames = "oid") })
public class PgTsDict implements java.io.Serializable {

	private PgTsDictId id;

	public PgTsDict() {
	}

	public PgTsDict(PgTsDictId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dictname", column = @Column(name = "dictname", nullable = false, length = 64)),
			@AttributeOverride(name = "dictnamespace", column = @Column(name = "dictnamespace", nullable = false)),
			@AttributeOverride(name = "dictowner", column = @Column(name = "dictowner", nullable = false)),
			@AttributeOverride(name = "dicttemplate", column = @Column(name = "dicttemplate", nullable = false)),
			@AttributeOverride(name = "dictinitoption", column = @Column(name = "dictinitoption")) })
	public PgTsDictId getId() {
		return this.id;
	}

	public void setId(PgTsDictId id) {
		this.id = id;
	}

}
