package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgTsConfigId generated by hbm2java
 */
@Embeddable
public class PgTsConfigId implements java.io.Serializable {

	private String cfgname;
	private int cfgnamespace;
	private int cfgowner;
	private int cfgparser;

	public PgTsConfigId() {
	}

	public PgTsConfigId(String cfgname, int cfgnamespace, int cfgowner, int cfgparser) {
		this.cfgname = cfgname;
		this.cfgnamespace = cfgnamespace;
		this.cfgowner = cfgowner;
		this.cfgparser = cfgparser;
	}

	@Column(name = "cfgname", nullable = false, length = 64)
	public String getCfgname() {
		return this.cfgname;
	}

	public void setCfgname(String cfgname) {
		this.cfgname = cfgname;
	}

	@Column(name = "cfgnamespace", nullable = false)
	public int getCfgnamespace() {
		return this.cfgnamespace;
	}

	public void setCfgnamespace(int cfgnamespace) {
		this.cfgnamespace = cfgnamespace;
	}

	@Column(name = "cfgowner", nullable = false)
	public int getCfgowner() {
		return this.cfgowner;
	}

	public void setCfgowner(int cfgowner) {
		this.cfgowner = cfgowner;
	}

	@Column(name = "cfgparser", nullable = false)
	public int getCfgparser() {
		return this.cfgparser;
	}

	public void setCfgparser(int cfgparser) {
		this.cfgparser = cfgparser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgTsConfigId))
			return false;
		PgTsConfigId castOther = (PgTsConfigId) other;

		return ((this.getCfgname() == castOther.getCfgname()) || (this.getCfgname() != null
				&& castOther.getCfgname() != null && this.getCfgname().equals(castOther.getCfgname())))
				&& (this.getCfgnamespace() == castOther.getCfgnamespace())
				&& (this.getCfgowner() == castOther.getCfgowner()) && (this.getCfgparser() == castOther.getCfgparser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCfgname() == null ? 0 : this.getCfgname().hashCode());
		result = 37 * result + this.getCfgnamespace();
		result = 37 * result + this.getCfgowner();
		result = 37 * result + this.getCfgparser();
		return result;
	}

}
