package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PgTypeId generated by hbm2java
 */
@Embeddable
public class PgTypeId implements java.io.Serializable {

	private String typname;
	private int typnamespace;
	private int typowner;
	private short typlen;
	private boolean typbyval;
	private Serializable typtype;
	private Serializable typcategory;
	private boolean typispreferred;
	private boolean typisdefined;
	private Serializable typdelim;
	private int typrelid;
	private int typelem;
	private int typarray;
	private Serializable typinput;
	private Serializable typoutput;
	private Serializable typreceive;
	private Serializable typsend;
	private Serializable typmodin;
	private Serializable typmodout;
	private Serializable typanalyze;
	private Serializable typalign;
	private Serializable typstorage;
	private boolean typnotnull;
	private int typbasetype;
	private int typtypmod;
	private int typndims;
	private int typcollation;
	private Serializable typdefaultbin;
	private String typdefault;
	private Serializable typacl;

	public PgTypeId() {
	}

	public PgTypeId(String typname, int typnamespace, int typowner, short typlen, boolean typbyval,
			Serializable typtype, Serializable typcategory, boolean typispreferred, boolean typisdefined,
			Serializable typdelim, int typrelid, int typelem, int typarray, Serializable typinput,
			Serializable typoutput, Serializable typreceive, Serializable typsend, Serializable typmodin,
			Serializable typmodout, Serializable typanalyze, Serializable typalign, Serializable typstorage,
			boolean typnotnull, int typbasetype, int typtypmod, int typndims, int typcollation) {
		this.typname = typname;
		this.typnamespace = typnamespace;
		this.typowner = typowner;
		this.typlen = typlen;
		this.typbyval = typbyval;
		this.typtype = typtype;
		this.typcategory = typcategory;
		this.typispreferred = typispreferred;
		this.typisdefined = typisdefined;
		this.typdelim = typdelim;
		this.typrelid = typrelid;
		this.typelem = typelem;
		this.typarray = typarray;
		this.typinput = typinput;
		this.typoutput = typoutput;
		this.typreceive = typreceive;
		this.typsend = typsend;
		this.typmodin = typmodin;
		this.typmodout = typmodout;
		this.typanalyze = typanalyze;
		this.typalign = typalign;
		this.typstorage = typstorage;
		this.typnotnull = typnotnull;
		this.typbasetype = typbasetype;
		this.typtypmod = typtypmod;
		this.typndims = typndims;
		this.typcollation = typcollation;
	}

	public PgTypeId(String typname, int typnamespace, int typowner, short typlen, boolean typbyval,
			Serializable typtype, Serializable typcategory, boolean typispreferred, boolean typisdefined,
			Serializable typdelim, int typrelid, int typelem, int typarray, Serializable typinput,
			Serializable typoutput, Serializable typreceive, Serializable typsend, Serializable typmodin,
			Serializable typmodout, Serializable typanalyze, Serializable typalign, Serializable typstorage,
			boolean typnotnull, int typbasetype, int typtypmod, int typndims, int typcollation,
			Serializable typdefaultbin, String typdefault, Serializable typacl) {
		this.typname = typname;
		this.typnamespace = typnamespace;
		this.typowner = typowner;
		this.typlen = typlen;
		this.typbyval = typbyval;
		this.typtype = typtype;
		this.typcategory = typcategory;
		this.typispreferred = typispreferred;
		this.typisdefined = typisdefined;
		this.typdelim = typdelim;
		this.typrelid = typrelid;
		this.typelem = typelem;
		this.typarray = typarray;
		this.typinput = typinput;
		this.typoutput = typoutput;
		this.typreceive = typreceive;
		this.typsend = typsend;
		this.typmodin = typmodin;
		this.typmodout = typmodout;
		this.typanalyze = typanalyze;
		this.typalign = typalign;
		this.typstorage = typstorage;
		this.typnotnull = typnotnull;
		this.typbasetype = typbasetype;
		this.typtypmod = typtypmod;
		this.typndims = typndims;
		this.typcollation = typcollation;
		this.typdefaultbin = typdefaultbin;
		this.typdefault = typdefault;
		this.typacl = typacl;
	}

	@Column(name = "typname", nullable = false, length = 64)
	public String getTypname() {
		return this.typname;
	}

	public void setTypname(String typname) {
		this.typname = typname;
	}

	@Column(name = "typnamespace", nullable = false)
	public int getTypnamespace() {
		return this.typnamespace;
	}

	public void setTypnamespace(int typnamespace) {
		this.typnamespace = typnamespace;
	}

	@Column(name = "typowner", nullable = false)
	public int getTypowner() {
		return this.typowner;
	}

	public void setTypowner(int typowner) {
		this.typowner = typowner;
	}

	@Column(name = "typlen", nullable = false)
	public short getTyplen() {
		return this.typlen;
	}

	public void setTyplen(short typlen) {
		this.typlen = typlen;
	}

	@Column(name = "typbyval", nullable = false)
	public boolean isTypbyval() {
		return this.typbyval;
	}

	public void setTypbyval(boolean typbyval) {
		this.typbyval = typbyval;
	}

	@Column(name = "typtype", nullable = false)
	public Serializable getTyptype() {
		return this.typtype;
	}

	public void setTyptype(Serializable typtype) {
		this.typtype = typtype;
	}

	@Column(name = "typcategory", nullable = false)
	public Serializable getTypcategory() {
		return this.typcategory;
	}

	public void setTypcategory(Serializable typcategory) {
		this.typcategory = typcategory;
	}

	@Column(name = "typispreferred", nullable = false)
	public boolean isTypispreferred() {
		return this.typispreferred;
	}

	public void setTypispreferred(boolean typispreferred) {
		this.typispreferred = typispreferred;
	}

	@Column(name = "typisdefined", nullable = false)
	public boolean isTypisdefined() {
		return this.typisdefined;
	}

	public void setTypisdefined(boolean typisdefined) {
		this.typisdefined = typisdefined;
	}

	@Column(name = "typdelim", nullable = false)
	public Serializable getTypdelim() {
		return this.typdelim;
	}

	public void setTypdelim(Serializable typdelim) {
		this.typdelim = typdelim;
	}

	@Column(name = "typrelid", nullable = false)
	public int getTyprelid() {
		return this.typrelid;
	}

	public void setTyprelid(int typrelid) {
		this.typrelid = typrelid;
	}

	@Column(name = "typelem", nullable = false)
	public int getTypelem() {
		return this.typelem;
	}

	public void setTypelem(int typelem) {
		this.typelem = typelem;
	}

	@Column(name = "typarray", nullable = false)
	public int getTyparray() {
		return this.typarray;
	}

	public void setTyparray(int typarray) {
		this.typarray = typarray;
	}

	@Column(name = "typinput", nullable = false)
	public Serializable getTypinput() {
		return this.typinput;
	}

	public void setTypinput(Serializable typinput) {
		this.typinput = typinput;
	}

	@Column(name = "typoutput", nullable = false)
	public Serializable getTypoutput() {
		return this.typoutput;
	}

	public void setTypoutput(Serializable typoutput) {
		this.typoutput = typoutput;
	}

	@Column(name = "typreceive", nullable = false)
	public Serializable getTypreceive() {
		return this.typreceive;
	}

	public void setTypreceive(Serializable typreceive) {
		this.typreceive = typreceive;
	}

	@Column(name = "typsend", nullable = false)
	public Serializable getTypsend() {
		return this.typsend;
	}

	public void setTypsend(Serializable typsend) {
		this.typsend = typsend;
	}

	@Column(name = "typmodin", nullable = false)
	public Serializable getTypmodin() {
		return this.typmodin;
	}

	public void setTypmodin(Serializable typmodin) {
		this.typmodin = typmodin;
	}

	@Column(name = "typmodout", nullable = false)
	public Serializable getTypmodout() {
		return this.typmodout;
	}

	public void setTypmodout(Serializable typmodout) {
		this.typmodout = typmodout;
	}

	@Column(name = "typanalyze", nullable = false)
	public Serializable getTypanalyze() {
		return this.typanalyze;
	}

	public void setTypanalyze(Serializable typanalyze) {
		this.typanalyze = typanalyze;
	}

	@Column(name = "typalign", nullable = false)
	public Serializable getTypalign() {
		return this.typalign;
	}

	public void setTypalign(Serializable typalign) {
		this.typalign = typalign;
	}

	@Column(name = "typstorage", nullable = false)
	public Serializable getTypstorage() {
		return this.typstorage;
	}

	public void setTypstorage(Serializable typstorage) {
		this.typstorage = typstorage;
	}

	@Column(name = "typnotnull", nullable = false)
	public boolean isTypnotnull() {
		return this.typnotnull;
	}

	public void setTypnotnull(boolean typnotnull) {
		this.typnotnull = typnotnull;
	}

	@Column(name = "typbasetype", nullable = false)
	public int getTypbasetype() {
		return this.typbasetype;
	}

	public void setTypbasetype(int typbasetype) {
		this.typbasetype = typbasetype;
	}

	@Column(name = "typtypmod", nullable = false)
	public int getTyptypmod() {
		return this.typtypmod;
	}

	public void setTyptypmod(int typtypmod) {
		this.typtypmod = typtypmod;
	}

	@Column(name = "typndims", nullable = false)
	public int getTypndims() {
		return this.typndims;
	}

	public void setTypndims(int typndims) {
		this.typndims = typndims;
	}

	@Column(name = "typcollation", nullable = false)
	public int getTypcollation() {
		return this.typcollation;
	}

	public void setTypcollation(int typcollation) {
		this.typcollation = typcollation;
	}

	@Column(name = "typdefaultbin")
	public Serializable getTypdefaultbin() {
		return this.typdefaultbin;
	}

	public void setTypdefaultbin(Serializable typdefaultbin) {
		this.typdefaultbin = typdefaultbin;
	}

	@Column(name = "typdefault")
	public String getTypdefault() {
		return this.typdefault;
	}

	public void setTypdefault(String typdefault) {
		this.typdefault = typdefault;
	}

	@Column(name = "typacl")
	public Serializable getTypacl() {
		return this.typacl;
	}

	public void setTypacl(Serializable typacl) {
		this.typacl = typacl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PgTypeId))
			return false;
		PgTypeId castOther = (PgTypeId) other;

		return ((this.getTypname() == castOther.getTypname()) || (this.getTypname() != null
				&& castOther.getTypname() != null && this.getTypname().equals(castOther.getTypname())))
				&& (this.getTypnamespace() == castOther.getTypnamespace())
				&& (this.getTypowner() == castOther.getTypowner()) && (this.getTyplen() == castOther.getTyplen())
				&& (this.isTypbyval() == castOther.isTypbyval())
				&& ((this.getTyptype() == castOther.getTyptype()) || (this.getTyptype() != null
						&& castOther.getTyptype() != null && this.getTyptype().equals(castOther.getTyptype())))
				&& ((this.getTypcategory() == castOther.getTypcategory())
						|| (this.getTypcategory() != null && castOther.getTypcategory() != null
								&& this.getTypcategory().equals(castOther.getTypcategory())))
				&& (this.isTypispreferred() == castOther.isTypispreferred())
				&& (this.isTypisdefined() == castOther.isTypisdefined())
				&& ((this.getTypdelim() == castOther.getTypdelim()) || (this.getTypdelim() != null
						&& castOther.getTypdelim() != null && this.getTypdelim().equals(castOther.getTypdelim())))
				&& (this.getTyprelid() == castOther.getTyprelid()) && (this.getTypelem() == castOther.getTypelem())
				&& (this.getTyparray() == castOther.getTyparray())
				&& ((this.getTypinput() == castOther.getTypinput()) || (this.getTypinput() != null
						&& castOther.getTypinput() != null && this.getTypinput().equals(castOther.getTypinput())))
				&& ((this.getTypoutput() == castOther.getTypoutput()) || (this.getTypoutput() != null
						&& castOther.getTypoutput() != null && this.getTypoutput().equals(castOther.getTypoutput())))
				&& ((this.getTypreceive() == castOther.getTypreceive()) || (this.getTypreceive() != null
						&& castOther.getTypreceive() != null && this.getTypreceive().equals(castOther.getTypreceive())))
				&& ((this.getTypsend() == castOther.getTypsend()) || (this.getTypsend() != null
						&& castOther.getTypsend() != null && this.getTypsend().equals(castOther.getTypsend())))
				&& ((this.getTypmodin() == castOther.getTypmodin()) || (this.getTypmodin() != null
						&& castOther.getTypmodin() != null && this.getTypmodin().equals(castOther.getTypmodin())))
				&& ((this.getTypmodout() == castOther.getTypmodout()) || (this.getTypmodout() != null
						&& castOther.getTypmodout() != null && this.getTypmodout().equals(castOther.getTypmodout())))
				&& ((this.getTypanalyze() == castOther.getTypanalyze()) || (this.getTypanalyze() != null
						&& castOther.getTypanalyze() != null && this.getTypanalyze().equals(castOther.getTypanalyze())))
				&& ((this.getTypalign() == castOther.getTypalign()) || (this.getTypalign() != null
						&& castOther.getTypalign() != null && this.getTypalign().equals(castOther.getTypalign())))
				&& ((this.getTypstorage() == castOther.getTypstorage()) || (this.getTypstorage() != null
						&& castOther.getTypstorage() != null && this.getTypstorage().equals(castOther.getTypstorage())))
				&& (this.isTypnotnull() == castOther.isTypnotnull())
				&& (this.getTypbasetype() == castOther.getTypbasetype())
				&& (this.getTyptypmod() == castOther.getTyptypmod()) && (this.getTypndims() == castOther.getTypndims())
				&& (this.getTypcollation() == castOther.getTypcollation())
				&& ((this.getTypdefaultbin() == castOther.getTypdefaultbin())
						|| (this.getTypdefaultbin() != null && castOther.getTypdefaultbin() != null
								&& this.getTypdefaultbin().equals(castOther.getTypdefaultbin())))
				&& ((this.getTypdefault() == castOther.getTypdefault()) || (this.getTypdefault() != null
						&& castOther.getTypdefault() != null && this.getTypdefault().equals(castOther.getTypdefault())))
				&& ((this.getTypacl() == castOther.getTypacl()) || (this.getTypacl() != null
						&& castOther.getTypacl() != null && this.getTypacl().equals(castOther.getTypacl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTypname() == null ? 0 : this.getTypname().hashCode());
		result = 37 * result + this.getTypnamespace();
		result = 37 * result + this.getTypowner();
		result = 37 * result + this.getTyplen();
		result = 37 * result + (this.isTypbyval() ? 1 : 0);
		result = 37 * result + (getTyptype() == null ? 0 : this.getTyptype().hashCode());
		result = 37 * result + (getTypcategory() == null ? 0 : this.getTypcategory().hashCode());
		result = 37 * result + (this.isTypispreferred() ? 1 : 0);
		result = 37 * result + (this.isTypisdefined() ? 1 : 0);
		result = 37 * result + (getTypdelim() == null ? 0 : this.getTypdelim().hashCode());
		result = 37 * result + this.getTyprelid();
		result = 37 * result + this.getTypelem();
		result = 37 * result + this.getTyparray();
		result = 37 * result + (getTypinput() == null ? 0 : this.getTypinput().hashCode());
		result = 37 * result + (getTypoutput() == null ? 0 : this.getTypoutput().hashCode());
		result = 37 * result + (getTypreceive() == null ? 0 : this.getTypreceive().hashCode());
		result = 37 * result + (getTypsend() == null ? 0 : this.getTypsend().hashCode());
		result = 37 * result + (getTypmodin() == null ? 0 : this.getTypmodin().hashCode());
		result = 37 * result + (getTypmodout() == null ? 0 : this.getTypmodout().hashCode());
		result = 37 * result + (getTypanalyze() == null ? 0 : this.getTypanalyze().hashCode());
		result = 37 * result + (getTypalign() == null ? 0 : this.getTypalign().hashCode());
		result = 37 * result + (getTypstorage() == null ? 0 : this.getTypstorage().hashCode());
		result = 37 * result + (this.isTypnotnull() ? 1 : 0);
		result = 37 * result + this.getTypbasetype();
		result = 37 * result + this.getTyptypmod();
		result = 37 * result + this.getTypndims();
		result = 37 * result + this.getTypcollation();
		result = 37 * result + (getTypdefaultbin() == null ? 0 : this.getTypdefaultbin().hashCode());
		result = 37 * result + (getTypdefault() == null ? 0 : this.getTypdefault().hashCode());
		result = 37 * result + (getTypacl() == null ? 0 : this.getTypacl().hashCode());
		return result;
	}

}
