package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PgUserMapping generated by hbm2java
 */
@Entity
@Table(name = "pg_user_mapping", schema = "pg_catalog", uniqueConstraints = { @UniqueConstraint(columnNames = "oid"),
		@UniqueConstraint(columnNames = { "umuser", "umserver" }) })
public class PgUserMapping implements java.io.Serializable {

	private PgUserMappingId id;

	public PgUserMapping() {
	}

	public PgUserMapping(PgUserMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "umuser", column = @Column(name = "umuser", nullable = false)),
			@AttributeOverride(name = "umserver", column = @Column(name = "umserver", nullable = false)),
			@AttributeOverride(name = "umoptions", column = @Column(name = "umoptions")) })
	public PgUserMappingId getId() {
		return this.id;
	}

	public void setId(PgUserMappingId id) {
		this.id = id;
	}

}
