package com.model;
// Generated Nov 11, 2017 10:37:01 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Provider generated by hbm2java
 */
@Entity
@Table(name = "provider", schema = "public")
public class Provider implements java.io.Serializable {

	private ProviderId id;

	public Provider() {
	}

	public Provider(ProviderId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCard", column = @Column(name = "ID_card", nullable = false, length = 64)),
			@AttributeOverride(name = "firstname", column = @Column(name = "Firstname", length = 64)),
			@AttributeOverride(name = "lastName", column = @Column(name = "LastName", length = 64)),
			@AttributeOverride(name = "profession", column = @Column(name = "Profession", length = 64)),
			@AttributeOverride(name = "login", column = @Column(name = "Login", nullable = false, length = 64)),
			@AttributeOverride(name = "password", column = @Column(name = "Password", length = 64)),
			@AttributeOverride(name = "socialStatus", column = @Column(name = "SocialStatus", length = 64)),
			@AttributeOverride(name = "birthDate", column = @Column(name = "BirthDate", length = 4)) })
	public ProviderId getId() {
		return this.id;
	}

	public void setId(ProviderId id) {
		this.id = id;
	}

}
